### ISSUE TITLE
Can't run Dashboard tool in windows10/python3.8.1

### ISSUE THREAD

**Issue by sergge1** [esphome/issues#1065]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Windows 10
Python 3.8.1
pip 19.2.3
esphome:latest

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266, sonoff mini

**Affected component:**

**Description of problem:**
can't run the command within Windows (terminal) to start Dashboard `esphome config/ dashboard`
Command returns with:

```sh
C:\Users\sss>esphome config/ dashboard
[32mINFO Starting dashboard web server on port 6052 and configuration dir config/...[0m
Traceback (most recent call last):
File "c:\users\sss\programs\python\python38\lib\runpy.py", line 193, in _run_module_as_main
return _run_code(code, main_globals, None,
File "c:\users\sss\programs\python\python38\lib\runpy.py", line 86, in _run_code
exec(code, run_globals)
File "C:\Users\Sss\Programs\Python\Python38\Scripts\esphome.exe\__main__.py", line 9, in <module>
File "c:\users\sss\programs\python\python38\lib\site-packages\esphome\__main__.py", line 566, in main
return run_esphome(sys.argv)
File "c:\users\sss\programs\python\python38\lib\site-packages\esphome\__main__.py", line 535, in run_esphome
return PRE_CONFIG_ACTIONS[args.command](args)
File "c:\users\sss\programs\python\python38\lib\site-packages\esphome\__main__.py", line 365, in command_dashboard
return dashboard.start_web_server(args)
File "c:\users\sss\programs\python\python38\lib\site-packages\esphome\dashboard\dashboard.py", line 752, in start_web_server
app.listen(args.port)
File "c:\users\sss\programs\python\python38\lib\site-packages\tornado\web.py", line 2042, in listen
server.listen(port, address)
File "c:\users\sss\programs\python\python38\lib\site-packages\tornado\tcpserver.py", line 144, in listen
self.add_sockets(sockets)
File "c:\users\sss\programs\python\python38\lib\site-packages\tornado\tcpserver.py", line 157, in add_sockets
self._handlers[sock.fileno()] = add_accept_handler(
File "c:\users\sss\programs\python\python38\lib\site-packages\tornado\netutil.py", line 268, in add_accept_handler
io_loop.add_handler(sock, accept_handler, IOLoop.READ)
File "c:\users\sss\programs\python\python38\lib\site-packages\tornado\platform\asyncio.py", line 79, in add_handler
self.asyncio_loop.add_reader(
File "c:\users\sss\programs\python\python38\lib\asyncio\events.py", line 501, in add_reader
raise NotImplementedError
NotImplementedError
C:\Users\sss>
```

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**

**Comment by glmnet** [comment]
As stated in docs, it is not supported on windows. You can make it work in WSL though.
