### ISSUE TITLE
ESPHome Dashboard Not Uploading

### ISSUE THREAD

**Issue by schreineradam** [esphome/issues#1114]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Raspberry Pi 3
Home Assistant 0.107.7
ESPHome 1.14.3

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMCU ESP8266

**Affected component:**

Dashboard

**Description of problem:**

1) Cannot upload to ESP directly from the dashboard however it works when I update all.
2) Cannot see anything under the drop down in order to flash through USB. The drop down is there but nothing happens when I click it.

**Problem-relevant YAML-configuration entries:**
```yaml
Not relevant.
```

**Logs (if applicable):**

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: ESPHome
 ESPHome Hass.io add-on for intelligently managing all your ESP8266/ESP32 devices.
-----------------------------------------------------------
 Add-on version: 1.14.3
 You are running the latest version of this add-on.
 System: HassOS 3.12  (armv7 / raspberrypi3)
 Home Assistant version: 0.107.7
 Supervisor version: 209
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-nginx.sh: executing... 
[cont-init.d] 20-nginx.sh: exited 0.
[cont-init.d] 30-esphome.sh: executing... 
[cont-init.d] 30-esphome.sh: exited 0.
[cont-init.d] 40-migrate.sh: executing... 
[cont-init.d] 40-migrate.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[21:57:55] INFO: Waiting for dashboard to come up...
[21:57:55] INFO: Starting ESPHome dashboard...
INFO Starting dashboard web server on unix socket /var/run/esphome.sock and configuration dir /config/esphome...
[21:57:57] INFO: Starting NGINX...
INFO 304 GET / (0.0.0.0) 58.57ms
INFO 101 GET /ace (0.0.0.0) 2.02ms
INFO Running command 'esphome --dashboard -q /config/esphome vscode --ace'
INFO 101 GET /upload (0.0.0.0) 2.51ms
ERROR Uncaught exception GET /upload (0.0.0.0)
HTTPServerRequest(protocol='http', host='redacted.com', method='GET', uri='/upload', version='HTTP/1.1', remote_ip='0.0.0.0')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/websocket.py", line 546, in _run_callback
    result = callback(*args, **kwargs)
  File "/opt/esphome/esphome/dashboard/dashboard.py", line 127, in decorator
    return func(self, *args, **kwargs)
  File "/opt/esphome/esphome/dashboard/dashboard.py", line 199, in on_message
    handlers[type_](self, json_message)
  File "/opt/esphome/esphome/dashboard/dashboard.py", line 206, in handle_spawn
    command = self.build_command(json_message)
  File "/opt/esphome/esphome/dashboard/dashboard.py", line 274, in build_command
    json_message["port"]]
KeyError: 'port'
INFO 304 GET / (0.0.0.0) 6.68ms
INFO 101 GET /ace (0.0.0.0) 1.85ms
INFO Running command 'esphome --dashboard -q /config/esphome vscode --ace'
INFO 101 GET /update-all (0.0.0.0) 2.16ms
INFO Running command 'esphome --dashboard /config/esphome update-all'
INFO Process exited with return code 1
```

**Additional information and things you've tried:**

Sorry, new to ESPHome. Not sure exactly what else to try.

**Comment by pruchai** [comment]
looks like your .yaml file is incorrect

``` 
web_server:
  port: 80
```
