### ISSUE TITLE
ERROR Running command failed: could not open port 'COM1': FileNotFoundError(2, 'The system cannot find the file specified.'

### ISSUE THREAD

**Issue by jamiebegin** [esphome/issues#1358]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESP8266 NodeMCU CP2102 ESP-12E

Version: 1.14.5

**Affected component:**

Command line build/run

**Description of problem:**
I'm using Windows 10 and Python 3.7.2 , both 64-bit versions. When I use the `run` command, ESPHome builds the config and then gets to the step where it tries to upload it to the MCU.
```
[32mINFO Successfully compiled program.[0m
Found multiple options, please choose one:
  [1] COM1 (Silicon Labs CP210x USB to UART Bridge (COM1))
  [2] Over The Air (clubhouse.local)
(number): 1
[32mINFO Running:  esptool.py --before default_reset --after hard_reset --baud 460800 --chip esp8266 --port COM1 write_flash 0x0 'clubhouse\.pioenvs\clubhouse\firmware.bin'[0m
esptool.py v2.8
Serial port COM1
[31mERROR Running command failed: could not open port 'COM1': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)[0m
[31mERROR Please try running esptool.py --before default_reset --after hard_reset --baud 460800 --chip esp8266 --port COM1 write_flash 0x0 'clubhouse\.pioenvs\clubhouse\firmware.bin' locally.[0m
[32mINFO Upload with baud rate 460800 failed. Trying again with baud rate 115200.[0m
[32mINFO Running:  esptool.py --before default_reset --after hard_reset --baud 115200 --chip esp8266 --port COM1 write_flash 0x0 'clubhouse\.pioenvs\clubhouse\firmware.bin'[0m
esptool.py v2.8
Serial port COM1
[31mERROR Running command failed: could not open port 'COM1': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)[0m
[31mERROR Please try running esptool.py --before default_reset --after hard_reset --baud 115200 --chip esp8266 --port COM1 write_flash 0x0 'clubhouse\.pioenvs\clubhouse\firmware.bin' locally.[0m
```

Manually running the command (as mentioned in the debug dump) gives me the same error:
```
C:\Users\jamie\Documents\esphome>esptool.py --before default_reset --after hard_reset --baud 115200 --chip esp8266 --port COM1 write_flash 0x0 clubhouse\.pioenvs\clubhouse\firmware.bin
esptool.py v2.8
Serial port COM1
Traceback (most recent call last):
  File "C:\Program Files\Python37\Scripts\esptool.py-script.py", line 11, in <module>
    load_entry_point('esptool==2.8', 'console_scripts', 'esptool.py')()
  File "c:\program files\python37\lib\site-packages\esptool.py", line 3194, in _main
    main()
  File "c:\program files\python37\lib\site-packages\esptool.py", line 2889, in main
    esp = chip_class(each_port, initial_baud, args.trace)
  File "c:\program files\python37\lib\site-packages\esptool.py", line 237, in __init__
    self._port = serial.serial_for_url(port)
  File "c:\program files\python37\lib\site-packages\serial\__init__.py", line 88, in serial_for_url
    instance.open()
  File "c:\program files\python37\lib\site-packages\serial\serialwin32.py", line 62, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM1': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
```

I can confirm that my ESP is connected to `COM1.` The upload function in Arduino IDE works fine at 115200 baud.

**Comment by jamiebegin** [comment]
I'm able to reproduce this error with a basic Python script:
```
import serial
import serial.tools.list_ports as port_list

ports = list(port_list.comports())
for p in ports:
    print (p)
    ser = serial.Serial(p.device)
 ```
I am running both this test script and ESPHome from an elevated command prompt. I will keep testing and see if I can figure this out.

**Comment by jamiebegin** [comment]
Rebooting my system resolved the problem. Even reopening Arduino IDE, uploading a sketch that outputted serial data, and then closing the IDE there were no further problems.  Closing the issue.
