### ISSUE TITLE
MacOS Big Sur dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found

### ISSUE THREAD

**Issue by rob-deutsch** [esphome/issues#1647]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

macOS Big Sur

**ESP (ESP32/ESP8266, Board/Sonoff):**

All

**ESPHome version (latest production, beta, dev branch)**

All

**Affected component:**

esphome/util.py

**Description of problem:**
esphome can not connect to ESP8266/ESP32 on macOS Big Sur. Infact, it will crash.

The problem is because PySerial does not support macOS Big Sur.

Esptool suffered from exactly the same problem: https://github.com/espressif/esptool/issues/540

**Problem-relevant YAML-configuration entries:**
```yaml
[any yaml file]
```

**Logs (if applicable):**

```
INFO Reading configuration homehub.yaml...
Traceback (most recent call last):
  File "/Users/rob/tmp/esphome/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/Users/rob/tmp/esphome/esphome/esphome/__main__.py", line 554, in main
    return run_esphome(sys.argv)
  File "/Users/rob/tmp/esphome/esphome/esphome/__main__.py", line 541, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/Users/rob/tmp/esphome/esphome/esphome/__main__.py", line 302, in command_logs
    show_ota=False, show_mqtt=True, show_api=True)
  File "/Users/rob/tmp/esphome/esphome/esphome/__main__.py", line 51, in choose_upload_log_host
    for port in get_serial_ports():
  File "/Users/rob/tmp/esphome/esphome/esphome/util.py", line 270, in get_serial_ports
    from serial.tools.list_ports import comports
  File "/Users/rob/tmp/esphome/lib/python3.7/site-packages/serial/tools/list_ports.py", line 29, in <module>
    from serial.tools.list_ports_posix import comports
  File "/Users/rob/tmp/esphome/lib/python3.7/site-packages/serial/tools/list_ports_posix.py", line 31, in <module>
    from serial.tools.list_ports_osx import comports
  File "/Users/rob/tmp/esphome/lib/python3.7/site-packages/serial/tools/list_ports_osx.py", line 32, in <module>
    kIOMasterPortDefault = ctypes.c_void_p.in_dll(iokit, "kIOMasterPortDefault")
ValueError: dlsym(RTLD_DEFAULT, kIOMasterPortDefault): symbol not found

```

**Additional information and things you've tried:**

**Comment by rob-deutsch** [comment]
PySerial has been fixed, but its not fully rolled out: https://github.com/pyserial/pyserial/issues/509#issuecomment-726966076

Esptool chose to implement a work around for users who aren't using a sufficiently recent version of PySerial: https://github.com/espressif/esptool/blob/0594249a32ef1fcbeac62bb52fca5e079c858f1a/esptool.py#L63
