### ISSUE TITLE
Unicode passwords generate 500 Error

### ISSUE THREAD

**Issue by ASMfreaK** [esphome/issues#169]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Debian 9, esphome in virtualenv

**ESP (ESP32/ESP8266, Board/Sonoff):**

Any

**Affected component:**

Wizard (no idea which page to link)

**Description of problem:**
Try adding a non-ascii password from Wizard

**Problem-relevant YAML-configuration entries:**
N/A

**Traceback (if applicable):**

```
ERROR Uncaught exception POST /wizard.html (192.168.1.2)
HTTPServerRequest(protocol='http', host='<REDACTED>:6052', method='POST', uri='/wizard.html', version='HTTP/1.1', remote_ip='<REDACTED>')
Traceback (most recent call last):
  File "<REDACTED>/local/lib/python2.7/site-packages/tornado/web.py", line 1590, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "<REDACTED>/local/lib/python2.7/site-packages/esphome/dashboard/dashboard.py", line 74, in decorator
    return func(self, *args, **kwargs)
  File "<REDACTED>/local/lib/python2.7/site-packages/esphome/dashboard/dashboard.py", line 228, in post
    wizard.wizard_write(path=destination, **kwargs)
  File "<REDACTED>/local/lib/python2.7/site-packages/esphome/wizard.py", line 83, in wizard_write
    f_handle.write(wizard_file(**kwargs))
  File "<REDACTED>/local/lib/python2.7/site-packages/esphome/wizard.py", line 68, in wizard_file
    config += u"  password: '{0}'\n\nota:\n  password: '{0}'\n".format(kwargs['password'])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)
ERROR 500 POST /wizard.html (192.168.1.2) 6.40ms
```

**Additional information and things you've tried:**
I tried modifying `dashboard.py` to use unicode string in join in dict comprehension, but it just moved the error there.

**Comment by ASMfreaK** [comment]
Update:
unicode passwords fail to upload:
```
INFO Uploading <REDACTED>/firmware.bin (332032 bytes)
Traceback (most recent call last):
  File "<REDACTED>/bin/esphome", line 10, in <module>
    sys.exit(main())
  File "<REDACTED>/local/lib/python2.7/site-packages/esphome/__main__.py", line 484, in main
    return run_esphome(sys.argv)
  File "<REDACTED>/local/lib/python2.7/site-packages/esphome/__main__.py", line 474, in run_esphome
    return POST_CONFIG_ACTIONS[args.command](args, config)
  File "<REDACTED>/local/lib/python2.7/site-packages/esphome/__main__.py", line 316, in command_run
    exit_code = upload_program(config, args, port)
  File "<REDACTED>/local/lib/python2.7/site-packages/esphome/__main__.py", line 205, in upload_program
    res = espota2.run_ota(host, remote_port, password, CORE.firmware_bin)
  File "<REDACTED>/local/lib/python2.7/site-packages/esphome/espota2.py", line 297, in run_ota
    return run_ota_impl_(remote_host, remote_port, password, filename)
  File "<REDACTED>/local/lib/python2.7/site-packages/esphome/espota2.py", line 284, in run_ota_impl_
    perform_ota(sock, password, file_handle, filename)
  File "<REDACTED>/local/lib/python2.7/site-packages/esphome/espota2.py", line 198, in perform_ota
    result_md5.update(password.encode())
```

**Comment by ASMfreaK** [comment]
The fix is:
```
esphome/espota2.py, line 198, in perform_ota
    result_md5.update(password.encode('utf-8'))
```
