### ISSUE TITLE
Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

### ISSUE THREAD

**Issue by nipender31234** [esphome/issues#1710]
E:\python programs>pip install audio
Collecting audio
  Using cached audio-1.5.0.tar.gz (2.1 kB)
Collecting audio.bitstream
  Using cached audio.bitstream-2.5.4.tar.gz (1.2 kB)
Collecting bitstream==2.5.4
  Using cached bitstream-2.5.4.tar.gz (168 kB)
Collecting audio.coders
  Using cached audio.coders-4.0.2.tar.gz (682 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\mrsin\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\mrsin\\AppData\\Local\\Temp\\pip-install-bes6yhin\\audio-coders_5e2003c3170a407b87ee8d6bebe577d3\\setup.py'"'"'; __file__='"'"'C:\\Users\\mrsin\\AppData\\Local\\Temp\\pip-install-bes6yhin\\audio-coders_5e2003c3170a407b87ee8d6bebe577d3\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\mrsin\AppData\Local\Temp\pip-pip-egg-info-l_lqk2hi'
         cwd: C:\Users\mrsin\AppData\Local\Temp\pip-install-bes6yhin\audio-coders_5e2003c3170a407b87ee8d6bebe577d3\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\mrsin\AppData\Local\Temp\pip-install-bes6yhin\audio-coders_5e2003c3170a407b87ee8d6bebe577d3\setup.py", line 5, in <module>
        import ConfigParser
    ModuleNotFoundError: No module named 'ConfigParser'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by nipender31234** [comment]
somebody help me .
