### ISSUE TITLE
Mqtt clean fail

### ISSUE THREAD

**Issue by raidnet-ms** [esphome/issues#1743]
Hello,

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

I'm using Hassio on Raspberry Pi4 8Gb (64bit version)
ESPhome configured with SSL with no error
Mqtt is configured with SSL and ACL with no error from MQTT supervisor log (other esp devices are working properly and so Zigbee devices used with Conbee).

**ESP (ESP32/ESP8266, Board/Sonoff):**
The problem exist with every board i tested: esp01, nodemcu, d1mini

ESPHome version latest production

**Affected component:**

**Description of problem:**
While trying to activa an "MQTT CLEAN" from the ESP dashboard i get this error, with every yaml config, even with a basic file (just wifi, api ad ota config):

(CLEAN MQTT LOG FROM ESP dashboard):

`INFO Reading configuration /config/esphome/test.yaml...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 11, in <module>
    load_entry_point('esphome', 'console_scripts', 'esphome')()
  File "/opt/esphome/esphome/__main__.py", line 554, in main
    return run_esphome(sys.argv)
  File "/opt/esphome/esphome/__main__.py", line 541, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/opt/esphome/esphome/__main__.py", line 328, in command_clean_mqtt
    return clean_mqtt(config, args)
  File "/opt/esphome/esphome/__main__.py", line 219, in clean_mqtt
    return mqtt.clear_topic(config, args.topic, args.username, args.password, args.client_id)
  File "/opt/esphome/esphome/mqtt.py", line 106, in clear_topic
    discovery_prefix = config[CONF_MQTT].get(CONF_DISCOVERY_PREFIX, 'homeassistant')
KeyError: 'mqtt'`

**Problem-relevant YAML-configuration entries:**
```yaml
###############################
esphome:
  name: $devicename
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "$devicename"
    password: !secret ap_password
captive_portal:
# Enable logging
logger:
# Enable Home Assistant API
api:
  password: !secret api_password
ota:
  password: !secret ota_password
#################################################################

status_led:
  pin:
    number: 1
    inverted: false
  id: led

switch:
    platform: gpio
    name: "heater"
    pin: 3
    id: switch01
```

**Logs (if applicable):**

```
ESPHOME supervisor log:

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: ESPHome
 ESPHome Hass.io add-on for intelligently managing all your ESP8266/ESP32 devices.
-----------------------------------------------------------
 Add-on version: 1.15.3
 You are running the latest version of this add-on.
 System: Home Assistant OS 5.9  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2020.12.2
 Home Assistant Supervisor: 2020.12.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-nginx.sh: executing... 
[cont-init.d] 20-nginx.sh: exited 0.
[cont-init.d] 30-esphome.sh: executing... 
[cont-init.d] 30-esphome.sh: exited 0.
[cont-init.d] 40-migrate.sh: executing... 
[cont-init.d] 40-migrate.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[14:12:42] INFO: Waiting for dashboard to come up...
[14:12:42] INFO: Starting ESPHome dashboard...
INFO Starting dashboard web server on unix socket /var/run/esphome.sock and configuration dir /config/esphome...
[14:12:44] INFO: Starting NGINX...
INFO 200 GET / (0.0.0.0) 87.57ms
INFO 200 GET /static/fonts/material-icons/material-icons.css?hash=ead4c276 (0.0.0.0) 14.57ms
INFO 200 GET /static/css/vendor/materialize/materialize.min.css?hash=ec1df3ba (0.0.0.0) 5.06ms
INFO 200 GET /static/css/vendor/materialize-stepper/materialize-stepper.min.css?hash=f4d254e9 (0.0.0.0) 3.89ms
INFO 200 GET /static/js/vendor/jquery-ui/jquery-ui.min.js?hash=cab3392d (0.0.0.0) 6.58ms
INFO 200 GET /static/css/esphome.css?hash=50406740 (0.0.0.0) 4.37ms
INFO 200 GET /static/js/vendor/jquery/jquery.min.js?hash=12108007 (0.0.0.0) 8.15ms
INFO 200 GET /static/js/vendor/jquery-validate/jquery.validate.min.js?hash=aad785d4 (0.0.0.0) 9.06ms
INFO 200 GET /static/js/vendor/materialize/materialize.min.js?hash=4be20daf (0.0.0.0) 5.45ms
INFO 200 GET /static/js/vendor/materialize-stepper/materialize-stepper.min.js?hash=ef217c59 (0.0.0.0) 3.58ms
INFO 200 GET /static/js/vendor/ace/ace.js?hash=65322f49 (0.0.0.0) 11.96ms
INFO 200 GET /static/js/esphome.js?hash=b418707c (0.0.0.0) 3.03ms
INFO 200 GET /static/fonts/material-icons/MaterialIcons-Regular.woff2 (0.0.0.0) 3.88ms
INFO 200 GET /static/js/vendor/ace/theme-dreamweaver.js (0.0.0.0) 4.32ms
INFO 200 GET /static/js/vendor/ace/mode-yaml.js (0.0.0.0) 5.57ms
INFO 101 GET /ace (0.0.0.0) 1.96ms
INFO Running command 'esphome --dashboard -q /config/esphome vscode --ace'
INFO 101 GET /upload (0.0.0.0) 2.26ms
INFO Running command 'esphome --dashboard /config/esphome/termostato.yaml run --upload-port /dev/ttyUSB0'
INFO 101 GET /upload (0.0.0.0) 2.40ms
INFO Running command 'esphome --dashboard /config/esphome/termostato.yaml run --upload-port /dev/ttyUSB0'
INFO 101 GET /clean (0.0.0.0) 1.81ms
INFO Running command 'esphome --dashboard /config/esphome/termostato.yaml clean'
INFO Process exited with return code 0
INFO 101 GET /compile (0.0.0.0) 1.79ms
INFO Running command 'esphome --dashboard /config/esphome/termostato.yaml compile'
INFO Process exited with return code 0
INFO 200 GET /download.bin?configuration=termostato.yaml (0.0.0.0) 12.50ms
INFO 200 GET / (0.0.0.0) 9.76ms
INFO 200 GET /static/fonts/material-icons/material-icons.css?hash=ead4c276 (0.0.0.0) 4.54ms
INFO 200 GET /static/css/vendor/materialize/materialize.min.css?hash=ec1df3ba (0.0.0.0) 6.37ms
INFO 200 GET /static/js/vendor/jquery-validate/jquery.validate.min.js?hash=aad785d4 (0.0.0.0) 3.38ms
INFO 200 GET /static/css/vendor/materialize-stepper/materialize-stepper.min.css?hash=f4d254e9 (0.0.0.0) 5.12ms
INFO 200 GET /static/css/esphome.css?hash=50406740 (0.0.0.0) 3.61ms
INFO 200 GET /static/js/vendor/materialize/materialize.min.js?hash=4be20daf (0.0.0.0) 6.87ms
INFO 200 GET /static/js/vendor/jquery-ui/jquery-ui.min.js?hash=cab3392d (0.0.0.0) 7.98ms
INFO 200 GET /static/js/vendor/materialize-stepper/materialize-stepper.min.js?hash=ef217c59 (0.0.0.0) 4.02ms
INFO 200 GET /static/js/vendor/jquery/jquery.min.js?hash=12108007 (0.0.0.0) 5.57ms
INFO 200 GET /static/js/vendor/ace/ace.js?hash=65322f49 (0.0.0.0) 13.87ms
INFO 200 GET /static/js/esphome.js?hash=b418707c (0.0.0.0) 5.00ms
INFO 200 GET /static/fonts/material-icons/MaterialIcons-Regular.woff2 (0.0.0.0) 4.22ms
INFO 200 GET /static/js/vendor/ace/theme-dreamweaver.js (0.0.0.0) 6.26ms
INFO 200 GET /static/js/vendor/ace/mode-yaml.js (0.0.0.0) 7.47ms
INFO 101 GET /ace (0.0.0.0) 2.37ms
INFO Running command 'esphome --dashboard -q /config/esphome vscode --ace'
INFO 101 GET /clean-mqtt (0.0.0.0) 2.01ms
INFO Running command 'esphome --dashboard /config/esphome/termostato.yaml clean-mqtt'
INFO Process exited with return code 1`


```

**Additional information and things you've tried:**

Mosquitto Broker Log:

`[13:57:28] INFO: Setup mosquitto configuration
[13:57:28] INFO: Found local users inside config
[13:57:28] INFO: Initialize Hass.io Add-on services
[13:57:28] INFO: Initialize Home Assistant discovery
[13:57:28] INFO: Start Mosquitto daemon
1609937848: mosquitto version 1.6.3 starting
1609937848: Config loaded from /etc/mosquitto.conf.
1609937848: Loading plugin: /usr/share/mosquitto/auth-plug.so
1609937848:  ├── Username/password checking enabled.
1609937848:  ├── TLS-PSK checking enabled.
1609937848:  └── Extended authentication not enabled.
1609937848: |-- *** auth-plug: startup
1609937848: Opening ipv4 listen socket on port 1883.
1609937848: Opening ipv6 listen socket on port 1883.
1609937848: Opening websockets listen socket on port 1884.
1609937848: Opening ipv4 listen socket on port 8883.
1609937848: Opening ipv6 listen socket on port 8883.
1609937848: Opening websockets listen socket on port 8884.
1609937849: Warning: Mosquitto should not be run as root/administrator.
1609937892: New connection from 172.30.32.1 on port 1883.
[INFO] found mqtt on local database
1609937892: New client connected from 172.30.32.1 as 3V1QifV6c05hAN80N7IX4j (p2, c1, k60, u'mqtt').
1609939649: Saving in-memory database to /data/mosquitto.db.`

thank you

**Comment by yahel2410** [comment]
Hi @raidnet-ms, did you find a solution for this? I'm facing the same issue

**Comment by raidnet-ms** [comment]
I was never able to make mqtt clean working, furthermore mqtt 5.1.1 has stopped working with esphome.
I partially solved the problem of zombie things with persistent will on mqtt integration settings.
Let me know if works for you.

**Comment by raidnet-ms** [comment]
Well this problem is persistent
