### ISSUE TITLE
Validation Crashes With Subsitutions in Lambdas

### ISSUE THREAD

**Issue by mtl010957** [esphome/issues#1853]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Tested in both Hass.io and Ubuntu 20.10

**ESP (ESP32/ESP8266, Board/Sonoff):**

D1Mini, NodeMCU, Sonoff

**ESPHome version (latest production, beta, dev branch)**

v1.17.0-dev

**Affected component:**

All

**Description of problem:**
Any configuration including a lambda with a substitution in it causes the validation process to crash with an error trace like this:
```
INFO Reading configuration git/esphome_config/dm01_test_sv1.yaml...
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "/home/michael/.local/bin/esphome", line 11, in <module>
    load_entry_point('esphome', 'console_scripts', 'esphome')()
  File "/home/michael/workspace/esphome/esphome/__main__.py", line 557, in main
    return run_esphome(sys.argv)
  File "/home/michael/workspace/esphome/esphome/__main__.py", line 535, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
  File "/home/michael/workspace/esphome/esphome/config.py", line 838, in read_config
    res = load_config(command_line_substitutions)
  File "/home/michael/workspace/esphome/esphome/config.py", line 696, in load_config
    return _load_config(command_line_substitutions)
  File "/home/michael/workspace/esphome/esphome/config.py", line 684, in _load_config
    result = validate_config(config, command_line_substitutions)
  File "/home/michael/workspace/esphome/esphome/config.py", line 599, in validate_config
    validated = comp.config_schema(conf)
  File "/home/michael/workspace/esphome/esphome/voluptuous_schema.py", line 30, in __call__
    res = super().__call__(data)
  File "/home/michael/.local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/home/michael/.local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/home/michael/workspace/esphome/esphome/voluptuous_schema.py", line 131, in validate_mapping
    cval = cvalue(key_path, value)
  File "/home/michael/.local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/home/michael/workspace/esphome/esphome/automation.py", line 101, in validator
    value = validator_(value)
  File "/home/michael/workspace/esphome/esphome/automation.py", line 94, in validator_
    return [schema(value)]
  File "/home/michael/workspace/esphome/esphome/voluptuous_schema.py", line 30, in __call__
    res = super().__call__(data)
  File "/home/michael/.local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/home/michael/.local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/home/michael/workspace/esphome/esphome/voluptuous_schema.py", line 131, in validate_mapping
    cval = cvalue(key_path, value)
  File "/home/michael/.local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/home/michael/workspace/esphome/esphome/config_validation.py", line 197, in validator
    return list_schema(value)
  File "/home/michael/workspace/esphome/esphome/voluptuous_schema.py", line 30, in __call__
    res = super().__call__(data)
  File "/home/michael/.local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/home/michael/.local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 635, in validate_sequence
    cval = validate(index_path, value)
  File "/home/michael/.local/lib/python3.8/site-packages/voluptuous/validators.py", line 205, in _run
    return self._exec(self._compiled, value, path)
  File "/home/michael/.local/lib/python3.8/site-packages/voluptuous/validators.py", line 285, in _exec
    v = func(path, v)
  File "/home/michael/.local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/home/michael/workspace/esphome/esphome/config_validation.py", line 1242, in validator
    value[key] = registry_entry.schema(value[key])
  File "/home/michael/workspace/esphome/esphome/voluptuous_schema.py", line 30, in __call__
    res = super().__call__(data)
  File "/home/michael/.local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/home/michael/.local/lib/python3.8/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/home/michael/workspace/esphome/esphome/config_validation.py", line 986, in lambda_
    value = make_data_base(Lambda(string_strict(value)), value)
  File "/home/michael/workspace/esphome/esphome/yaml_util.py", line 59, in make_data_base
    value.from_database(from_database)
  File "/home/michael/workspace/esphome/esphome/yaml_util.py", line 47, in from_database
    self._esp_range = database.esp_range
AttributeError: 'str' object has no attribute 'esp_range'
```
This error effectively stops any further progress so nothing can be compiled.

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
substitutions:
  devicename: dm01_sv1
  upper_devicename: DM01_SV1

esphome:
  name: ${devicename}
  platform: ESP8266
  board: d1_mini
  on_boot:
    then:
      - wait_until: mqtt.connected
      - delay: 2s
      - lambda: id(${devicename}_wifi_info_ip).publish_state(WiFi.localIP().toString().c_str());
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password
text_sensor:
  - platform: wifi_info
    ip_address:
      id: "${devicename}_wifi_info_ip"
      name: "${upper_devicename} IP"
```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
This yaml example is greatly simplified to illustrate the error, I use substitutions extensively in lambdas and have never had issues. I've isolated the issue to the changes introduced in commit [28e39f7](https://github.com/esphome/esphome/commit/28e39f7f765e91355d7d837630f32e965026c4d8), not sure exactly what part of that is causing the issue. Prior to that commit everything works as expected, the validation output should look like:
```
INFO Reading configuration git/esphome_config/dm01_test_sv1.yaml...
INFO Configuration is valid!
substitutions:
  devicename: dm01_sv1
  upper_devicename: DM01_SV1
esphome:
  name: dm01_sv1
  platform: ESP8266
  board: d1_mini
  on_boot:
  - then:
    - wait_until:
        condition:
          mqtt.connected: {}
    - delay: 2s
    - lambda: !lambda |-
        id(dm01_sv1_wifi_info_ip).publish_state(WiFi.localIP().toString().c_str());
    priority: 600.0
  arduino_version: espressif8266@2.6.2
  build_path: dm01_sv1
  platformio_options: {}
  esp8266_restore_from_flash: false
  board_flash_mode: dout
  includes: []
  libraries: []
wifi:
  domain: .local
  reboot_timeout: 15min
  power_save_mode: NONE
  fast_connect: false
  output_power: 20.0
  networks:
  - ssid: !secret 'wifi_ssid'
    password: !secret 'wifi_password'
    priority: 0.0
  use_address: dm01_sv1.local
mqtt:
  broker: !secret 'mqtt_broker'
  username: !secret 'mqtt_username'
  password: !secret 'mqtt_password'
  port: 1883
  discovery: true
  discovery_retain: true
  discovery_prefix: homeassistant
  topic_prefix: dm01_sv1
  keepalive: 15s
  reboot_timeout: 15min
  birth_message:
    topic: dm01_sv1/status
    payload: online
    qos: 0
    retain: true
  will_message:
    topic: dm01_sv1/status
    payload: offline
    qos: 0
    retain: true
  shutdown_message:
    topic: dm01_sv1/status
    payload: offline
    qos: 0
    retain: true
  log_topic:
    topic: dm01_sv1/debug
    qos: 0
    retain: true
text_sensor:
- platform: wifi_info
  ip_address:
    id: dm01_sv1_wifi_info_ip
    name: DM01_SV1 IP

```

**Comment by mtl010957** [comment]
Further analysis showed that the problem does not show up with all lambdas with embedded substitutions, only those where the substitution is part of an id reference to a sensor component. I've submitted a PR that fixes the issue.
