### ISSUE TITLE
Problem with zeroconf and mdsn

### ISSUE THREAD

**Issue by dedalusjinja** [esphome/issues#1901]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Raspbian on Pi4

**ESP (ESP32/ESP8266, Board/Sonoff):**

All devices

**ESPHome version (latest production, beta, dev branch)**

ESPHome version 1.16.2

**Description of problem:**
Since I switched to HomeAssistant Core on raspbian I have this problem with mdsn and Esphome, before on HassOs no kind of problem. Now if I launch the esphome config / dasboard command from the terminal, or if I compile a project, or if I open the log of any project, I get this error. And the devices I see them online healthily and for short seconds. On HA they work regularly.

**Logs (if applicable):**

```

INFO Reading configuration config/home.yaml...
INFO Starting log output from home.local using esphome API
WARNING Exception occurred:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/esphome/zeroconf.py", line 755, in send
    bytes_sent = s.sendto(packet, 0, (_MDNS_ADDR, _MDNS_PORT))
OSError: [Errno 126] Required key not available
INFO Connecting to home.local:6053 (192.168.XX.XX)
INFO Successfully connected to home.local
[20:58:45][I][app:105]: ESPHome version 1.16.2 compiled on Mar 11 2021, 17:42:24
[20:58:45][C][wifi:443]: WiFi:
[20:58:45][C][wifi:303]:   SSID: 'XXXXXXXXX'[redacted]
[20:58:45][C][wifi:304]:   IP Address: 192.168.X.X
[20:58:45][C][wifi:306]:   BSSID: xxxxxxxxxxxx[redacted]
[20:58:45][C][wifi:307]:   Hostname: 'home'
[20:58:45][C][wifi:311]:   Signal strength: -54 dB ▂▄▆█
[20:58:45][C][wifi:315]:   Channel: 11
[20:58:45][C][wifi:316]:   Subnet: 255.255.255.0
[20:58:45][C][wifi:317]:   Gateway: 192.168.X.X
[20:58:45][C][wifi:318]:   DNS1: 192.168.X.X
[20:58:45][C][wifi:319]:   DNS2: (IP unset)

```

**Additional information and things you've tried:**
Log compiling project
```
INFO Reading configuration config/home.yaml...
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d config/home
Processing home (board: d1_mini; framework: arduino; platform: espressif8266@2.6.2)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.20704.0 (2.7.4) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20800.0 (2.8.0) 
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Library Manager: Installing Update
Warning! Could not find the package with 'Update' requirements for your system 'linux_armv7l'
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <ESP8266WiFi> 1.0
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.7
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
Compiling .pioenvs/home/src/esphome/components/api/api_connection.cpp.o
Compiling .pioenvs/home/src/esphome/components/api/api_pb2.cpp.o
Compiling .pioenvs/home/src/esphome/components/api/api_pb2_service.cpp.o
Compiling .pioenvs/home/src/esphome/components/api/api_server.cpp.o
Compiling .pioenvs/home/src/esphome/components/api/list_entities.cpp.o
Compiling .pioenvs/home/src/esphome/components/api/proto.cpp.o
Compiling .pioenvs/home/src/esphome/components/api/subscribe_state.cpp.o
Compiling .pioenvs/home/src/esphome/components/api/user_services.cpp.o
Compiling .pioenvs/home/src/esphome/components/api/util.cpp.o
Compiling .pioenvs/home/src/esphome/components/binary_sensor/automation.cpp.o
Compiling .pioenvs/home/src/esphome/components/binary_sensor/binary_sensor.cpp.o
Compiling .pioenvs/home/src/esphome/components/binary_sensor/filter.cpp.o
Compiling .pioenvs/home/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/home/src/esphome/components/gpio/binary_sensor/gpio_binary_sensor.cpp.o
Compiling .pioenvs/home/src/esphome/components/gpio/switch/gpio_switch.cpp.o
Compiling .pioenvs/home/src/esphome/components/logger/logger.cpp.o
Compiling .pioenvs/home/src/esphome/components/ota/ota_component.cpp.o
Compiling .pioenvs/home/src/esphome/components/switch/automation.cpp.o
Compiling .pioenvs/home/src/esphome/components/switch/switch.cpp.o
Compiling .pioenvs/home/src/esphome/components/template/switch/template_switch.cpp.o
Compiling .pioenvs/home/src/esphome/components/web_server_base/web_server_base.cpp.o
Compiling .pioenvs/home/src/esphome/components/wifi/wifi_component.cpp.o
Compiling .pioenvs/home/src/esphome/components/wifi/wifi_component_esp32.cpp.o
Compiling .pioenvs/home/src/esphome/components/wifi/wifi_component_esp8266.cpp.o
Compiling .pioenvs/home/src/esphome/core/application.cpp.o
Compiling .pioenvs/home/src/esphome/core/component.cpp.o
Compiling .pioenvs/home/src/esphome/core/controller.cpp.o
Compiling .pioenvs/home/src/esphome/core/esphal.cpp.o
Compiling .pioenvs/home/src/esphome/core/helpers.cpp.o
Compiling .pioenvs/home/src/esphome/core/log.cpp.o
Compiling .pioenvs/home/src/esphome/core/preferences.cpp.o
Compiling .pioenvs/home/src/esphome/core/scheduler.cpp.o
Compiling .pioenvs/home/src/esphome/core/util.cpp.o
Compiling .pioenvs/home/src/main.cpp.o
Generating LD script .pioenvs/home/ld/local.eagle.app.v6.common.ld
Compiling .pioenvs/home/lib46a/ESP8266WiFi/BearSSLHelpers.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/CertStoreBearSSL.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/ESP8266WiFi.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/ESP8266WiFiAP.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/ESP8266WiFiGeneric.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/ESP8266WiFiGratuitous.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/ESP8266WiFiMulti.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/ESP8266WiFiSTA-WPS.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/ESP8266WiFiSTA.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/ESP8266WiFiScan.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/WiFiClient.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/WiFiClientSecureAxTLS.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/WiFiClientSecureBearSSL.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/WiFiServer.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/WiFiServerSecureAxTLS.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/WiFiServerSecureBearSSL.cpp.o
Compiling .pioenvs/home/lib46a/ESP8266WiFi/WiFiUdp.cpp.o
Compiling .pioenvs/home/libfd6/ESPAsyncTCP-esphome/AsyncPrinter.cpp.o
Compiling .pioenvs/home/libfd6/ESPAsyncTCP-esphome/ESPAsyncTCP.cpp.o
Compiling .pioenvs/home/libfd6/ESPAsyncTCP-esphome/ESPAsyncTCPbuffer.cpp.o
Archiving .pioenvs/home/lib46a/libESP8266WiFi.a
Indexing .pioenvs/home/lib46a/libESP8266WiFi.a
Compiling .pioenvs/home/libfd6/ESPAsyncTCP-esphome/SyncClient.cpp.o
Compiling .pioenvs/home/libfd6/ESPAsyncTCP-esphome/tcp_axtls.c.o
Compiling .pioenvs/home/lib624/ESP8266mDNS/ESP8266mDNS.cpp.o
Compiling .pioenvs/home/lib624/ESP8266mDNS/ESP8266mDNS_Legacy.cpp.o
Compiling .pioenvs/home/lib624/ESP8266mDNS/LEAmDNS.cpp.o
Archiving .pioenvs/home/libfd6/libESPAsyncTCP-esphome.a
Indexing .pioenvs/home/libfd6/libESPAsyncTCP-esphome.a
Compiling .pioenvs/home/lib624/ESP8266mDNS/LEAmDNS_Control.cpp.o
Compiling .pioenvs/home/lib624/ESP8266mDNS/LEAmDNS_Helpers.cpp.o
Compiling .pioenvs/home/lib624/ESP8266mDNS/LEAmDNS_Structs.cpp.o
Compiling .pioenvs/home/lib624/ESP8266mDNS/LEAmDNS_Transfer.cpp.o
Compiling .pioenvs/home/lib517/Hash/Hash.cpp.o
Compiling .pioenvs/home/libf2f/ESPAsyncWebServer-esphome/AsyncEventSource.cpp.o
Archiving .pioenvs/home/lib517/libHash.a
Indexing .pioenvs/home/lib517/libHash.a
Compiling .pioenvs/home/libf2f/ESPAsyncWebServer-esphome/AsyncWebSocket.cpp.o
Compiling .pioenvs/home/libf2f/ESPAsyncWebServer-esphome/SPIFFSEditor.cpp.o
Archiving .pioenvs/home/lib624/libESP8266mDNS.a
Indexing .pioenvs/home/lib624/libESP8266mDNS.a
Compiling .pioenvs/home/libf2f/ESPAsyncWebServer-esphome/WebAuthentication.cpp.o
Compiling .pioenvs/home/libf2f/ESPAsyncWebServer-esphome/WebHandlers.cpp.o
Compiling .pioenvs/home/libf2f/ESPAsyncWebServer-esphome/WebRequest.cpp.o
In file included from .piolibdeps/home/ESPAsyncWebServer-esphome/src/SPIFFSEditor.cpp:1:0:
.piolibdeps/home/ESPAsyncWebServer-esphome/src/SPIFFSEditor.h:16:101: warning: 'SPIFFS' is deprecated (declared at /home/pi/.platformio/packages/framework-arduinoespressif8266/cores/esp8266/FS.h:269): SPIFFS has been deprecated. Please consider moving to LittleFS or other filesystems. [-Wdeprecated-declarations]
     SPIFFSEditor(const String& username=String(), const String& password=String(), const fs::FS& fs=SPIFFS);
                                                                                                     ^
Compiling .pioenvs/home/libf2f/ESPAsyncWebServer-esphome/WebResponses.cpp.o
Compiling .pioenvs/home/libf2f/ESPAsyncWebServer-esphome/WebServer.cpp.o
Compiling .pioenvs/home/lib084/DNSServer/DNSServer.cpp.o
Archiving .pioenvs/home/lib084/libDNSServer.a
Indexing .pioenvs/home/lib084/libDNSServer.a
Archiving .pioenvs/home/libFrameworkArduinoVariant.a
Indexing .pioenvs/home/libFrameworkArduinoVariant.a
Compiling .pioenvs/home/FrameworkArduino/Crypto.cpp.o
Compiling .pioenvs/home/FrameworkArduino/Esp-frag.cpp.o
Compiling .pioenvs/home/FrameworkArduino/Esp-version.cpp.o
Archiving .pioenvs/home/libf2f/libESPAsyncWebServer-esphome.a
Indexing .pioenvs/home/libf2f/libESPAsyncWebServer-esphome.a
Compiling .pioenvs/home/FrameworkArduino/Esp.cpp.o
Compiling .pioenvs/home/FrameworkArduino/FS.cpp.o
Compiling .pioenvs/home/FrameworkArduino/FSnoop.cpp.o
Compiling .pioenvs/home/FrameworkArduino/FunctionalInterrupt.cpp.o
Compiling .pioenvs/home/FrameworkArduino/HardwareSerial.cpp.o
Compiling .pioenvs/home/FrameworkArduino/IPAddress.cpp.o
Compiling .pioenvs/home/FrameworkArduino/MD5Builder.cpp.o
Compiling .pioenvs/home/FrameworkArduino/Print.cpp.o
Compiling .pioenvs/home/FrameworkArduino/Schedule.cpp.o
Compiling .pioenvs/home/FrameworkArduino/StackThunk.cpp.o
Compiling .pioenvs/home/FrameworkArduino/Stream.cpp.o
Compiling .pioenvs/home/FrameworkArduino/StreamString.cpp.o
Compiling .pioenvs/home/FrameworkArduino/Tone.cpp.o
Compiling .pioenvs/home/FrameworkArduino/TypeConversion.cpp.o
Compiling .pioenvs/home/FrameworkArduino/Updater.cpp.o
Compiling .pioenvs/home/FrameworkArduino/WMath.cpp.o
Compiling .pioenvs/home/FrameworkArduino/WString.cpp.o
Compiling .pioenvs/home/FrameworkArduino/abi.cpp.o
Compiling .pioenvs/home/FrameworkArduino/base64.cpp.o
Compiling .pioenvs/home/FrameworkArduino/cbuf.cpp.o
Compiling .pioenvs/home/FrameworkArduino/cont.S.o
Compiling .pioenvs/home/FrameworkArduino/cont_util.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_app_entry_noextra4k.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_eboot_command.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_features.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_flash_quirks.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_flash_utils.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_i2s.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_main.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_noniso.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_phy.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_postmortem.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_si2c.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_sigma_delta.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_spi_utils.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_timer.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_waveform.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_wiring.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_wiring_analog.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_wiring_digital.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_wiring_pulse.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_wiring_pwm.cpp.o
Compiling .pioenvs/home/FrameworkArduino/core_esp8266_wiring_shift.cpp.o
Compiling .pioenvs/home/FrameworkArduino/crc32.cpp.o
Compiling .pioenvs/home/FrameworkArduino/debug.cpp.o
Compiling .pioenvs/home/FrameworkArduino/flash_hal.cpp.o
Compiling .pioenvs/home/FrameworkArduino/gdb_hooks.cpp.o
Compiling .pioenvs/home/FrameworkArduino/heap.cpp.o
Compiling .pioenvs/home/FrameworkArduino/libb64/cdecode.cpp.o
Compiling .pioenvs/home/FrameworkArduino/libb64/cencode.cpp.o
Compiling .pioenvs/home/FrameworkArduino/libc_replacements.cpp.o
Compiling .pioenvs/home/FrameworkArduino/sntp-lwip2.cpp.o
Compiling .pioenvs/home/FrameworkArduino/spiffs/spiffs_cache.cpp.o
Compiling .pioenvs/home/FrameworkArduino/spiffs/spiffs_check.cpp.o
Compiling .pioenvs/home/FrameworkArduino/spiffs/spiffs_gc.cpp.o
Compiling .pioenvs/home/FrameworkArduino/spiffs/spiffs_hydrogen.cpp.o
Compiling .pioenvs/home/FrameworkArduino/spiffs/spiffs_nucleus.cpp.o
Compiling .pioenvs/home/FrameworkArduino/spiffs_api.cpp.o
Compiling .pioenvs/home/FrameworkArduino/sqrt32.cpp.o
Compiling .pioenvs/home/FrameworkArduino/time.cpp.o
Compiling .pioenvs/home/FrameworkArduino/uart.cpp.o
Compiling .pioenvs/home/FrameworkArduino/umm_malloc/umm_info.c.o
Compiling .pioenvs/home/FrameworkArduino/umm_malloc/umm_integrity.c.o
Compiling .pioenvs/home/FrameworkArduino/umm_malloc/umm_local.c.o
Compiling .pioenvs/home/FrameworkArduino/umm_malloc/umm_malloc.cpp.o
Compiling .pioenvs/home/FrameworkArduino/umm_malloc/umm_poison.c.o
Archiving .pioenvs/home/libFrameworkArduino.a
Indexing .pioenvs/home/libFrameworkArduino.a
Linking .pioenvs/home/firmware.elf
Retrieving maximum program size .pioenvs/home/firmware.elf
Checking size .pioenvs/home/firmware.elf
RAM:   [====      ]  45.0% (used 36840 bytes from 81920 bytes)
Flash: [====      ]  38.5% (used 401608 bytes from 1044464 bytes)
Building .pioenvs/home/firmware.bin
Creating BIN file ".pioenvs/home/firmware.bin" using "/home/pi/.platformio/packages/framework-arduinoespressif8266/bootloaders/eboot/eboot.elf" and ".pioenvs/home/firmware.elf"
========================= [SUCCESS] Took 72.34 seconds =========================

INFO Successfully compiled program.
INFO Resolving IP address of home.local
WARNING Exception occurred:
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.8/site-packages/esphome/zeroconf.py", line 755, in send
    bytes_sent = s.sendto(packet, 0, (_MDNS_ADDR, _MDNS_PORT))
OSError: [Errno 126] Required key not available
INFO  -> 192.168.XX.XX
INFO Uploading config/home/.pioenvs/home/firmware.bin (405760 bytes)
Uploading: [============================================================] 100% Done...


```

**Comment by mguaylam** [comment]
I have the same problem as you. I’m unsure what cause it. Under Docker / debian, it seem’s to work but with Podman / Fedora, I get the same message : 
`WARNING Error with socket 18 (('10.60.0.1', 5353))): [Errno 126] Required key not available
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 1056, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 126] Required key not available
WARNING Can't connect to ESPHome API for lave_vaiselle.local: Error connecting to ('10.0.20.20', 6053): [Errno 111] Connect call failed ('10.0.20.20', 6053)`
