### ISSUE TITLE
disable mqtt LWT failed

### ISSUE THREAD

**Issue by hotsnow** [esphome/issues#197]
failed to disable MQTT LWT with home assistant. since home assistant not allow empty availability_topic

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

esphome v1.12.2, home assistant 0.90

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32/ESP8266

**Affected component:**

MQTT

**Description of problem:**
unable to disable MQTT LWT feature as document said: use empty topic. when I use empty topic or difference topic for birth and will. homeassistnt will log an error with not allow availability_topic to empty

**Problem-relevant YAML-configuration entries:**
```yaml
mqtt:
  birth_message:
  will_message:

or as this:
mqtt:
  birth_message:
    topic: $devicename/birth
    payload: online
  will_message:
    topic: $devicename/will
    payload: offline
```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

home assistant error log:
2019-04-03 22:06:17 ERROR (MainThread) [homeassistant.components.mqtt.sensor] Exception in async_discover_sensor when dispatching 'mqtt_discovery_new_sensor_mqtt': ({'unit_of_measurement': 'dB', 'expire_after': 150, 'icon': 'mdi:signal', 'name': 'Amy Key RSSI', 'state_topic': 'esp32s/sensor/my_key_rssi/state', 'availability_topic': '', 'unique_id': 'ble-00300533F17A16FA-rssi', 'device': {'identifiers': '30aea33b23ac', 'name': 'esp32s', 'sw_version': 'esphome v1.12.2 Apr  3 2019, 08:59:25', 'model': 'NodeMCU-32S', 'manufacturer': 'espressif'}, 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/data/app/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/config_validation.py", line 643, in __call__
    return super().__call__(data)
  File "/data/app/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 267, in __call__
    return self._compiled([], data)
  File "/data/app/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/data/app/homeassistant/lib/python3.6/site-packages/voluptuous/schema_builder.py", line 427, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: MQTT topic name/filter must not be empty. for dictionary value @ data['availability_topic']

**Comment by OttoWinter** [comment]
Fixed
