### ISSUE TITLE
Teminated Process in Dashboard

### ISSUE THREAD

**Issue by Trance-Paradox** [esphome/issues#2008]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**
Windows 10  : pip install esphome

**ESP (ESP32/ESP8266, Board/Sonoff):**
ESP8266

**ESPHome version (latest production, beta, dev branch)**
esphome 1.16.2

**Affected component:**
ESPHome Dashboard

**Description of problem:**
When I launch dashboard with ```esphome /config dashboard``` the terminal puts out error which i have pasted in log. Also apart from creating new nodes I cannot do anything. Neither compiling nor uploading.

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: led_builtin
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "************"
  password: "**********"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Led Builtin Fallback Hotspot"
    password: "j0nkzEVqaO8Y"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:


```

**Logs (if applicable):**

```
INFO 101 GET /ace (::1) 0.00ms
INFO Running command 'esphome --dashboard -q config/ vscode --ace'
ERROR Uncaught exception GET /ace (::1)
HTTPServerRequest(protocol='http', host='localhost:6052', method='GET', uri='/ace', version='HTTP/1.1', remote_ip='::1')
Traceback (most recent call last):
  File "c:\users\surya\appdata\local\programs\python\python39\lib\site-packages\tornado\websocket.py", line 647, in _run_callback
    result = callback(*args, **kwargs)
  File "c:\users\surya\appdata\local\programs\python\python39\lib\site-packages\esphome\dashboard\dashboard.py", line 128, in decorator
    return func(self, *args, **kwargs)
  File "c:\users\surya\appdata\local\programs\python\python39\lib\site-packages\esphome\dashboard\dashboard.py", line 200, in on_message
    handlers[type_](self, json_message)
  File "c:\users\surya\appdata\local\programs\python\python39\lib\site-packages\esphome\dashboard\dashboard.py", line 209, in handle_spawn
    self._proc = tornado.process.Subprocess(command,
  File "c:\users\surya\appdata\local\programs\python\python39\lib\site-packages\tornado\process.py", line 226, in __init__
    self.stdin = PipeIOStream(in_w)
  File "c:\users\surya\appdata\local\programs\python\python39\lib\site-packages\tornado\iostream.py", line 1625, in __init__
    os.set_blocking(fd, False)
AttributeError: module 'os' has no attribute 'set_blocking'

```

**Additional information and things you've tried:**

**Comment by 467815891a** [comment]
same here

**Comment by chepo92** [comment]
The dashboard upload is not fully supported in Windows, but the CLI is, https://esphome.io/guides/getting_started_command_line.html
I use the dashboard editor and then upload with command line, or even use VSCode and do both
