### ISSUE TITLE
PID Climate causes unrefrenced variable compile error

### ISSUE THREAD

**Issue by haukurhafsteins** [esphome/issues#2098]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESPHome integration in Home Assistant and ESPHome in the command line in Windows 10.
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 Wrover
**ESPHome version (latest production, beta, dev branch)**

1.18.0
**Affected component:**

https://esphome.io/components/climate/pid.html

**Description of problem:**
Adding climate with platfrom pid causes the following error in ESPHome integration in homeassistant: 
UnboundLocalError: local variable 'orig_err' referenced before assignment

Tested in the command line in Windows with similar results:
 esphome.exe tst.yaml compile
INFO Reading configuration tst.yaml...
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\hauku\AppData\Local\Programs\Python\Python39\Scripts\esphome.exe\__main__.py", line 7, in <module>
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\esphome\__main__.py", line 557, in main
    return run_esphome(sys.argv)
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\esphome\__main__.py", line 535, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\esphome\config.py", line 834, in read_config
    res = load_config(command_line_substitutions)
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\esphome\config.py", line 694, in load_config
    return _load_config(command_line_substitutions)
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\esphome\config.py", line 682, in _load_config
    result = validate_config(config, command_line_substitutions)
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\esphome\config.py", line 589, in validate_config
    validated = comp.config_schema(input_conf)
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\voluptuous\validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\voluptuous\validators.py", line 336, in _exec
    v = func(v)
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\voluptuous\schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\voluptuous\schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\esphome\voluptuous_schema.py", line 30, in __call__
    res = super().__call__(data)
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\voluptuous\schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\voluptuous\schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\esphome\voluptuous_schema.py", line 131, in validate_mapping
    cval = cvalue(key_path, value)
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\voluptuous\schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "c:\users\hauku\appdata\local\programs\python\python39\lib\site-packages\esphome\config_validation.py", line 646, in temperature
    raise orig_err  # noqa
UnboundLocalError: local variable 'orig_err' referenced before assignment

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: climatetest
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: "XYZ"
  password: "12345678"

  ap:
    ssid: "Hottubcontroller"
    password: "xbYrFEfkApV8"

captive_portal:
api:
ota:

dallas:
  - id: dallas_temperature
    pin: GPIO5
    update_interval: 1s
    
output:
  - platform: esp32_dac
    pin: GPIO25
    id: htc_dac_motor_hot
  - platform: esp32_dac
    pin: GPIO26
    id: htc_dac_motor_cold
    
sensor:
  - platform: dallas
    id: htc_current_temp
    address: 0xA80008039D1DC610
    name: "Current Temp"

climate:
  - platform: pid
    id: pid_water_temp
    name: "PID Hottub Controller"
    heat_output: htc_dac_motor_hot
    cool_output: htc_dac_motor_cold
    sensor: htc_current_temp
    default_target_temperature: 27.0;
    control_parameters:
      kp: 0.49460
      ki: 0.00487
      kd: 12.56301

```

**Logs (if applicable):**

```
-----------------------------------------------------------
 Add-on: ESPHome
 ESPHome Hass.io add-on for intelligently managing all your ESP8266/ESP32 devices.
-----------------------------------------------------------
 Add-on version: 1.18.0
 You are running the latest version of this add-on.
 System: Debian GNU/Linux 10 (buster)  (amd64 / qemux86-64)
 Home Assistant Core: 2021.6.2
 Home Assistant Supervisor: 2021.05.4
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-nginx.sh: executing... 
[cont-init.d] 20-nginx.sh: exited 0.
[cont-init.d] 30-esphome.sh: executing... 
[cont-init.d] 30-esphome.sh: exited 0.
[cont-init.d] 40-migrate.sh: executing... 
[cont-init.d] 40-migrate.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[19:19:20] INFO: Starting ESPHome dashboard...
[19:19:20] INFO: Waiting for dashboard to come up...
INFO Starting dashboard web server on unix socket /var/run/esphome.sock and configuration dir /config/esphome...
[19:19:22] INFO: Starting NGINX...
INFO 304 GET / (0.0.0.0) 50.27ms
INFO 101 GET /ace (0.0.0.0) 1.35ms
INFO Running command 'esphome --dashboard -q /config/esphome vscode --ace'
INFO 304 GET /edit?configuration=hottupcontroller.yaml (0.0.0.0) 3.00ms
INFO 304 GET / (0.0.0.0) 9.00ms
INFO 101 GET /ace (0.0.0.0) 1.65ms
INFO Running command 'esphome --dashboard -q /config/esphome vscode --ace'
INFO 304 GET /edit?configuration=hottupcontroller.yaml (0.0.0.0) 2.37ms
INFO 302 POST /wizard.html (0.0.0.0) 12.53ms
INFO 200 GET /?begin=True (0.0.0.0) 6.17ms
INFO 101 GET /ace (0.0.0.0) 1.42ms
INFO Running command 'esphome --dashboard -q /config/esphome vscode --ace'
INFO 200 GET /edit?configuration=tst.yaml (0.0.0.0) 2.90ms
INFO 200 POST /edit?configuration=tst.yaml (0.0.0.0) 1.83ms
INFO 200 POST /edit?configuration=tst.yaml (0.0.0.0) 2.45ms
INFO 200 POST /edit?configuration=tst.yaml (0.0.0.0) 3.17ms
INFO 200 GET / (0.0.0.0) 10.34ms
INFO 101 GET /ace (0.0.0.0) 1.53ms
INFO Running command 'esphome --dashboard -q /config/esphome vscode --ace'
INFO 200 GET /edit?configuration=tst.yaml (0.0.0.0) 2.34ms

```

**Additional information and things you've tried:**
Did found in this issue(https://github.com/esphome/issues/issues/602) that mentioned adding LC_ALL=C to export. Did try that in the command line in Windows without success.

**Comment by haukurhafsteins** [comment]
The error was the ";" after the default_target_temperature. Closing issue.
