### ISSUE TITLE
Unable to open device logs in 1.19.4 (TypeError: t.filter is not a function)

### ISSUE THREAD

**Issue by DAVe3283** [esphome/issues#2211]
I hope this is not a duplicate, but searching for "logs" or any variation results in __every issue__ matching. Sorry in advance.
This broke somewhere after 1.19.1.

I have the add-on set to use SSL. I also have the VS Code add-on installed, which might be relevant given the mention in the logs below. I was not able to get the VSCode integration working, probably due to my DNS setup (I do not use Home Assistant for DNS, I use Windows Server 2012R2 with a real domain name for everything, so *.local will not resolve anything).

**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Hass.io (Home Assistant OS 6.0, supervisor-2021.06.6, core-2021.6.4 running in a VM)
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266, probably all though
**ESPHome version (latest production, beta, dev branch)**

1.19.4 (latest as of now)
**Affected component:**

The web UI itself ([here I guess](https://esphome.io/guides/getting_started_hassio.html))

**Description of problem:**

**Problem-relevant YAML-configuration entries:**
All devices have this issue, appears front-end related.

**Logs (if applicable):**

Browser console logs. The first 3 entries are just loading the page, the last entry is when I click on LOGS:

![image](https://user-images.githubusercontent.com/6894502/124042809-ea255800-d9c6-11eb-9e2e-1b834f361d77.png)
```
Uncaught (in promise) TypeError: t.filter is not a function
    at c.2472ed8e.js:1
```

ESPHome log:
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Add-on: ESPHome
 ESPHome add-on for intelligently managing all your ESP8266/ESP32 devices
-----------------------------------------------------------
 Add-on version: 1.19.4
 You are running the latest version of this add-on.
 System: Home Assistant OS 6.0  (amd64 / qemux86-64)
 Home Assistant Core: 2021.6.4
 Home Assistant Supervisor: 2021.06.6
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-nginx.sh: executing... 
[cont-init.d] 20-nginx.sh: exited 0.
[cont-init.d] 30-esphome.sh: executing... 
[cont-init.d] 30-esphome.sh: exited 0.
[cont-init.d] 40-migrate.sh: executing... 
[cont-init.d] 40-migrate.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[17:15:02] INFO: Waiting for dashboard to come up...
[services.d] done.
[17:15:02] INFO: Starting ESPHome dashboard...
INFO Starting dashboard web server on unix socket /var/run/esphome.sock and configuration dir /config/esphome...
[17:15:03] INFO: Starting NGINX...
INFO 200 GET / (0.0.0.0) 7.86ms
INFO 101 GET /ace (0.0.0.0) 0.47ms
INFO Running command 'esphome --dashboard -q vscode /config/esphome --ace'
```

**Additional information and things you've tried:**

ESPHome add-on configuration:
```yml
status_use_ping: true
ssl: true
certfile: real.FQDN.net-chain-2020.crt
keyfile: real.FQDN.net-key-2020.pem
relative_url: ''
leave_front_door_open: false
```
I have `status_use_ping: true` because mDNS does not work to/from the VLAN I keep my IOT devices in. But ping does, and this setup has been flawless until 1.19.4.

Reverting to a snapshot of 1.19.1 got things working again. I tried to restore my snapshot of 1.19.2 but that failed. Supervisor logs of restoring then trying (and failing) to start it:
```
21-06-30 17:05:15 INFO (MainThread) [supervisor.addons.addon] Restore/Update of image for addon a0d7b954_esphome
21-06-30 17:05:15 INFO (SyncWorker_4) [supervisor.docker.interface] Updating image esphome/esphome-hassio-amd64:1.19.4 to esphome/esphome-hassio-amd64:1.19.2
21-06-30 17:05:15 INFO (SyncWorker_4) [supervisor.docker.interface] Downloading docker image esphome/esphome-hassio-amd64 with tag 1.19.2.
21-06-30 17:05:18 INFO (SyncWorker_4) [supervisor.docker.interface] Stopping addon_a0d7b954_esphome application
21-06-30 17:05:19 INFO (SyncWorker_4) [supervisor.docker.interface] Cleaning addon_a0d7b954_esphome application
21-06-30 17:05:19 INFO (MainThread) [supervisor.addons.addon] Restoring data for addon a0d7b954_esphome
21-06-30 17:05:19 ERROR (MainThread) [supervisor.jobs] Unhandled exception: [Errno 2] No such file or directory: '/data/tmp/tmp5vd_l_7c/data'
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 105, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/addons/__init__.py", line 358, in restore
    await addon.restore(tar_file)
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 853, in restore
    await self.sys_run_in_executor(_restore_data)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/supervisor/supervisor/addons/addon.py", line 847, in _restore_data
    shutil.copytree(Path(temp, "data"), self.path_data, symlinks=True)
  File "/usr/local/lib/python3.9/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/data/tmp/tmp5vd_l_7c/data'
21-06-30 17:05:19 WARNING (MainThread) [supervisor.snapshots.snapshot] Can't restore Add-on a0d7b954_esphome: 
21-06-30 17:05:19 INFO (MainThread) [supervisor.snapshots] Partial-Restore 1a57ca72 done
```

**Comment by DAVe3283** [comment]
So this is really browser/app specific...

Phone:
❌ ESPHome 2021.6.2-full (Android 10 app)
✔️ Firefox 89.1.1 (Android 10)
✔️ Chrome 91.0.4472.120 (Android 10)

Desktop:
❌ Chrome 91.0.4472.124 (Windows 10 Enterprise 20H2)
✔️ Edge 91.0.864.41 (Windows 10 Enterprise 20H2)
✔️ Firefox 89.0.2 (Windows 7 Enterprise)
All 3 browsers are running the same plugins (uBlock Origin and LastPass). Disabling uBlock Origin has no effect.
