### ISSUE TITLE
OTA Log crash

### ISSUE THREAD

**Issue by michelebergo** [esphome/issues#2251]
### The problem

Log crashes and it is not recovering. Log with previous version was working perfectly. components not updated to 1.20.0 are working fine.

### What is version of ESPHome has the issue?

1.20.0

### What type of installation are you using?

Home Assistant Add-on

### What platform are you using?

ESP8266

### Board

custom component

### Component causing the issue

custom component

### Anything in the logs that might be useful for us?

```txt
[05:29:20][C][uart_esp8266:088]:   Using hardware serial interface.
[05:29:20][C][logger:189]: Logger:
[05:29:20][C][logger:190]:   Level: DEBUG
[05:29:20][C][logger:191]:   Log Baud Rate: 0
[05:29:20][C][logger:192]:   Hardware UART: UART0
[05:29:20][C][comfoair:222]: ComfoAir:
[05:29:20][C][comfoair:223]:   Update Interval: 0.6s
[05:29:20][C][comfoair:225]:   Bootloader WHR 200    v3.80 b32
[05:29:20][C][comfoair:227]:   Firmware WHR 200    v3.80 b32
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/opt/esphome/esphome/api/client.py", line 408, in run
    self._run_once()
  File "/opt/esphome/esphome/api/client.py", line 398, in _run_once
    msg.ParseFromString(raw_msg)
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/message.py", line 199, in ParseFromString
    return self.MergeFromString(serialized)
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/internal/python_message.py", line 1139, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/internal/python_message.py", line 1206, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/internal/decoder.py", line 619, in DecodeField
    field_dict[key] = _ConvertToUnicode(buffer[pos:new_pos])
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/internal/decoder.py", line 572, in _ConvertToUnicode
    value = local_unicode(byte_str, 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 44: 'utf-8' codec can't decode byte 0xff in position 44: invalid start byte in field: SubscribeLogsResponse.message

WARNING Disconnected from API: Timeout while waiting for message response!
INFO Connecting to comfoair.local:6053 (192.168.1.43)
WARNING Couldn't connect to API (Timeout while waiting for message response!). Trying to reconnect in 1 seconds
INFO Connecting to comfoair.local:6053 (192.168.1.43)
WARNING Couldn't connect to API (Timeout while waiting for message response!). Trying to reconnect in 1 seconds
INFO Connecting to comfoair.local:6053 (192.168.1.43)
```

**Comment by glmnet** [comment]
The problem is you're trying to send to the logger a non Utf 8 string

You must encode utf your messages
