### ISSUE TITLE
Web Server js_include and css_include not working

### ISSUE THREAD

**Issue by bkaufx** [esphome/issues#2310]
### The problem

Compile error when trying to include local js/css files in web_server component.  In editor, warning is shown when file name is wrong, but warning goes away with correct file name so I know file is in the right place and the name matches entry.  However, I still get FileNotFoundError on compile.  It also used to work before and I haven't changed the yaml file or moved any files.

### Which version of ESPHome has the issue?

1.20.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8

### What platform are you using?

ESP8266

### Component causing the issue

web_server

### Example YAML snippet

```yaml
web_server:
  js_include: webserver-v1.min.js
  css_include: webserver-v1.min.css
```

### Anything in the logs that might be useful for us?

```txt
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/opt/esphome/esphome/__main__.py", line 750, in main
    return run_esphome(sys.argv)
  File "/opt/esphome/esphome/__main__.py", line 737, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/opt/esphome/esphome/__main__.py", line 292, in command_compile
    exit_code = write_cpp(config)
  File "/opt/esphome/esphome/__main__.py", line 144, in write_cpp
    generate_cpp_contents(config)
  File "/opt/esphome/esphome/__main__.py", line 156, in generate_cpp_contents
    CORE.flush_tasks()
  File "/opt/esphome/esphome/core/__init__.py", line 596, in flush_tasks
    self.event_loop.flush_tasks()
  File "/opt/esphome/esphome/coroutine.py", line 245, in flush_tasks
    next(task.iterator)
  File "/opt/esphome/esphome/__main__.py", line 136, in wrapped
    await coro(conf)
  File "/opt/esphome/esphome/components/web_server/__init__.py", line 68, in to_code
    with open(config[CONF_JS_INCLUDE], "r") as myfile:
FileNotFoundError: [Errno 2] No such file or directory: 'webserver-v1.min.js'
```

### Additional information

webserver-v1.min.css and webserver-v1.min.js are in the same folder as the yaml config file.

**Comment by bkaufx** [comment]
These images show error in editor going away when file is properly named.  I still get the above error.

Name wrong:
![image](https://user-images.githubusercontent.com/31808830/128948052-e8146cc9-315e-41d9-a24f-ace46ea5535f.png)

Name right:
![image](https://user-images.githubusercontent.com/31808830/128948153-29d8d56b-7247-477b-84ef-6597f3570f7a.png)
