### ISSUE TITLE
Russian font

### ISSUE THREAD

**Issue by viktor6** [esphome/issues#2318]
### The problem

Russian font does not work 

### Which version of ESPHome has the issue?

v1.20.4

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.8.6

### What platform are you using?

ESP8266

### Board

wemos d1 mini

### Component causing the issue

max7219digit

### Example YAML snippet

```yaml
globals:
  - id: display_page
    type: int
    restore_value: no
    initial_value: '1'
 
spi:
 clk_pin: D5                                  # это подключать к входу CLK на max7219
 mosi_pin: D7                              # это подключать к входу DIN на max7219

display:
 - platform: max7219digit
   cs_pin: D6                               # это подключать к входу CS на max7219
   num_chips: 8                        # количество матриц
   intensity: 8                            # яркость матрицы от 0 до 15
   update_interval: 5s
   scroll_speed: 200ms
   id: max7219d
   lambda: |-
          it.intensity(atoi(id(matrixbri).state.c_str()));
          if (id(display_page) == 1) {
            it.printf(0, 0, id(digit_font), "%s", id(pir_sensor).state ? "ON" : "OFF");
            }  else {
              if (id(display_page) == 2) {
              it.strftime(0, 0, id(digit_font), "%H:%M", id(hass_time).now()); 
              } else {
                if (id(display_page) == 3) {
                it.printf(0, 0, id(digit_font), "%.1f°C", id(temp1).state); 
                } else {
                   if (id(display_page) == 4) {
                   it.printf(0, 0, id(digit_font), "%s%%", id(humi1).state.c_str());
                   } else {
                   if (id(display_page) == 5) { 
                     it.printf(0, 0, id(digit_font), "%s", id(matrix_text).state.c_str()); 
                     id(display_page) = 0;
                     }
                   
                   } } } };
          id(display_page) ++;
  


#  it.intensity(atoi(id(matrixbri).state.c_str()));
#  it.printf(0, 0, id(digit_font), "%s", id(temp1).state.c_str());.
# it.printdigitf("%s", id(temp1).state.c_str());.
#  it.scroll_left();
#  it.printf(0, 0, id(digit_font), TextAlign::TOP_LEFT, "%s", id(matrix_text).state.c_str());      
#  it.print(0, 0, id(digit_font), "%.1f°C", id(temp1).state);
#  it.strftime(0, 0, id(digit_font), "%H:%M", id(hass_time).now());   
#  it.strftimedigit("%H:%M", id(hass_time).now());
      
font:
  - file: "pixelmix.ttf"
    id: digit_font
    size: 8
  - file: "Pixel-UniCode.ttf"
    id: digit_font_unic
    size: 16

    
time:                                                 #компонент для получения времени
  - platform: homeassistant
    id: hass_time
    
text_sensor:                                    #компонент текстовых сенсоров
  - platform: homeassistant
    name: "Matrix Text"
    id: matrix_text
    entity_id: input_text.matrix_text
    
  - platform: homeassistant
    name: "Brightness 7219"
    id: matrixbri
    entity_id: input_number.matrixbri
    
  - platform: homeassistant
    name: "Kitchen Humidity"
    id: humi1
    entity_id: sensor.balkon_temperature
    
sensor:                                          #компонент числовых сенсоров
  - platform: homeassistant
    name: "Kitchen Temp"
    id: temp1
    entity_id: sensor.balkon_temperature 

binary_sensor:                            #компонент бинарных  сенсоров
  - platform: homeassistant
    id: pir_sensor
    entity_id: sensor.spalnya_temperature
    internal: true
```

### Anything in the logs that might be useful for us?

```txt
[W][display:173]: Encountered character without representation in font: '�'
[W][display:173]: Encountered character without representation in font: '�'
[W][display:173]: Encountered character without representation in font: '�'
[W][display:173]: Encountered character without representation in font: '�'
[W][display:173]: Encountered character without representation in font: '�'
[W][display:173]: Encountered character without representation in font: '�'
```

### Additional information
```txt
INFO Reading configuration /config/esphome/veneer_display.yaml...
INFO Detected timezone 'EET' with UTC offset 2 and daylight saving time from 27 March 03:00:00 to 30 October 04:00:00
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/veneer_display
Processing veneer_display (board: d1_mini; framework: arduino; platform: platformio/espressif8266@2.6.2)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.20704.0 (2.7.4) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20800.0 (2.8.0) 
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Library Manager: Installing Update
Library Manager: Already installed, built-in library
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.7
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <AsyncMqttClient-esphome> 0.8.4
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |   |-- <ESP8266WiFi> 1.0
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
|-- <SPI> 1.0
Compiling /data/veneer_display/.pioenvs/veneer_display/src/main.cpp.o
src/main.cpp:250:3: warning: multi-line comment [-Wcomment]
   //     %s\", id(matrix_text).state.c_str()); \n           id(display_page) = 0;\n     \
   ^
Linking /data/veneer_display/.pioenvs/veneer_display/firmware.elf
Retrieving maximum program size /data/veneer_display/.pioenvs/veneer_display/firmware.elf
Checking size /data/veneer_display/.pioenvs/veneer_display/firmware.elf
Building /data/veneer_display/.pioenvs/veneer_display/firmware.bin
RAM:   [=====     ]  53.9% (used 44128 bytes from 81920 bytes)
Flash: [=====     ]  45.6% (used 476664 bytes from 1044464 bytes)
Creating BIN file "/data/veneer_display/.pioenvs/veneer_display/firmware.bin" using "/root/.platformio/packages/framework-arduinoespressif8266/bootloaders/eboot/eboot.elf" and "/data/veneer_display/.pioenvs/veneer_display/firmware.elf"
========================= [SUCCESS] Took 21.12 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of veneer_display.local
INFO  -> 192.168.0.112
INFO Uploading /data/veneer_display/.pioenvs/veneer_display/firmware.bin (480816 bytes)
Uploading: [============================================================] 100% Done...

INFO Waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from veneer_display.local using esphome API
INFO Connecting to veneer_display.local:6053 (192.168.0.112)
INFO Successfully connected to veneer_display.local
[18:49:30][I][app:105]: ESPHome version 1.20.4 compiled on Aug 13 2021, 18:48:53
[18:49:30][C][wifi:499]: WiFi:
[18:49:30][C][wifi:359]:   SSID: [redacted]
[18:49:30][C][wifi:360]:   IP Address: 192.168.0.112
[18:49:30][C][wifi:362]:   BSSID: [redacted]
[18:49:30][C][wifi:363]:   Hostname: 'veneer_display'
[18:49:30][C][wifi:367]:   Signal strength: -68 dB ▂▄▆█
[18:49:30][C][wifi:371]:   Channel: 8
[18:49:30][C][wifi:372]:   Subnet: 255.255.255.0
[18:49:30][C][wifi:373]:   Gateway: 192.168.0.1
[18:49:30][C][wifi:374]:   DNS1: 192.168.0.1
[18:49:30][C][wifi:375]:   DNS2: (IP unset)
[18:49:30][C][spi:081]: SPI bus:
[18:49:30][C][spi:082]:   CLK Pin: GPIO14 (Mode: OUTPUT)
[18:49:30][C][spi:084]:   MOSI Pin: GPIO13 (Mode: OUTPUT)
[18:49:30][C][spi:085]:   Using HW SPI: YES
[18:49:31][C][logger:189]: Logger:
[18:49:31][C][logger:190]:   Level: DEBUG
[18:49:31][C][logger:191]:   Log Baud Rate: 115200
[18:49:31][C][logger:192]:   Hardware UART: UART0
[18:49:31][C][homeassistant.time:010]: Home Assistant Time:
[18:49:31][C][homeassistant.time:011]:   Timezone: 'EET-2EEST-3,M3.4.0/3,M10.5.0/4'
[18:49:31][C][max7219DIGIT:046]: MAX7219DIGIT:
[18:49:31][C][max7219DIGIT:047]:   Number of Chips: 8
[18:49:31][C][max7219DIGIT:048]:   Intensity: 0
[18:49:31][C][max7219DIGIT:049]:   Scroll Mode: 0
[18:49:31][C][max7219DIGIT:050]:   Scroll Speed: 200
[18:49:31][C][max7219DIGIT:051]:   Scroll Dwell: 1000
[18:49:31][C][max7219DIGIT:052]:   Scroll Delay: 1000
[18:49:31][C][max7219DIGIT:053]:   CS Pin: GPIO12 (Mode: OUTPUT)
[18:49:31][C][max7219DIGIT:054]:   Update Interval: 5.0s
[18:49:31][C][captive_portal:148]: Captive Portal:
[18:49:31][C][web_server:142]: Web Server:
[18:49:31][C][web_server:143]:   Address: veneer_display.local:80
[18:49:31][C][ota:029]: Over-The-Air Updates:
[18:49:31][C][ota:030]:   Address: veneer_display.local:8266
[18:49:31][C][ota:032]:   Using Password.
[18:49:31][C][api:095]: API Server:
[18:49:31][C][api:096]:   Address: veneer_display.local:6053
[18:49:31][C][mqtt:061]: MQTT:
[18:49:31][C][mqtt:063]:   Server Address: 192.168.0.201:1883 (192.168.0.201)
[18:49:31][C][mqtt:064]:   Username: [redacted]
[18:49:31][C][mqtt:065]:   Client ID: [redacted]
[18:49:31][C][mqtt:067]:   Discovery prefix: 'homeassistant'
[18:49:31][C][mqtt:068]:   Discovery retain: YES
[18:49:31][C][mqtt:070]:   Topic Prefix: 'veneer_display'
[18:49:31][C][mqtt:072]:   Log Topic: 'veneer_display/debug'
[18:49:31][C][mqtt:075]:   Availability: 'veneer_display/status'
[18:49:31][C][homeassistant.binary_sensor:038]: Homeassistant Binary Sensor 'pir_sensor'
[18:49:31][C][homeassistant.binary_sensor:039]:   Entity ID: 'sensor.spalnya_temperature'
[18:49:31][C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'Matrix Text'
[18:49:31][C][homeassistant.text_sensor:024]:   Entity ID: 'input_text.matrix_text'
[18:49:31][C][mqtt.text_sensor:025]: MQTT Text Sensor 'Matrix Text':
[18:49:31][C][mqtt.text_sensor:026]:   State Topic: 'veneer_display/sensor/matrix_text/state'
[18:49:31][C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'Brightness 7219'
[18:49:31][C][homeassistant.text_sensor:024]:   Entity ID: 'input_number.matrixbri'
[18:49:31][C][mqtt.text_sensor:025]: MQTT Text Sensor 'Brightness 7219':
[18:49:31][C][mqtt.text_sensor:026]:   State Topic: 'veneer_display/sensor/brightness_7219/state'
[18:49:31][C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'Kitchen Humidity'
[18:49:31][C][homeassistant.text_sensor:024]:   Entity ID: 'sensor.balkon_temperature'
[18:49:31][C][mqtt.text_sensor:025]: MQTT Text Sensor 'Kitchen Humidity':
[18:49:31][C][mqtt.text_sensor:026]:   State Topic: 'veneer_display/sensor/kitchen_humidity/state'
[18:49:31][C][homeassistant.sensor:030]: Homeassistant Sensor 'Kitchen Temp'
[18:49:31][C][homeassistant.sensor:030]:   State Class: ''
[18:49:31][C][homeassistant.sensor:030]:   Unit of Measurement: ''
[18:49:31][C][homeassistant.sensor:030]:   Accuracy Decimals: 1
[18:49:31][C][homeassistant.sensor:031]:   Entity ID: 'sensor.balkon_temperature'
[18:49:31][C][mqtt.sensor:024]: MQTT Sensor 'Kitchen Temp':
[18:49:31][C][mqtt.sensor:028]:   State Topic: 'veneer_display/sensor/kitchen_temp/state'
[18:49:31][C][mqtt.binary_sensor:018]: MQTT Binary Sensor 'pir_sensor':
[18:49:31][C][mqtt.binary_sensor:019]:   State Topic: 'veneer_display/binary_sensor/pir_sensor/state'
[18:49:31][D][api.connection:670]: Client 'Home Assistant 2021.8.6 (192.168.0.201)' connected successfully!
[18:49:31][D][time:040]: Synchronized time: Fri Aug 13 18:49:31 2021
[18:49:32][W][homeassistant.binary_sensor:017]: Can't convert 'unknown' to binary state!
[18:49:32][D][homeassistant.text_sensor:017]: 'input_text.matrix_text': Got state 'про'
[18:49:32][D][text_sensor:015]: 'Matrix Text': Sending state 'про'
[18:49:32][D][homeassistant.text_sensor:017]: 'input_number.matrixbri': Got state '15.0'
[18:49:32][D][text_sensor:015]: 'Brightness 7219': Sending state '15.0'
[18:49:32][D][homeassistant.text_sensor:017]: 'sensor.balkon_temperature': Got state '30.6'
[18:49:32][D][text_sensor:015]: 'Kitchen Humidity': Sending state '30.6'
[18:49:32][D][homeassistant.sensor:024]: 'sensor.balkon_temperature': Got state 30.60
[18:49:32][D][sensor:127]: 'Kitchen Temp': Sending state 30.60000  with 1 decimals of accuracy
[18:49:32][D][homeassistant.text_sensor:017]: 'sensor.balkon_temperature': Got state '30.6'
[18:49:32][D][text_sensor:015]: 'Kitchen Humidity': Sending state '30.6'
[18:49:32][D][homeassistant.sensor:024]: 'sensor.balkon_temperature': Got state 30.60
[18:49:32][D][sensor:127]: 'Kitchen Temp': Sending state 30.60000  with 1 decimals of accuracy
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/opt/esphome/esphome/api/client.py", line 408, in run
    self._run_once()
  File "/opt/esphome/esphome/api/client.py", line 398, in _run_once
    msg.ParseFromString(raw_msg)
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/message.py", line 199, in ParseFromString
    return self.MergeFromString(serialized)
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/internal/python_message.py", line 1139, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/internal/python_message.py", line 1206, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/internal/decoder.py", line 619, in DecodeField
    field_dict[key] = _ConvertToUnicode(buffer[pos:new_pos])
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/internal/decoder.py", line 572, in _ConvertToUnicode
    value = local_unicode(byte_str, 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 80: 'utf-8' codec can't decode byte 0xd0 in position 80: invalid continuation byte in field: SubscribeLogsResponse.message
```

**Comment by jesserockz** [comment]
The default glpyhs are here: https://github.com/esphome/esphome/blob/5edebaf4686ceb30a4d0440b52d63811e9be6efd/esphome/components/font/__init__.py#L75-L77

For displays you will need to add the russian characters to the `glyphs` key:
```yaml
font:
  - file: "pixelmix.ttf"
    id: digit_font
    size: 8
    glyphs: ...
  - file: "Pixel-UniCode.ttf"
    id: digit_font_unic
    size: 16
    glyphs: ...
```

As for the logs crashing, that''s another issue and not really supported right now.

**Comment by viktor6** [comment]
INFO Reading configuration /config/esphome/veneer_display.yaml...
INFO Detected timezone 'EET' with UTC offset 2 and daylight saving time from 27 March 03:00:00 to 30 October 04:00:00
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d /config/esphome/veneer_display
Processing veneer_display (board: d1_mini; framework: arduino; platform: platformio/espressif8266@2.6.2)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif8266 3.20704.0 (2.7.4) 
 - tool-esptool 1.413.0 (4.13) 
 - tool-esptoolpy 1.20800.0 (2.8.0) 
 - toolchain-xtensa 2.40802.200502 (4.8.2)
Library Manager: Installing Update
Library Manager: Already installed, built-in library
Dependency Graph
|-- <ESPAsyncTCP-esphome> 1.2.3
|   |-- <ESP8266WiFi> 1.0
|-- <ESPAsyncWebServer-esphome> 1.2.7
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |   |-- <ESP8266WiFi> 1.0
|   |-- <Hash> 1.0
|   |-- <ESP8266WiFi> 1.0
|   |-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
|   |-- <ESP8266WiFi> 1.0
|-- <AsyncMqttClient-esphome> 0.8.4
|   |-- <ESPAsyncTCP-esphome> 1.2.3
|   |   |-- <ESP8266WiFi> 1.0
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <DNSServer> 1.1.1
|   |-- <ESP8266WiFi> 1.0
|-- <SPI> 1.0
Retrieving maximum program size /data/veneer_display/.pioenvs/veneer_display/firmware.elf
Checking size /data/veneer_display/.pioenvs/veneer_display/firmware.elf
RAM:   [=====     ]  54.3% (used 44444 bytes from 81920 bytes)
Flash: [=====     ]  45.7% (used 477180 bytes from 1044464 bytes)
========================= [SUCCESS] Took 6.82 seconds =========================
INFO Successfully compiled program.
INFO Resolving IP address of veneer_display.local
INFO  -> 192.168.0.179
INFO Uploading /data/veneer_display/.pioenvs/veneer_display/firmware.bin (481328 bytes)
Uploading: [============================================================] 100% Done...

INFO Waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
INFO Starting log output from veneer_display.local using esphome API
INFO Connecting to veneer_display.local:6053 (192.168.0.179)
INFO Successfully connected to veneer_display.local
[22:50:25][I][app:105]: ESPHome version 1.20.4 compiled on Aug 14 2021, 22:47:56
[22:50:25][C][wifi:499]: WiFi:
[22:50:25][C][wifi:359]:   SSID: [redacted]
[22:50:25][C][wifi:360]:   IP Address: 192.168.0.179
[22:50:25][C][wifi:362]:   BSSID: [redacted]
[22:50:25][C][wifi:363]:   Hostname: 'veneer_display'
[22:50:25][C][wifi:367]:   Signal strength: -67 dB ▂▄▆█
[22:50:25][C][wifi:371]:   Channel: 8
[22:50:25][C][wifi:372]:   Subnet: 255.255.255.0
[22:50:25][C][wifi:373]:   Gateway: 192.168.0.1
[22:50:25][C][wifi:374]:   DNS1: 192.168.0.1
[22:50:25][C][wifi:375]:   DNS2: (IP unset)
[22:50:25][C][spi:081]: SPI bus:
[22:50:25][C][spi:082]:   CLK Pin: GPIO14 (Mode: OUTPUT)
[22:50:25][C][spi:084]:   MOSI Pin: GPIO13 (Mode: OUTPUT)
[22:50:25][C][spi:085]:   Using HW SPI: YES
[22:50:25][C][logger:189]: Logger:
[22:50:25][C][logger:190]:   Level: DEBUG
[22:50:25][C][logger:191]:   Log Baud Rate: 115200
[22:50:25][C][logger:192]:   Hardware UART: UART0
[22:50:25][C][homeassistant.time:010]: Home Assistant Time:
[22:50:25][C][homeassistant.time:011]:   Timezone: 'EET-2EEST-3,M3.4.0/3,M10.5.0/4'
[22:50:25][C][max7219DIGIT:046]: MAX7219DIGIT:
[22:50:25][C][max7219DIGIT:047]:   Number of Chips: 8
[22:50:25][C][max7219DIGIT:048]:   Intensity: 0
[22:50:25][C][max7219DIGIT:049]:   Scroll Mode: 0
[22:50:25][C][max7219DIGIT:050]:   Scroll Speed: 200
[22:50:25][C][max7219DIGIT:051]:   Scroll Dwell: 1000
[22:50:25][C][max7219DIGIT:052]:   Scroll Delay: 1000
[22:50:25][C][max7219DIGIT:053]:   CS Pin: GPIO12 (Mode: OUTPUT)
[22:50:26][C][max7219DIGIT:054]:   Update Interval: 5.0s
[22:50:26][C][captive_portal:148]: Captive Portal:
[22:50:26][D][api.connection:670]: Client 'Home Assistant 2021.8.6 (192.168.0.201)' connected successfully!
[22:50:26][C][web_server:142]: Web Server:
[22:50:26][C][web_server:143]:   Address: veneer_display.local:80
[22:50:26][D][time:040]: Synchronized time: Sat Aug 14 22:50:26 2021
[22:50:26][C][ota:029]: Over-The-Air Updates:
[22:50:26][C][ota:030]:   Address: veneer_display.local:8266
[22:50:26][C][ota:032]:   Using Password.
[22:50:26][C][api:095]: API Server:
[22:50:26][C][api:096]:   Address: veneer_display.local:6053
[22:50:26][C][mqtt:061]: MQTT:
[22:50:26][C][mqtt:063]:   Server Address: 192.168.0.201:1883 (192.168.0.201)
[22:50:26][C][mqtt:064]:   Username: [redacted]
[22:50:26][C][mqtt:065]:   Client ID: [redacted]
[22:50:26][C][mqtt:067]:   Discovery prefix: 'homeassistant'
[22:50:26][C][mqtt:068]:   Discovery retain: YES
[22:50:26][C][mqtt:070]:   Topic Prefix: 'veneer_display'
[22:50:26][C][mqtt:072]:   Log Topic: 'veneer_display/debug'
[22:50:26][C][mqtt:075]:   Availability: 'veneer_display/status'
[22:50:26][C][homeassistant.binary_sensor:038]: Homeassistant Binary Sensor 'pir_sensor'
[22:50:26][C][homeassistant.binary_sensor:039]:   Entity ID: 'sensor.spalnya_temperature'
[22:50:26][C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'Matrix Text'
[22:50:26][C][homeassistant.text_sensor:024]:   Entity ID: 'input_text.matrix_text'
[22:50:26][C][mqtt.text_sensor:025]: MQTT Text Sensor 'Matrix Text':
[22:50:26][C][mqtt.text_sensor:026]:   State Topic: 'veneer_display/sensor/matrix_text/state'
[22:50:26][C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'Brightness 7219'
[22:50:26][C][homeassistant.text_sensor:024]:   Entity ID: 'input_number.matrixbri'
[22:50:26][C][mqtt.text_sensor:025]: MQTT Text Sensor 'Brightness 7219':
[22:50:26][C][mqtt.text_sensor:026]:   State Topic: 'veneer_display/sensor/brightness_7219/state'
[22:50:26][C][homeassistant.text_sensor:023]: Homeassistant Text Sensor 'Kitchen Humidity'
[22:50:26][C][homeassistant.text_sensor:024]:   Entity ID: 'sensor.balkon_temperature'
[22:50:26][C][mqtt.text_sensor:025]: MQTT Text Sensor 'Kitchen Humidity':
[22:50:26][C][mqtt.text_sensor:026]:   State Topic: 'veneer_display/sensor/kitchen_humidity/state'
[22:50:26][C][homeassistant.sensor:030]: Homeassistant Sensor 'Kitchen Temp'
[22:50:26][C][homeassistant.sensor:030]:   State Class: ''
[22:50:26][C][homeassistant.sensor:030]:   Unit of Measurement: ''
[22:50:26][C][homeassistant.sensor:030]:   Accuracy Decimals: 1
[22:50:26][C][homeassistant.sensor:031]:   Entity ID: 'sensor.balkon_temperature'
[22:50:26][C][mqtt.sensor:024]: MQTT Sensor 'Kitchen Temp':
[22:50:26][C][mqtt.sensor:028]:   State Topic: 'veneer_display/sensor/kitchen_temp/state'
[22:50:26][C][mqtt.binary_sensor:018]: MQTT Binary Sensor 'pir_sensor':
[22:50:26][C][mqtt.binary_sensor:019]:   State Topic: 'veneer_display/binary_sensor/pir_sensor/state'
[22:50:26][W][homeassistant.binary_sensor:017]: Can't convert 'unknown' to binary state!
[22:50:26][D][homeassistant.text_sensor:017]: 'input_text.matrix_text': Got state '122'
[22:50:26][D][text_sensor:015]: 'Matrix Text': Sending state '122'
[22:50:26][D][homeassistant.text_sensor:017]: 'input_number.matrixbri': Got state '15.0'
[22:50:26][D][text_sensor:015]: 'Brightness 7219': Sending state '15.0'
[22:50:26][D][homeassistant.text_sensor:017]: 'sensor.balkon_temperature': Got state '28.1'
[22:50:26][D][text_sensor:015]: 'Kitchen Humidity': Sending state '28.1'
[22:50:26][D][homeassistant.sensor:024]: 'sensor.balkon_temperature': Got state 28.10
[22:50:26][D][sensor:127]: 'Kitchen Temp': Sending state 28.10000  with 1 decimals of accuracy
[22:50:26][D][homeassistant.text_sensor:017]: 'sensor.balkon_temperature': Got state '28.1'
[22:50:26][D][text_sensor:015]: 'Kitchen Humidity': Sending state '28.1'
[22:50:26][D][homeassistant.sensor:024]: 'sensor.balkon_temperature': Got state 28.10
[22:50:26][D][sensor:127]: 'Kitchen Temp': Sending state 28.10000  with 1 decimals of accuracy
[22:50:30][W][display:173]: Encountered character without representation in font: '.'
[22:50:30][W][display:173]: Encountered character without representation in font: '%'
[22:50:40][D][homeassistant.text_sensor:017]: 'sensor.balkon_temperature': Got state '28.2'
[22:50:40][D][text_sensor:015]: 'Kitchen Humidity': Sending state '28.2'
[22:50:40][D][homeassistant.sensor:024]: 'sensor.balkon_temperature': Got state 28.20
[22:50:40][D][sensor:127]: 'Kitchen Temp': Sending state 28.20000  with 1 decimals of accuracy
[22:50:40][D][homeassistant.text_sensor:017]: 'sensor.balkon_temperature': Got state '28.2'
[22:50:40][D][text_sensor:015]: 'Kitchen Humidity': Sending state '28.2'
[22:50:40][D][homeassistant.sensor:024]: 'sensor.balkon_temperature': Got state 28.20
[22:50:40][D][sensor:127]: 'Kitchen Temp': Sending state 28.20000  with 1 decimals of accuracy
[22:50:40][W][display:173]: Encountered character without representation in font: 'O'
[22:50:40][W][display:173]: Encountered character without representation in font: 'F'
[22:50:40][W][display:173]: Encountered character without representation in font: 'F'
[22:50:50][W][display:173]: Encountered character without representation in font: '.'
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/opt/esphome/esphome/api/client.py", line 408, in run
    self._run_once()
  File "/opt/esphome/esphome/api/client.py", line 398, in _run_once
    msg.ParseFromString(raw_msg)
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/message.py", line 199, in ParseFromString
    return self.MergeFromString(serialized)
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/internal/python_message.py", line 1139, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/internal/python_message.py", line 1206, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/internal/decoder.py", line 619, in DecodeField
    field_dict[key] = _ConvertToUnicode(buffer[pos:new_pos])
  File "/usr/local/lib/python3.7/dist-packages/google/protobuf/internal/decoder.py", line 572, in _ConvertToUnicode
    value = local_unicode(byte_str, 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 80: 'utf-8' codec can't decode byte 0xc2 in position 80: invalid continuation byte in field: SubscribeLogsResponse.message

WARNING Disconnected from API: Timeout while waiting for message response!
INFO Connecting to veneer_display.local:6053 (192.168.0.179)
WARNING Couldn't connect to API (Timeout while waiting for message response!). Trying to reconnect in 1 seconds
INFO Connecting to veneer_display.local:6053 (192.168.0.179)
WARNING Couldn't connect to API (Timeout while waiting for message response!). Trying to reconnect in 1 seconds
INFO Connecting to veneer_display.local:6053 (192.168.0.179)
WARNING Couldn't connect to API (Timeout while waiting for message response!). Trying to reconnect in 2 seconds
INFO Connecting to veneer_display.local:6053 (192.168.0.179)
WARNING Couldn't connect to API (Timeout while waiting for message response!). Trying to reconnect in 3 seconds
INFO Connecting to veneer_display.local:6053 (192.168.0.179)
WARNING Couldn't connect to API (Timeout while waiting for message response!). Trying to reconnect in 5 seconds
INFO Connecting to veneer_display.local:6053 (192.168.0.179)

**Comment by DavWM2020** [comment]
Is the problem solved and how?
