### ISSUE TITLE
ESP32 Bluetooth Low Energy Tracker - ValueError: could not convert string to float: 'unavailable'

### ISSUE THREAD

**Issue by tunip** [esphome/issues#238]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

Docker for ESPHome (1.12.2) and Home Assistant (0.91.4) 

**ESP (ESP32 LOLIN D32):**

**Affected component:**

https://esphome.io/components/esp32_ble_tracker.html

**Description of problem:**

Migrated my last device to ESPHome which is using BLE for getting values of my MiFlora sensors.

Everything is working as expected. Only a few error messages (for every value like temp, humidity, soil, etc.) on Home Assistant startup:

```
2019-04-16 14:43:00 ERROR (MainThread) [homeassistant.core] Error doing job: Exception in callback async_track_state_change.<locals>.state_change_listener(<Event state_...845774+02:00>>) at /usr/local/lib/python3.7/dist-packages/homeassistant/helpers/event.py:64
Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.7/dist-packages/homeassistant/helpers/event.py", line 82, in state_change_listener
    event.data.get('new_state'))
  File "/usr/local/lib/python3.7/dist-packages/homeassistant/core.py", line 333, in async_run_job
    target(*args)
  File "/usr/local/lib/python3.7/dist-packages/homeassistant/components/plant/__init__.py", line 201, in state_changed
    self._conductivity = int(float(value))
ValueError: could not convert string to float: 'unavailable'
```
As i worte, the ESPHome device works and I see correct values updated on my HA plant card. It is only this error messages on Home Assistant startup.

Do not know if it is ESPHome or Home Assistant realated.

**Additional information and things you've tried:**
N/A

**Comment by OttoWinter** [comment]
This is a HA issue.

The esphome plugin reports `unavailable` state in HA when the device is not connected (for example during startup). This is consistent with HA's standard for displaying unavailable state.

The plant monitor component needs to be updated to check for such states.
