### ISSUE TITLE
Log dont work

### ISSUE THREAD

**Issue by javilopezalarcon** [esphome/issues#2438]
### The problem

Good afternoon, Sorry for my English, I'm from Spain. I have a mistake since yesterday that I don't know how to solve it. The log does not work for me in all the esphome nodes, in all it says the same thing that I hit you below:

INFO Reading configuration /config/esphome/Cocina.yaml...
INFO Starting log output from esp-cocina.lan using esphome API
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/opt/esphome/esphome/__main__.py", line 770, in main
    return run_esphome(sys.argv)
  File "/opt/esphome/esphome/__main__.py", line 757, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/opt/esphome/esphome/__main__.py", line 339, in command_logs
    return show_logs(config, args, port)
  File "/opt/esphome/esphome/__main__.py", line 261, in show_logs
    return run_logs(config, port)
  File "/opt/esphome/esphome/components/api/client.py", line 73, in run_logs
    asyncio.run(async_run_logs(config, address))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/esphome/esphome/components/api/client.py", line 24, in async_run_logs
    zc = zeroconf.Zeroconf()
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 410, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_utils/net.py", line 359, in create_sockets
    if add_multicast_member(cast(socket.socket, listen_socket), i):
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_utils/net.py", line 276, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available

### Which version of ESPHome has the issue?

2021.9.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.6

### What platform are you using?

ESP32

### Additional information

I have 3 esp32 and 1 esp8266 wemos and the log does not work in any of them. I can compile them, upload the firm, and they work normally, it only fails when wanting to see the log or after compiling it and uploading the firm, which would show the log, it shows me the error

**Comment by javilopezalarcon** [comment]
I give you all the configuration that I have because I see the mdns label and I don't really use it.

esphome:
  name: termometros
  platform: ESP32
  board: esp-wrover-kit

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

 # necesario para no usar el dominio .local tambien se puede poner una ip
  use_address: esp-cocina.lan
  enable_mdns: false
  
# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password
  
#  Termostatos Xiaomi
esp32_ble_tracker:
  
sensor:  
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:9B:10:F8"
    temperature:
      name: "Temperatura Cocina"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 3
    humidity:
      name: "Humedad Cocina"
    battery_level:
      name: "Nivel Bateria Cocina"
    battery_voltage:
      name: "Voltage Bateria Cocina"
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:B8:DB:BC"
    temperature:
      name: "Temperatura H-Nenes"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 3
    humidity:
      name: "Humedad H-Nenes"
    battery_level:
      name: "Nivel Bateria H-Nenes"
    battery_voltage:
      name: "Voltage Bateria H-Nenes"
      

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:18:11:47"
    temperature:
      name: "Temperatura H-Pc"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 3
    humidity:
      name: "Humedad H-Pc"
    battery_level:
      name: "Nivel Bateria H-Pc"
    battery_voltage:
      name: "Voltage Bateria H-Pc"
      

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:C0:91:47"
    temperature:
      name: "Temperatura Baño"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 3
    humidity:
      name: "Humedad Baño"
    battery_level:
      name: "Nivel Bateria Baño"
    battery_voltage:
      name: "Voltage Bateria Baño"   
      
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:49:0D:8C"
    temperature:
      name: "Temperatura Exterior H-Nenes"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 3
    humidity:
      name: "Humedad Exterior H-Nenes"
    battery_level:
      name: "Nivel Bateria Exterior H-Nenes"
    battery_voltage:
      name: "Voltage Bateria Exterior H-Nenes"
      
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:8D:B3:65"
    temperature:
      name: "Temperatura Salon"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 3
    humidity:
      name: "Humedad Salon"
    battery_level:
      name: "Nivel Bateria Salon"
    battery_voltage:
      name: "Voltage Bateria Salon"
      

  - platform: atc_mithermometer
    mac_address: "A4:C1:38:1C:31:E9"
    temperature:
      name: "Temperatura H-Matrimonio"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 3
    humidity:
      name: "Humedad H-Matrimonio"
    battery_level:
      name: "Nivel Bateria H-Matrimonio"
    battery_voltage:
      name: "Voltage Bateria H-Matrimonio"
      
  - platform: atc_mithermometer
    mac_address: "A4:C1:38:28:31:9D"
    temperature:
      name: "Temperatura Exterior H-Matrimonio"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 15
            send_every: 3
    humidity:
      name: "Humedad Exterior H-Matrimonio"
    battery_level:
      name: "Nivel Bateria Exterior H-Matrimonio"
    battery_voltage:
      name: "Voltage Bateria Exterior H-Matrimonio"
