### ISSUE TITLE
Can not watch logs. OSError: [Errno 105] No buffer space available

### ISSUE THREAD

**Issue by olskar** [esphome/issues#2465]
### The problem

I can not watch the logs of any device any longer. It has worked before, see log below.

I am not sure if this is a sudden problem with ESPhome or underlying OS (or esphome docker?)

### Which version of ESPHome has the issue?

2021.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

core-2021.9.7

### What platform are you using?

ESP32

### Board

Wemos D1 mini

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/bastu.yaml...
INFO Starting log output from bastu.local using esphome API
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/opt/esphome/esphome/__main__.py", line 770, in main
    return run_esphome(sys.argv)
  File "/opt/esphome/esphome/__main__.py", line 757, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/opt/esphome/esphome/__main__.py", line 339, in command_logs
    return show_logs(config, args, port)
  File "/opt/esphome/esphome/__main__.py", line 261, in show_logs
    return run_logs(config, port)
  File "/opt/esphome/esphome/components/api/client.py", line 73, in run_logs
    asyncio.run(async_run_logs(config, address))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/esphome/esphome/components/api/client.py", line 24, in async_run_logs
    zc = zeroconf.Zeroconf()
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 410, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_utils/net.py", line 359, in create_sockets
    if add_multicast_member(cast(socket.socket, listen_socket), i):
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_utils/net.py", line 276, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available
```

**Comment by olskar** [comment]
Fixed with this guide, not an esphome issue

https://blog.mphomphego.co.za/blog/2017/06/28/why-am-i-getting-errno105-no-buffer-space-available-when-subscribing-to-multicast-addresses.html
