### ISSUE TITLE
Unexpected error while reading incoming messages: [Errno 104] Connection reset by peer - repeating periodically

### ISSUE THREAD

**Issue by paulius2k** [esphome/issues#2468]
### The problem

One of my four esp8266 Wemos D1 mini pro boards started showing ```[Errno 104] Connection reset by peer``` errors.
I am not sure when exactly this started - _probably_ with ```esphome v2021.8.2```, because my other boards with ```esphome v1.19.4``` don't have that issue.

The connection is reset periodically in exact 10 OR 15 minute intervals - see logs.

I have tried setting fixed IP for that board in the esphome yaml, then reverted as there was no difference.

I changed the power supply as well - no difference.

### Which version of ESPHome has the issue?

2021.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.7

### What platform are you using?

ESP8266

### Board

d1_mini_pro

### Example YAML snippet

```yaml
esphome:
  name: plant-watering
  platform: ESP8266
  board: d1_mini_pro

# Enable logging
logger:
  level: DEBUG
  
# Enable Home Assistant API
api:

ota:
  password: "xx"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  # Optional manual IP
  # manual_ip:
  #   static_ip: 192.168.0.141
  #   gateway: 192.168.0.1
  #   subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Plant-Watering Fallback Hotspot"
    password: "LgaWnDRYAl1k"

captive_portal:


switch:
  - platform: gpio
    name: "Plant Watering Relay-Motor"
    pin: D3
    #inverted: True
    restore_mode: ALWAYS_OFF
    
sensor:
  - platform: adc
    pin: A0
    name: "Plant moisture level Percent"
    update_interval: 5s
    unit_of_measurement: "%"
    accuracy_decimals: 0
    icon: "mdi:water-percent"
    filters:
      # 0.31v = in water
      # 0.67v = dry
      lambda: |-
        return max(min((1.0 - (x - 0.31) / (0.67 - 0.31))*100.0, 100.0), 0.0);
```

### Anything in the logs that might be useful for us?

```txt
ESPHOME logs:
[11:14:03][D][adc:104]: 'Plant moisture level Percent': Got voltage=0.44V
[11:14:03][D][sensor:121]: 'Plant moisture level Percent': Sending state 65.12587 % with 0 decimals of accuracy
[11:14:08][D][adc:104]: 'Plant moisture level Percent': Got voltage=0.44V
INFO 192.168.0.141: Unexpected error while reading incoming messages: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 505, in run_forever
    await self._run_once()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 480, in _run_once
    pkt = await self._frame_helper.read_packet()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 219, in read_packet
    return await self._read_packet_plaintext()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 197, in _read_packet_plaintext
    preamble = await self._reader.readexactly(1)
  File "/usr/lib/python3.9/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
INFO Disconnected from ESPHome API for 192.168.0.141
WARNING Disconnected from API
WARNING Can't connect to ESPHome API for 192.168.0.141: Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
INFO Trying to reconnect to 192.168.0.141 in the background
INFO Successfully connected to 192.168.0.141
[11:19:23][D][api:095]: Accepted 192.168.0.123
[11:19:23][D][api.connection:727]: Home Assistant 2021.9.7 (192.168.0.123): Connected successfully
[11:19:23][D][adc:104]: 'Plant moisture level Percent': Got voltage=0.44V
[11:19:23][D][sensor:121]: 'Plant moisture level Percent': Sending state 65.12587 % with 0 decimals of accuracy
[11:19:24][D][switch:025]: 'Plant Watering Relay-Motor' Turning OFF.
[11:19:28][D][adc:104]: 'Plant moisture level Percent': Got voltage=0.43V
[11:19:28][D][sensor:121]: 'Plant moisture level Percent': Sending state 65.39713 % with 0 decimals of accuracy
[11:19:33][D][adc:104]: 'Plant moisture level Percent': Got voltage=0.44V
[11:19:33][D][sensor:121]: 'Plant moisture level Percent': Sending state 65.12587 % with 0 decimals of accuracy
[11:19:38][D][adc:104]: 'Plant moisture level Percent': Got voltage=0.43V
[...]
[11:20:33][D][adc:104]: 'Plant moisture level Percent': Got voltage=0.43V
[11:20:33][D][sensor:121]: 'Plant moisture level Percent': Sending state 65.39713 % with 0 decimals of accuracy
INFO 192.168.0.141: Ping Failed!
INFO Disconnected from ESPHome API for 192.168.0.141
WARNING Disconnected from API
INFO 192.168.0.141: Unexpected error while reading incoming messages: 0 bytes read on a total of 1 expected bytes
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 505, in run_forever
    await self._run_once()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 480, in _run_once
    pkt = await self._frame_helper.read_packet()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 219, in read_packet
    return await self._read_packet_plaintext()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 197, in _read_packet_plaintext
    preamble = await self._reader.readexactly(1)
  File "/usr/lib/python3.9/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 1 expected bytes
INFO Successfully connected to 192.168.0.141
[11:20:48][D][adc:104]: 'Plant moisture level Percent': Got voltage=0.44V
[11:20:48][D][sensor:121]: 'Plant moisture level Percent': Sending state 65.12587 % with 0 decimals of accuracy
[11:20:53][D][adc:104]: 'Plant moisture level Percent': Got voltage=0.44V
[...]
[11:23:58][D][adc:104]: 'Plant moisture level Percent': Got voltage=0.44V
[11:23:58][D][sensor:121]: 'Plant moisture level Percent': Sending state 65.12587 % with 0 decimals of accuracy
INFO 192.168.0.141: Unexpected error while reading incoming messages: [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 505, in run_forever
    await self._run_once()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 480, in _run_once
    pkt = await self._frame_helper.read_packet()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 219, in read_packet
    return await self._read_packet_plaintext()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 197, in _read_packet_plaintext
    preamble = await self._reader.readexactly(1)
  File "/usr/lib/python3.9/asyncio/streams.py", line 723, in readexactly
    await self._wait_for_data('readexactly')
  File "/usr/lib/python3.9/asyncio/streams.py", line 517, in _wait_for_data
    await self._waiter
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 856, in _read_ready__data_received
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer
INFO Disconnected from ESPHome API for 192.168.0.141
WARNING Disconnected from API
WARNING Can't connect to ESPHome API for 192.168.0.141: Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
INFO Trying to reconnect to 192.168.0.141 in the background
INFO Successfully connected to 192.168.0.141
[11:29:18][D][api:095]: Accepted 192.168.0.123
[11:29:18][D][api.connection:727]: Home Assistant 2021.9.7 (192.168.0.123): Connected successfully
[11:29:18][D][switch:025]: 'Plant Watering Relay-Motor' Turning OFF.
[11:29:18][D][adc:104]: 'Plant moisture level Percent': Got voltage=0.43V
[11:29:18][D][sensor:121]: 'Plant moisture level Percent': Sending state 65.39713 % with 0 decimals of accuracy
[11:29:23][D][adc:104]: 'Plant moisture level Percent': Got voltage=0.43V
[11:29:23][D][sensor:121]: 'Plant moisture level Percent': Sending state 65.66840 % with 0 decimals of accuracy
[...]
[11:30:28][D][sensor:121]: 'Plant moisture level Percent': Sending state 65.39713 % with 0 decimals of accuracy
INFO 192.168.0.141: Ping Failed!
INFO Disconnected from ESPHome API for 192.168.0.141
WARNING Disconnected from API
INFO 192.168.0.141: Unexpected error while reading incoming messages: 0 bytes read on a total of 1 expected bytes
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 505, in run_forever
    await self._run_once()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 480, in _run_once
    pkt = await self._frame_helper.read_packet()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 219, in read_packet
    return await self._read_packet_plaintext()
  File "/usr/local/lib/python3.9/dist-packages/aioesphomeapi/connection.py", line 197, in _read_packet_plaintext
    preamble = await self._reader.readexactly(1)
  File "/usr/lib/python3.9/asyncio/streams.py", line 721, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 1 expected bytes
INFO Successfully connected to 192.168.0.141
[11:30:43][D][adc:104]: 'Plant moisture level Percent': Got voltage=0.44V
[11:30:43][D][sensor:121]: 'Plant moisture level Percent': Sending state 65.12587 % with 0 decimals of accuracy
```

### Additional information

```
HA logs:
Line 54706: 2021.09.22 12:08:31 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54715: 2021.09.22 12:22:31 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54719: 2021.09.22 12:32:31 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54723: 2021.09.22 12:57:31 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54727: 2021.09.22 13:07:31 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54731: 2021.09.22 13:22:31 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54736: 2021.09.22 13:42:31 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54740: 2021.09.22 13:57:31 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54748: 2021.09.22 14:02:31 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54752: 2021.09.22 14:17:34 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54756: 2021.09.22 14:27:34 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54759: 2021.09.22 14:37:34 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54763: 2021.09.22 14:52:34 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54770: 2021.09.22 15:12:34 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54774: 2021.09.22 15:22:32 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54778: 2021.09.22 15:32:49 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54783: 2021.09.22 15:44:08 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54788: 2021.09.22 15:54:04 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54794: 2021.09.22 16:04:04 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54800: 2021.09.22 16:24:03 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54806: 2021.09.22 16:34:03 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54810: 2021.09.22 16:44:03 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54813: 2021.09.22 16:54:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54819: 2021.09.22 17:04:01 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54824: 2021.09.22 17:14:01 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54828: 2021.09.22 17:24:01 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54832: 2021.09.22 17:34:01 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54838: 2021.09.22 18:04:01 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54843: 2021.09.22 18:14:02 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54849: 2021.09.22 18:34:02 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54853: 2021.09.22 18:49:01 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54858: 2021.09.22 19:04:02 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54863: 2021.09.22 19:14:02 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54871: 2021.09.22 19:29:08 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54876: 2021.09.22 19:44:04 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54882: 2021.09.22 19:59:02 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54886: 2021.09.22 20:14:07 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54891: 2021.09.22 20:29:02 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54894: 2021.09.22 20:39:07 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54900: 2021.09.22 20:49:07 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54904: 2021.09.22 20:59:02 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54909: 2021.09.22 21:24:07 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54914: 2021.09.22 21:34:02 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54918: 2021.09.22 21:49:02 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54925: 2021.09.22 22:04:07 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54929: 2021.09.22 22:14:02 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54935: 2021.09.22 22:29:02 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54940: 2021.09.22 22:49:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54947: 2021.09.22 23:04:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54952: 2021.09.22 23:19:05 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54956: 2021.09.22 23:29:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54962: 2021.09.22 23:44:05 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54966: 2021.09.22 23:54:05 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54970: 2021.09.22 23:59:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54977: 2021.09.23 00:19:05 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54981: 2021.09.23 00:29:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54984: 2021.09.23 00:39:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54989: 2021.09.23 00:49:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54993: 2021.09.23 00:59:05 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 54997: 2021.09.23 01:04:05 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55001: 2021.09.23 01:14:01 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55007: 2021.09.23 01:39:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55011: 2021.09.23 01:54:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55016: 2021.09.23 02:09:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55021: 2021.09.23 02:24:01 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55025: 2021.09.23 02:34:01 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55029: 2021.09.23 02:44:01 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55033: 2021.09.23 02:59:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55038: 2021.09.23 03:09:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55043: 2021.09.23 03:24:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55047: 2021.09.23 03:34:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55054: 2021.09.23 03:59:01 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55057: 2021.09.23 04:09:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55066: 2021.09.23 04:29:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55072: 2021.09.23 04:39:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55083: 2021.09.23 04:59:01 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55087: 2021.09.23 05:14:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55091: 2021.09.23 05:24:02 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55095: 2021.09.23 05:39:07 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55100: 2021.09.23 05:54:02 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55104: 2021.09.23 06:09:02 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55110: 2021.09.23 06:24:07 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55116: 2021.09.23 06:34:06 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55120: 2021.09.23 06:44:02 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55125: 2021.09.23 06:59:07 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
	Line 55129: 2021.09.23 07:14:07 WARNING [homeassistant.components.esphome] Can't connect to ESPHome API for plant-watering (192.168.0.141): Error connecting to ('192.168.0.141', 6053): [Errno 111] Connect call failed ('192.168.0.141', 6053)
```

**Comment by paulius2k** [comment]
Update: I have replaced my new router (Netgear AX3000 RAX40v2), on which the problem appeared, with the old router (Netgear R6400v2) and the issue disappeared, just like that... I have no idea what exactly on the router caused this behaviour. If the developers know, this could be put here if somebody bumps into a similar issue.

**Comment by krzysiek2788** [comment]
I have the same issue with official build 2021.09.2. I have esp8266+mcp23017+uart and has the same errors I remember some version before all was working fine. Maybe this new security update mess something in wifi configuration?? I have uniFi system at home and my network didn't change.

**Comment by krzysiek2788** [comment]
Also my system overview: 
![Screenshot_20210929_061326_io homeassistant companion android](https://user-images.githubusercontent.com/61471407/135202179-d47c645e-2491-4051-bb6a-e21e80140225.jpg)

**Comment by paulius2k** [comment]
Even on my other router I still have situations when ESPhome cannot connect to the API and **rebooting** the router resolves this issue.
