### ISSUE TITLE
Error after 2021.9.3 update install

### ISSUE THREAD

**Issue by theflorianmaas** [esphome/issues#2534]
### The problem

I updated my working version of ESPHome from 2021.9.2 to 2021.9.3 and now I get this error.
I get this error whenever I compile and upload firmaware in any node.

```

> [cont-init.d] 01-log-level.sh: executing... 
> [cont-init.d] 01-log-level.sh: exited 0.
> [cont-init.d] 10-requirements.sh: executing... 
> [cont-init.d] 10-requirements.sh: exited 0.
> [cont-init.d] 20-nginx.sh: executing... 
> [cont-init.d] 20-nginx.sh: exited 0.
> [cont-init.d] done.
> [services.d] starting services
> [services.d] done.
> [17:00:53] INFO: Waiting for dashboard to come up...
> [17:00:54] INFO: Starting ESPHome dashboard...
> INFO Starting dashboard web server on unix socket /var/run/esphome.sock and configuration dir /config/esphome...
> Exception in thread Thread-1:
> Traceback (most recent call last):
>   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
>     self.run()
>   File "/opt/esphome/esphome/dashboard/dashboard.py", line 504, in run
>     zc = EsphomeZeroconf()
>   File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 410, in __init__
>     listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
>   File "/usr/local/lib/python3.9/dist-packages/zeroconf/_utils/net.py", line 359, in create_sockets
>     if add_multicast_member(cast(socket.socket, listen_socket), i):
>   File "/usr/local/lib/python3.9/dist-packages/zeroconf/_utils/net.py", line 276, in add_multicast_member
>     listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
> OSError: [Errno 105] No buffer space available

```

### Which version of ESPHome has the issue?

2021.9.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.9.7

### What platform are you using?

ESP32

### Board

ESP32-cam, ESP32 mini D1,  TTGO-CAM

### Component causing the issue

zeroconf

### Anything in the logs that might be useful for us?

```txt
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] 10-requirements.sh: executing... 
[cont-init.d] 10-requirements.sh: exited 0.
[cont-init.d] 20-nginx.sh: executing... 
[cont-init.d] 20-nginx.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[17:00:53] INFO: Waiting for dashboard to come up...
[17:00:54] INFO: Starting ESPHome dashboard...
INFO Starting dashboard web server on unix socket /var/run/esphome.sock and configuration dir /config/esphome...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/opt/esphome/esphome/dashboard/dashboard.py", line 504, in run
    zc = EsphomeZeroconf()
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 410, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_utils/net.py", line 359, in create_sockets
    if add_multicast_member(cast(socket.socket, listen_socket), i):
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_utils/net.py", line 276, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available
```

**Comment by Adil-MohammedK** [comment]
@theflorianmaas Yes I do know that it is a linux command. I tried it inside bash of esphome container. So its a linux machine. And I also tried in my host Linux machine(Raspberry Pi 4). Here is a screenshot of my terminal

![image](https://user-images.githubusercontent.com/18614021/138578023-c025915d-cadb-48ef-b19e-6566aac3cd8c.png)
