### ISSUE TITLE
Unable to run esphome logs

### ISSUE THREAD

**Issue by ZephireNZ** [esphome/issues#2604]
### The problem

I am trying to read OTA logs. When running, I get an error and logs do not show.

### Which version of ESPHome has the issue?

2021.10.0

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

nodemcu

### Anything in the logs that might be useful for us?

```txt
$ esphome logs esp2_ble.yaml
INFO Reading configuration esp2_ble.yaml...
Found multiple options, please choose one:
  [1] /dev/ttyACM0 (ConBee II)
  [2] /dev/ttyUSB0 (USB Serial)
  [3] Over The Air (esp2.local)
(number): 3
INFO Starting log output from esp2.local using esphome API
Traceback (most recent call last):
  File "/usr/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome==2021.10.0', 'console_scripts', 'esphome')())
  File "/usr/lib/python3.9/site-packages/esphome/__main__.py", line 815, in main
    return run_esphome(sys.argv)
  File "/usr/lib/python3.9/site-packages/esphome/__main__.py", line 802, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/usr/lib/python3.9/site-packages/esphome/__main__.py", line 358, in command_logs
    return show_logs(config, args, port)
  File "/usr/lib/python3.9/site-packages/esphome/__main__.py", line 280, in show_logs
    return run_logs(config, port)
  File "/usr/lib/python3.9/site-packages/esphome/components/api/client.py", line 73, in run_logs
    asyncio.run(async_run_logs(config, address))
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/lib/python3.9/site-packages/esphome/components/api/client.py", line 25, in async_run_logs
    cli = APIClient(
TypeError: __init__() takes 4 positional arguments but 5 positional arguments (and 2 keyword-only arguments) were given
```

**Comment by fikovnik** [comment]
I'm experiencing the same issue with 2021.10.3. I think it is related to this commit: https://github.com/esphome/aioesphomeapi/commit/f3aaf0391df5df654bd389dfce841377c8a622d4

If I downgrade `aioesphomeapi` to 9.1.5 (version without this commit) it works.

**Comment by mmakaay** [comment]
In case you are running ESPHome from a cloned tree or something:
after upgrading ESPHome, you should run the `script/setup` script to update your dependencies.
When I ran into this error, having my dependencies updates fixed the error.

**Comment by ZephireNZ** [comment]
Ah, I think the esphome package in AUR might be the issue in that case, if the AUR installed packages aren't matching up with the actual requirements.
