### ISSUE TITLE
Error doing job: Future exception was never retrieved

### ISSUE THREAD

**Issue by holdestmade** [esphome/issues#2637]
### The problem

At random intervals, get several of these in my HA log.

No idea how to find which node is causing the problem, as have around 70

### Which version of ESPHome has the issue?

2021.10.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.6

### What platform are you using?

ESP32

### Board

na

### Component causing the issue

unknown

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant
Source: components/esphome/__init__.py:405
First occurred: 11:51:13 am (4 occurrences)
Last logged: 1:15:25 pm

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/connection.py", line 206, in _write_packet_plaintext
    await self._writer.drain()
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 190, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 405, in _try_connect
    await self._cli.connect(on_stop=self._on_disconnect, login=True)
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/client.py", line 183, in connect
    await self._connection.connect()
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/connection.py", line 470, in connect
    await self._connect_hello()
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/connection.py", line 397, in _connect_hello
    resp = await self.send_message_await_response(hello, HelloResponse)
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/connection.py", line 617, in send_message_await_response
    res = await self.send_message_await_response_complex(
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/connection.py", line 595, in send_message_await_response_complex
    await self.send_message(send_msg)
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/connection.py", line 539, in send_message
    await self._frame_helper.write_packet(
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/connection.py", line 212, in write_packet
    await self._write_packet_plaintext(packet)
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/connection.py", line 208, in _write_packet_plaintext
    raise SocketAPIError(f"Error while writing data: {err}") from err
aioesphomeapi.core.SocketAPIError: Error while writing data: Connection lost
```

**Comment by adrianmihalko** [comment]
I have same problem.

`
Logger: homeassistant
Source: /usr/src/homeassistant/homeassistant/runner.py:98 
First occurred: 27 December 2021, 17:54:00 (2 occurrences) 
Last logged: 12:42:34

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/_frame_helper.py", line 68, in write_packet
    await self._writer.drain()
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 387, in drain
    await self._protocol._drain_helper()
  File "/usr/local/lib/python3.9/asyncio/streams.py", line 190, in _drain_helper
    raise ConnectionResetError('Connection lost')
ConnectionResetError: Connection lost

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/reconnect_logic.py", line 121, in _try_connect
    await self._cli.connect(on_stop=self._on_disconnect, login=True)
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/client.py", line 176, in connect
    await self._connection.connect(login=login)
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/connection.py", line 262, in connect
    await self._connect_hello()
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/connection.py", line 189, in _connect_hello
    resp = await self.send_message_await_response(hello, HelloResponse)
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/connection.py", line 411, in send_message_await_response
    res = await self.send_message_await_response_complex(
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/connection.py", line 389, in send_message_await_response_complex
    await self.send_message(send_msg)
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/connection.py", line 333, in send_message
    await self._frame_helper.write_packet(
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/_frame_helper.py", line 70, in write_packet
    raise SocketAPIError(f"Error while writing data: {err}") from err
aioesphomeapi.core.SocketAPIError: Error while writing data: Connection lost
`
