### ISSUE TITLE
Number initial_value is not set to min value

### ISSUE THREAD

**Issue by raidnet-ms** [esphome/issues#2698]
### The problem

If I set a number template entity with min and max value but without an initial_value, assumed to what i read in the documentation, the initial_value should be the min value, while I get a NAN value until i set anything in the lovelace view.

### Which version of ESPHome has the issue?

2021.10.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2021.10.8

### What platform are you using?

ESP8266

### Board

esp01

### Component causing the issue

number templeate

### Example YAML snippet

```yaml
number:
  - platform: template
    name: Minutes delay esph
    step: 5
    min_value: 0
    max_value: 60
    id: time_spr1
    optimistic: true
```

### Anything in the logs that might be useful for us?
```
2021-11-10 22:05:41 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/client.py", line 167, in _on_stop
    await on_stop()
  File "/usr/local/lib/python3.9/site-packages/aioesphomeapi/reconnect_logic.py", line 84, in _on_disconnect
    await self._on_disconnect_cb()
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 291, in on_disconnect
    disconnect_cb()
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 289, in remove_listener
    _async_remove_indexed_listeners(
  File "/usr/src/homeassistant/homeassistant/helpers/event.py", line 317, in _async_remove_indexed_listeners
    callbacks[storage_key].remove(job)
KeyError: 'input_number.minuti_irrigazione_prato'
2021-11-10 22:05:43 ERROR (MainThread) [homeassistant.components.hassio.handler] Client error on /homeassistant/restart request Server disconnected
```

**Comment by jesserockz** [comment]
Fixed in esphome/esphome#2692
