### ISSUE TITLE
python3.9？？？

### ISSUE THREAD

**Issue by Awe7** [esphome/issues#2947]
### The problem

Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/dist-packages/esphome/__main__.py", line 823, in main
    return run_esphome(sys.argv)
  File "/usr/local/lib/python3.9/dist-packages/esphome/__main__.py", line 810, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/usr/local/lib/python3.9/dist-packages/esphome/__main__.py", line 324, in command_compile
    exit_code = write_cpp(config)
  File "/usr/local/lib/python3.9/dist-packages/esphome/__main__.py", line 157, in write_cpp
    generate_cpp_contents(config)
  File "/usr/local/lib/python3.9/dist-packages/esphome/__main__.py", line 169, in generate_cpp_contents
    CORE.flush_tasks()
  File "/usr/local/lib/python3.9/dist-packages/esphome/core/__init__.py", line 613, in flush_tasks
    self.event_loop.flush_tasks()
  File "/usr/local/lib/python3.9/dist-packages/esphome/coroutine.py", line 245, in flush_tasks
    next(task.iterator)
  File "/usr/local/lib/python3.9/dist-packages/esphome/core/config.py", line 283, in _add_platformio_options
    cg.add_platformio_option(key, val)
  File "/usr/local/lib/python3.9/dist-packages/esphome/cpp_generator.py", line 595, in add_platformio_option
    CORE.add_platformio_option(key, value)
  File "/usr/local/lib/python3.9/dist-packages/esphome/core/__init__.py", line 707, in add_platformio_option
    assert isinstance(value, list)
AssertionError

### Which version of ESPHome has the issue?

Current version: 2021.12.3 

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

Home Assistant 2021.12.9

### What platform are you using?

ESP32

### Additional information

System Health

version: core-2021.12.9
installation_type: Home Assistant OS
dev: false
hassio: true
docker: true
user: root
virtualenv: false
python_version: 3.9.7
os_name: Linux
os_version: 5.10.88
arch: x86_64
timezone: Asia/Shanghai

GitHub API: ok
Github API Calls Remaining: 4988
Installed Version: 1.19.3
Stage: running
Available Repositories: 939
Downloaded Repositories: 36

logged_in: false
can_reach_cert_server: ok
can_reach_cloud_auth: failed to load: timeout
can_reach_cloud: failed to load: timeout

host_os: Home Assistant OS 7.1
update_channel: stable
supervisor_version: supervisor-2021.12.2
docker_version: 20.10.9
disk_total: 31.3 GB
disk_used: 6.8 GB
healthy: true
supported: true
board: ova
supervisor_api: ok
version_api: failed to load: timeout
installed_addons: RPC Shutdown (2.2), Samba share (9.5.1), File editor (5.3.3), Mosquitto broker (6.0.1), Terminal & SSH (9.3.0), VLC (0.1.3), ESPHome (2021.12.3)

dashboards: 2
resources: 23
views: 4
error: /config/homekit-infused.yaml not found
mode: storage

**Comment by jesserockz** [comment]
Going to need your full config to know which components are combining to cause this error
