### ISSUE TITLE
first run install fails on LibraryManager

### ISSUE THREAD

**Issue by stoneobscurity** [esphome/issues#296]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

rasp-pi-3, w/120gb SSD.

**ESP (ESP32/ESP8266, Board/Sonoff):**

NodeMCU generic 8266

fresh install
1.12.2

**Affected component:**

**Description of problem:**

```pi@piHouse:~/esp $ python2 -m esphome herp.yaml run
INFO Reading configuration...
WARNING The esphomeyaml section has been renamed to esphome in 1.11.0. Please replace 'esphomeyaml:' in your configuration with 'esphome:'.
INFO Generating C++ source...
INFO Compiling app...
INFO Running:  platformio run -d herpahome
Processing herpahome (platform: espressif8266@1.8.0; framework: arduino; board: nodemcuv2)
------------------------------------------------------------------------------------------------------------------------
LibraryManager: Installing id=346 @ 0.8.2
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing id=305 @ ^1.1.0
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing id=1826 @ ^1.0.0
Downloading...
Unpacking  [####################################]  100%
LibraryManager: Installing v1.12.2
Error: Please read http://bit.ly/package-manager-ioerror
Error: Traceback (most recent call last):
  File "/home/pi/.local/lib/python2.7/site-packages/platformio/__main__.py", line 120, in main
    cli(None, None, None)
  File "/home/pi/.local/lib/python2.7/site-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/home/pi/.local/lib/python2.7/site-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/.local/lib/python2.7/site-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/.local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/click/decorators.py", line 16, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/platformio/commands/run.py", line 107, in cli
    result = (envname, ep.process())
  File "/home/pi/.local/lib/python2.7/site-packages/platformio/commands/run.py", line 207, in process
    result = self._run()
  File "/home/pi/.local/lib/python2.7/site-packages/platformio/commands/run.py", line 302, in _run
    self.verbose)
  File "/home/pi/.local/lib/python2.7/site-packages/platformio/commands/run.py", line 325, in _autoinstall_libdeps
    ctx.invoke(cmd_lib_install, libraries=[lib], silent=not verbose)
  File "/home/pi/.local/lib/python2.7/site-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/pi/.local/lib/python2.7/site-packages/platformio/commands/lib.py", line 103, in lib_install
    library, silent=silent, interactive=interactive, force=force)
  File "/home/pi/.local/lib/python2.7/site-packages/platformio/managers/lib.py", line 352, in install
    force=force)
  File "/home/pi/.local/lib/python2.7/site-packages/platformio/managers/package.py", line 721, in install
    name, url, requirements, track=True)
  File "/home/pi/.local/lib/python2.7/site-packages/platformio/managers/package.py", line 508, in _install_from_url
    dlpath = self.download(url, tmp_dir, sha1)
  File "/home/pi/.local/lib/python2.7/site-packages/platformio/managers/package.py", line 199, in download
    raise e
ConnectionError: HTTPSConnectionPool(host='codeload.github.com', port=443): Max retries exceeded with url: /esphome/esphome-core/zip/v1.12.2 (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x75da8d50>: Failed to establish a new connection: [Errno 111] Connection refused',))

============================================================

An unexpected error occurred. Further steps:

* Verify that you have the latest version of PlatformIO using
  `pip install -U platformio` command

* Try to find answer in FAQ Troubleshooting section
  https://docs.platformio.org/page/faq.html

* Report this problem to the developers
  https://github.com/platformio/platformio-core/issues

============================================================

```

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE
pi@piHouse:~/esp $ cat herp.yaml 
esphomeyaml:
  name: herpahome
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: 'Alexa_Is_Always_Listening'
  password: 'pass'

mqtt:
  broker: 'ip'
  username: 'hass'
  password: 'pass'

# Enable logging
#logger:

ota:
  password: 'pass'

sensor:
  - platform: dht
    pin: D1
    model: DHT22
    update_interval: 10s
    temperature:
      name: "Warm Temperature"
      unit_of_measurement: "°F"
      accuracy_decimals: 1
      retain: True
      discovery: False
      expire_after: 30s
      availability:
        topic: warm/temperature
        payload_available: online
        payload_not_available: offline
    humidity:
      name: "Warm Humidity"
      unit_of_measurement: "%"
      accuracy_decimals: 1
      retain: True
      discovery: False
      expire_after: 30s
      availability:
        topic: warm/humidity
        payload_available: online
        payload_not_available: offline
  - platform: dht
    pin: D2
    model: DHT22
    update_interval: 10s
    temperature:
      name: "Cool Temperature"
      unit_of_measurement: "°F"
      accuracy_decimals: 1
      retain: True
      discovery: False
      expire_after: 30s
      availability:
        topic: cool/temperature
        payload_available: online
        payload_not_available: offline
    humidity:
      name: "Cool Humidity"
      unit_of_measurement: "%"
      accuracy_decimals: 1
      retain: True
      discovery: False
      expire_after: 30s
      availability:
        topic: cool/humidity
        payload_available: online
        payload_not_available: offline

```

**Traceback (if applicable):**

```

```

**Additional information and things you've tried:**

**Comment by stoneobscurity** [comment]
resolved.

it was my pi-hole blocking.
