### ISSUE TITLE
PackageNotFoundError raised when running esphome in docker

### ISSUE THREAD

**Issue by filmkorn** [esphome/issues#3089]
### The problem

Running the following docker command line on a Raspbian:

> docker run --name esphome --rm -v /media/disk/homeassistant/esphome:/esphome -it esphome/esphome run /esphome/config.yaml

Results in the following traceback:
```
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/usr/local/bin/esphome", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: esphome
```

The last working version of the image I could find was `2021.12.3`.

What am I doing wrong? Any help would be appreciated.

### Which version of ESPHome has the issue?

2022.1+

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

### Board

Wemos D1 Mini

### Anything in the logs that might be useful for us?

```txt
Creating cache directory /config/.esphome/platformio
You can change this behavior by mounting a directory to the container's /cache directory.
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/usr/local/bin/esphome", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: esphome
```

**Comment by OttoWinter** [comment]
```
docker run --name esphome --rm -v /media/disk/homeassistant/esphome:/esphome -it esphome/esphome run /esphome/config.yaml
```

The issue is in the volume mount; you should mount to `/config`, not `/esphome` (see also getting started guide)
