### ISSUE TITLE
Error resolving on missing ipv6 address

### ISSUE THREAD

**Issue by lutzky** [esphome/issues#3125]
### The problem

I don't generally use ipv6 (though, in the future, who knows). I run homeassistant on docker on ubuntu. The devices mostly work fine; however, after a restart today, homeassistant refused to connect to one of my devices, with the following error:

```
2022-03-09 13:06:20 WARNING (MainThread) [aioesphomeapi.reconnect_logic] Can't connect to ESPHome API for ledtest @ ledtest.pollitzky-iot: Erro
r resolving IP address: [Errno -2] Name does not resolve                                                                                       
```

The name `ledtest.pollitzky-iot` does resolve, but not for ipv6:

```
$ host ledtest.pollitzky-iot
ledtest.pollitzky-iot has address 192.168.107.248
Host ledtest.pollitzky-iot not found: 3(NXDOMAIN)
$ host -t A ledtest.pollitzky-iot
ledtest.pollitzky-iot has address 192.168.107.248
```

Adding an entry "192.168.107.248 ledtest.pollitzky-iot" to `/etc/hosts` works around the problem, but is hacky. Is this the ESPHome-in-homeassistant code insisting on using ipv6, or something about homeassistant itself?

### Which version of ESPHome has the issue?

2022.2.6

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.3.3

### What platform are you using?

ESP8266

**Comment by lutzky** [comment]
Some more information which is perhaps helpful: Apparently the error originates here: https://github.com/esphome/aioesphomeapi/blob/583a97066ae6e5c39c034115d44850c19b5c3091/aioesphomeapi/host_resolver.py#L136

Indeed, `getaddrinfo` returns an error... but only inside the container:

```
$ python3 --version
Python 3.8.10
$ python3 -c 'import socket; print(socket.getaddrinfo("ledtest.pollitzky-iot",80))'
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('192.168.107.248', 80)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('192.168.107.248', 80)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_RAW: 3>, 0, '', ('192.168.107.248', 80))]
$
$ docker exec homeassistant python3 --version
Python 3.9.9
$ docker exec homeassistant python3 -c 'import socket; print(socket.getaddrinfo("ledtest.pollitzky-iot",80))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
```

I'm not sure if this is down to the python version or something about the docker container's network configuration.

**Comment by lutzky** [comment]
It's not the python version, as this gives the desired results:

```
docker run --rm python:3.9.9 python3 -c 'import socket; print(socket.getaddrinfo("ledtest.pollitzky-iot",80))'
```
