### ISSUE TITLE
HA Auto Discovery is broken for template select entities

### ISSUE THREAD

**Issue by kquinsland** [esphome/issues#3264]
### The problem

I have a simple `select`: in my yaml:

```yaml
select:
  - platform: template
    internal: false
    id: tmpl_sel_active_thing
    name: "TheSelectedThing"
    optimistic: false
    options:
      - "1"
      - "2"
    set_action:
      then:
        ...
    lambda: |-
     ...
```

This yaml was working in builds done just before I did a `pip install esphome --upgrade` about an hour ago.

I did a new build and was disappointed to see that this entity was the ONLY one that wasn't automatically discoverd as part of the same device.

Here's the relevant bit from my HA logs:

```
2022-05-05 03:07:36 ERROR (MainThread) [homeassistant.util.logging] Exception in async_discover when dispatching 'mqtt_discovery_new_select_mqtt': ({'options': ['1', '2''], 'name': 'TheSelectedThing', 'state_topic': 'projectName/select/active_thing/state', 'command_topic': 'projectName/select/active_thing/command', 'availability_topic': 'projectName/status', 'unique_id': 'ESPselectactive_thing', 'device': {'identifiers': 'a4cf1224b30c', 'name': 'projectName', 'sw_version': None, 'model': 'mhetesp32minikit', 'manufacturer': 'espressif'}, 'platform': 'mqtt'},)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 246, in async_discover
    config = schema(discovery_payload)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 218, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 341, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/validators.py", line 337, in _exec
    v = func(v)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.9/site-packages/voluptuous/schema_builder.py", line 432, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: string value is None for dictionary value @ data['device']['sw_version']
```

And this is what my MQTT broker has for the `homeassistant/select/projectName/active_thing/config`

This is what my MQTT client shows:

```
{"ops":["1","2","3","4","5","6","7","8"],"name":"TheSelectedThing","stat_t":"projectName/select/active_thing/state","cmd_t":"projectName/select/active_thing/command","avty_t":"projectName/status","uniq_id":"ESPselectactive_thing","dev":{"ids":"a4cf1224b30c","name":"projectName","sw":null,"mdl":"mhetesp32minikit","mf":"espressif"}}
```

My environment:

```shell
❯ esphome version
Version: 2022.4.0
❯ python --version
Python 3.10.4
❯ pip index versions esphome
WARNING: pip index is currently an experimental command. It may be removed/changed in a future release without prior warning.
esphome (2022.4.0)
Available versions: 2022.4.0, 2022.3.2, 2022.3.1, 2022.3.0, 2022.2.6, 2022.2.5, 2022.2.4, 2022.2.3, 2022.2.2, 2022.2.1, 2022.2.0, 2022.1.4, 2022.1.3, 2022.1.2, 2022.1.1, 2022.1.0, 2021.12.3, 2021.12.2, 2021.12.1, 2021.12.0, 2021.11.4, 2021.11.3, 2021.11.2, 2021.11.1, 2021.11.0, 2021.10.3, 2021.10.2, 2021.10.1, 2021.10.0, 2021.9.3, 2021.9.2, 2021.9.1, 2021.9.0, 2021.8.2, 2021.8.1, 2021.8.0, 1.20.4, 1.20.3, 1.20.2, 1.20.1, 1.20.0, 1.19.4, 1.19.3, 1.19.2, 1.19.1, 1.19.0, 1.18.0, 1.17.2, 1.17.1, 1.17.0, 1.16.2, 1.16.1, 1.16.0, 1.15.3, 1.15.2, 1.15.1, 1.15.0, 1.14.5, 1.14.4, 1.14.3, 1.14.2, 1.14.1, 1.14.0, 1.13.6, 1.13.5, 1.13.4, 1.13.3, 1.13.2, 1.13.1, 1.13.0, 1.12.2, 1.12.1, 1.12.0, 1.11.2, 1.11.1, 1.11.0, 1.10.1
  INSTALLED: 2022.4.0
  LATEST:    2022.4.0
❯ pip install esphome --upgrade --target=2022.3.2
<...>

```

### Which version of ESPHome has the issue?

2022.4.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

core-2022.4.5

### What platform are you using?

ESP32

**Comment by kquinsland** [comment]
I was able to recover the previous build that was working and got this from the mqtt broker:

```json
{"ops":["1","2"],"name":"TheSelectedThing","stat_t":"projectName/select/project_name/state","cmd_t":"projectName/select/project_name/command","avty_t":"projectName/status","uniq_id":"ESPselectproject_name","dev":{"ids":"807d3ab97678","name":"projectName","sw":"esphome v2022.3.2 Apr 17 2022, 11:14:08","mdl":"mhetesp32minikit","mf":"espressif"}}
```

**Comment by norriscm** [comment]
I was able to resolve a related issue by reverting https://github.com/esphome/esphome/pull/3384/commits/3a9410f5f6342d56e0a752ac3123b5ab66012882

That commit causes the json component to allocate a buffer that is too small to hold the config message, which ends up truncated and invalid as a result.

**Comment by kquinsland** [comment]
I am no longer able to reproduce this with the release of `2022.5.0`.  The full and proper payload is sent to the topic, now.

**Comment by derandiunddasbo** [comment]
Yes, seems to work again for meas well.
