### ISSUE TITLE
Custom outputs stopped working on dev branch

### ISSUE THREAD

**Issue by glmnet** [esphome/issues#346]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

command line dev branch

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP8266
**Affected component:**

Custom outputs

**Description of problem:**
Validation / schema parsing seems to be failing

**Problem-relevant YAML-configuration entries:**
```yaml
esphome:
  name: esphome
  platform: ESP8266
  board: nodemcu
  
output:
- platform: custom
  type: binary
  lambda: |-
    return 1;
  outputs:
  - id: a_custom_output
    
```

**Traceback (if applicable):**

```
?[32mINFO Reading configuration...?[0m
?[31mERROR Unexpected exception while reading configuration:?[0m
Traceback (most recent call last):
  File "C:\python27\Scripts\esphome-script.py", line 11, in <module>
    load_entry_point('esphome', 'console_scripts', 'esphome')()
  File "c:\git\esphome\esphome\__main__.py", line 480, in main
    return run_esphome(sys.argv)
  File "c:\git\esphome\esphome\__main__.py", line 463, in run_esphome
    config = read_config(args.verbose)
  File "c:\git\esphome\esphome\config.py", line 793, in read_config
    res = load_config()
  File "c:\git\esphome\esphome\config.py", line 653, in load_config
    return _load_config()
  File "c:\git\esphome\esphome\config.py", line 641, in _load_config
    result = validate_config(config)
  File "c:\git\esphome\esphome\config.py", line 554, in validate_config
    validated = OrderedDict(validated)
  File "c:\python27\lib\collections.py", line 69, in __init__
    self.__update(*args, **kwds)
  File "c:\python27\lib\_abcoll.py", line 571, in update
    for key, value in other:
TypeError: 'NoneType' object is not iterable

```

**Additional information and things you've tried:**

**Comment by glmnet** [comment]
Thank you!!! I'll test it tonight
