### ISSUE TITLE
After updating HA and the addon installation and validation is broken

### ISSUE THREAD

**Issue by bobvmierlo** [esphome/issues#3656]
### The problem

After updating HA to 2022.10.0 and also the esphome addon to 2022.9.3, installation and validation is completely broken. Fails every time with zero output.

See screenshots below:
![IMG_0057](https://user-images.githubusercontent.com/38190383/194393952-2e61c6ea-1178-4f34-bb34-d7c16971f2f4.png)

![IMG_0058](https://user-images.githubusercontent.com/38190383/194393971-08d4294b-029d-4982-b3c7-74b0276e4a33.png)

![IMG_0059](https://user-images.githubusercontent.com/38190383/194393992-6c2058d9-3109-4006-b404-d540f4098a30.png)

### Which version of ESPHome has the issue?

2022.9.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.10.0

### What platform are you using?

ESP8266

### Board

Any

### Anything in the logs that might be useful for us?

This is from the ha supervisor logs, timestamp matches with triggering a validation in esphome. Not sure if it’s related though.

```
XXX lineno: 391, opcode: 0
22-10-06 20:50:49 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-9948' coro=<_websocket_forward() done, defined at /usr/src/supervisor/supervisor/api/ingress.py:276> exception=SystemError('unknown opcode')>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/api/ingress.py", line 279, in _websocket_forward
    async for msg in ws_from:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_ws.py", line 480, in __anext__
    msg = await self.receive()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_ws.py", line 391, in receive
    if self._reader is None:
SystemError: unknown opcode
```

**Comment by bobvmierlo** [comment]
Fixed after installing OS9.2 and thus a full reboot of the VM
