### ISSUE TITLE
Error pairing Eve bluetooth device with notification capabilities

### ISSUE THREAD

**Issue by virtualm2000** [esphome/issues#3694]
### The problem

When I try to pair a device like Eve Door or Eve Motion I get an error on ESP32 side then timeout error in HA.

### Which version of ESPHome has the issue?

All including 2022.10.0b2

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2022.10.4

### What platform are you using?

ESP32

### Board

ESP32DEV

### Component causing the issue

bluetooth_proxy

### Example YAML snippet

```yaml
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true
```

### Anything in the logs that might be useful for us?

```txt
ESP32:

[07:27:31][D][esp32_ble_client:036]: Found device at MAC address [E0:08:18:11:9D:12]
[07:27:31][I][esp32_ble_client:058]: Attempting BLE connection to e0:08:18:11:9d:12
[07:27:38][I][esp32_ble_client:142]: Service UUID: 0x1800
[07:27:38][I][esp32_ble_client:143]:   start_handle: 0x1  end_handle: 0x7
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 0x2A00, handle 0x3, properties 0x2
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 0x2A01, handle 0x5, properties 0x2
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 0x2A04, handle 0x7, properties 0x2
[07:27:38][I][esp32_ble_client:142]: Service UUID: 0x1801
[07:27:38][I][esp32_ble_client:143]:   start_handle: 0x8  end_handle: 0x8
[07:27:38][I][esp32_ble_client:142]: Service UUID: 0000003E-0000-1000-8000-0026BB765291
[07:27:38][I][esp32_ble_client:143]:   start_handle: 0x9  end_handle: 0x20
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 00000023-0000-1000-8000-0026BB765291, handle 0xb, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 00000014-0000-1000-8000-0026BB765291, handle 0xe, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 00000020-0000-1000-8000-0026BB765291, handle 0x11, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 00000021-0000-1000-8000-0026BB765291, handle 0x14, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 00000030-0000-1000-8000-0026BB765291, handle 0x17, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 00000052-0000-1000-8000-0026BB765291, handle 0x1a, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 00000053-0000-1000-8000-0026BB765291, handle 0x1d, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic E604E95D-A759-4817-87D3-AA005083A0D1, handle 0x20, properties 0x2
[07:27:38][I][esp32_ble_client:142]: Service UUID: 000000A2-0000-1000-8000-0026BB765291
[07:27:38][I][esp32_ble_client:143]:   start_handle: 0x21  end_handle: 0x29
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 00000037-0000-1000-8000-0026BB765291, handle 0x23, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 000000A5-0000-1000-8000-0026BB765291, handle 0x26, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic E604E95D-A759-4817-87D3-AA005083A0D1, handle 0x29, properties 0x2
[07:27:38][I][esp32_ble_client:142]: Service UUID: 00000055-0000-1000-8000-0026BB765291
[07:27:38][I][esp32_ble_client:143]:   start_handle: 0x2a  end_handle: 0x38
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 0000004C-0000-1000-8000-0026BB765291, handle 0x2c, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 0000004E-0000-1000-8000-0026BB765291, handle 0x2f, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 0000004F-0000-1000-8000-0026BB765291, handle 0x32, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 00000050-0000-1000-8000-0026BB765291, handle 0x35, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic E604E95D-A759-4817-87D3-AA005083A0D1, handle 0x38, properties 0x2
[07:27:38][I][esp32_ble_client:142]: Service UUID: 00000085-0000-1000-8000-0026BB765291
[07:27:38][I][esp32_ble_client:143]:   start_handle: 0x39  end_handle: 0x4e
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 00000023-0000-1000-8000-0026BB765291, handle 0x3b, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 00000022-0000-1000-8000-0026BB765291, handle 0x3e, properties 0x2a
[07:27:38][I][esp32_ble_client.service:057]:  characteristic E863F120-079E-48FF-8F27-9C2605A29F52, handle 0x42, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic E863F12D-079E-48FF-8F27-9C2605A29F52, handle 0x45, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic E863F11A-079E-48FF-8F27-9C2605A29F52, handle 0x48, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic 000000A5-0000-1000-8000-0026BB765291, handle 0x4b, properties 0xa
[07:27:38][I][esp32_ble_client.service:057]:  characteristic E604E95D-A759-4817-87D3-AA005083A0D1, handle 0x4e, properties 0x2
[07:27:39][I][esp32_ble_client:142]: Service UUID: 00000096-0000-1000-8000-0026BB765291
[07:27:39][I][esp32_ble_client:143]:   start_handle: 0x4f  end_handle: 0x60
[07:27:39][I][esp32_ble_client.service:057]:  characteristic 00000023-0000-1000-8000-0026BB765291, handle 0x51, properties 0xa
[07:27:39][I][esp32_ble_client.service:057]:  characteristic 00000068-0000-1000-8000-0026BB765291, handle 0x54, properties 0x2a
[07:27:39][I][esp32_ble_client.service:057]:  characteristic 0000008F-0000-1000-8000-0026BB765291, handle 0x58, properties 0x2a
[07:27:39][I][esp32_ble_client.service:057]:  characteristic 00000079-0000-1000-8000-0026BB765291, handle 0x5c, properties 0x2a
[07:27:39][I][esp32_ble_client.service:057]:  characteristic E604E95D-A759-4817-87D3-AA005083A0D1, handle 0x60, properties 0x2
[07:27:39][I][esp32_ble_client:142]: Service UUID: E863F007-079E-48FF-8F27-9C2605A29F52
[07:27:39][I][esp32_ble_client:143]:   start_handle: 0x61  end_handle: 0x81
[07:27:39][I][esp32_ble_client.service:057]:  characteristic 00000023-0000-1000-8000-0026BB765291, handle 0x63, properties 0xa
[07:27:39][I][esp32_ble_client.service:057]:  characteristic E863F11E-079E-48FF-8F27-9C2605A29F52, handle 0x66, properties 0xa
[07:27:39][I][esp32_ble_client.service:057]:  characteristic E863F112-079E-48FF-8F27-9C2605A29F52, handle 0x69, properties 0xa
[07:27:39][I][esp32_ble_client.service:057]:  characteristic E863F11C-079E-48FF-8F27-9C2605A29F52, handle 0x6c, properties 0xa
[07:27:39][I][esp32_ble_client.service:057]:  characteristic E863F121-079E-48FF-8F27-9C2605A29F52, handle 0x6f, properties 0xa
[07:27:39][I][esp32_ble_client.service:057]:  characteristic E863F116-079E-48FF-8F27-9C2605A29F52, handle 0x72, properties 0xa
[07:27:39][I][esp32_ble_client.service:057]:  characteristic E863F117-079E-48FF-8F27-9C2605A29F52, handle 0x75, properties 0xa
[07:27:39][I][esp32_ble_client.service:057]:  characteristic E863F131-079E-48FF-8F27-9C2605A29F52, handle 0x78, properties 0xa
[07:27:39][I][esp32_ble_client.service:057]:  characteristic E863F11D-079E-48FF-8F27-9C2605A29F52, handle 0x7b, properties 0xa
[07:27:39][I][esp32_ble_client.service:057]:  characteristic 000000A5-0000-1000-8000-0026BB765291, handle 0x7e, properties 0xa
[07:27:39][I][esp32_ble_client.service:057]:  characteristic E604E95D-A759-4817-87D3-AA005083A0D1, handle 0x81, properties 0x2
[07:27:39][D][esp32_ble_tracker:264]: Starting scan...
[07:27:47][D][esp-idf:000]: W (31211728) BT_HCI: hcif disc complete: hdl 0x0, rsn 0x8

[07:27:47][D][esp-idf:000]: W (31211738) BT_APPL: gattc_conn_cb: if=3 st=0 id=3 rsn=0x8

[07:27:47][W][bluetooth_proxy:090]: Error reading char/descriptor at handle 0x2C, status=133


HA:

2022-10-15T08:28:49.539925378+01:00 2022-10-15 08:28:49.536 ERROR (MainThread) [homeassistant.components.homekit_controller.config_flow] Pairing attempt failed with an unhandled exception
2022-10-15T08:28:49.540066096+01:00 Traceback (most recent call last):
2022-10-15T08:28:49.540097903+01:00   File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 445, in send_message_await_response_complex
2022-10-15T08:28:49.540129679+01:00     await fut
2022-10-15T08:28:49.540169458+01:00 asyncio.exceptions.CancelledError
2022-10-15T08:28:49.540190076+01:00 
2022-10-15T08:28:49.540208001+01:00 During handling of the above exception, another exception occurred:
2022-10-15T08:28:49.540224610+01:00 
2022-10-15T08:28:49.540247277+01:00 Traceback (most recent call last):
2022-10-15T08:28:49.540270490+01:00   File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 444, in send_message_await_response_complex
2022-10-15T08:28:49.540292523+01:00     async with async_timeout.timeout(timeout):
2022-10-15T08:28:49.540309277+01:00   File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 129, in __aexit__
2022-10-15T08:28:49.540324127+01:00     self._do_exit(exc_type)
2022-10-15T08:28:49.540347147+01:00   File "/usr/local/lib/python3.10/site-packages/async_timeout/__init__.py", line 212, in _do_exit
2022-10-15T08:28:49.540369658+01:00     raise asyncio.TimeoutError
2022-10-15T08:28:49.540392670+01:00 asyncio.exceptions.TimeoutError
2022-10-15T08:28:49.540450797+01:00 
2022-10-15T08:28:49.540474912+01:00 The above exception was the direct cause of the following exception:
2022-10-15T08:28:49.540495675+01:00 
2022-10-15T08:28:49.540518185+01:00 Traceback (most recent call last):
2022-10-15T08:28:49.540544048+01:00   File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 64, in _async_wrap_bluetooth_operation
2022-10-15T08:28:49.540565015+01:00     return await func(self, *args, **kwargs)
2022-10-15T08:28:49.540579480+01:00   File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 317, in read_gatt_char
2022-10-15T08:28:49.540595792+01:00     return await self._client.bluetooth_gatt_read(
2022-10-15T08:28:49.540609476+01:00   File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 538, in bluetooth_gatt_read
2022-10-15T08:28:49.540628603+01:00     resp = await self._connection.send_message_await_response_complex(
2022-10-15T08:28:49.540651975+01:00   File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 447, in send_message_await_response_complex
2022-10-15T08:28:49.540667174+01:00     raise TimeoutAPIError(
2022-10-15T08:28:49.540680568+01:00 aioesphomeapi.core.TimeoutAPIError: Timeout waiting for response for <class 'api_pb2.BluetoothGATTReadRequest'>
2022-10-15T08:28:49.540693044+01:00 
2022-10-15T08:28:49.540706699+01:00 The above exception was the direct cause of the following exception:
2022-10-15T08:28:49.540727526+01:00 
2022-10-15T08:28:49.540745864+01:00 Traceback (most recent call last):
2022-10-15T08:28:49.540759767+01:00   File "/usr/src/homeassistant/homeassistant/components/homekit_controller/config_flow.py", line 479, in async_step_pair
2022-10-15T08:28:49.540772828+01:00     self.finish_pairing = await discovery.async_start_pairing(self.hkid)
2022-10-15T08:28:49.540786002+01:00   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 76, in _async_wrap
2022-10-15T08:28:49.540803105+01:00     return await func(*args, **kwargs)
2022-10-15T08:28:49.540823567+01:00   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/discovery.py", line 139, in async_start_pairing
2022-10-15T08:28:49.540845857+01:00     salt, pub_key = await self._async_start_pairing(alias)
2022-10-15T08:28:49.540866480+01:00   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/discovery.py", line 129, in _async_start_pairing
2022-10-15T08:28:49.540885515+01:00     return await drive_pairing_state_machine(
2022-10-15T08:28:49.540907757+01:00   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 258, in drive_pairing_state_machine
2022-10-15T08:28:49.540939534+01:00     decoded = await _pairing_char_write(client, char, iid, request)
2022-10-15T08:28:49.540965252+01:00   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 212, in _pairing_char_write
2022-10-15T08:28:49.540990925+01:00     data = await char_write(client, None, None, handle, iid, next_write)
2022-10-15T08:28:49.541019735+01:00   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 195, in char_write
2022-10-15T08:28:49.541053238+01:00     pdu_status, data = await ble_request(
2022-10-15T08:28:49.541085173+01:00   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 101, in ble_request
2022-10-15T08:28:49.541110826+01:00     return await _read_pdu(client, decryption_key, handle, tid)
2022-10-15T08:28:49.541145218+01:00   File "/usr/local/lib/python3.10/site-packages/aiohomekit/controller/ble/client.py", line 137, in _read_pdu
2022-10-15T08:28:49.541177065+01:00     data = await client.read_gatt_char(handle)
2022-10-15T08:28:49.541249032+01:00   File "/usr/local/lib/python3.10/site-packages/bleak/__init__.py", line 482, in read_gatt_char
2022-10-15T08:28:49.541286162+01:00     return await self._backend.read_gatt_char(char_specifier, **kwargs)
2022-10-15T08:28:49.541321127+01:00   File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 52, in _async_wrap_bluetooth_connected_operation
2022-10-15T08:28:49.541341373+01:00     return await func(self, *args, **kwargs)
2022-10-15T08:28:49.541363222+01:00   File "/usr/src/homeassistant/homeassistant/components/esphome/bluetooth/client.py", line 66, in _async_wrap_bluetooth_operation
2022-10-15T08:28:49.541460919+01:00     raise asyncio.TimeoutError(str(err)) from err
2022-10-15T08:28:49.541545085+01:00 asyncio.exceptions.TimeoutError: Timeout waiting for response for <class 'api_pb2.BluetoothGATTReadRequest'>
```

### Additional information

It works with normal BT adapter and BLUEZ stack.

Thank you!

**Comment by virtualm2000** [comment]
Fixed by increasing the channel interval to 2000ms.

esp32_ble_tracker:
  scan_parameters:
    interval: 2000ms
    window: 1000ms
    active: true

bluetooth_proxy:
  active: true
