### ISSUE TITLE
Pico W ADC NotImplementedError

### ISSUE THREAD

**Issue by si458** [esphome/issues#3795]
### The problem

im trying to read the ADC pin 4 to get the temperature from the Pico W directly but its not working
the sample python code is below
```
import machine
import utime
sensor_temp = machine.ADC(4)
conversion_factor = 3.3 / (65535)
while True:
    reading = sensor_temp.read_u16() * conversion_factor
    temperature = 27 - (reading - 0.706)/0.001721
    print(temperature)
    utime.sleep(2)
```

the output error is below
```
INFO Reading configuration /config/esphome/pico-w-home.yaml...
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 955, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 933, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
  File "/esphome/esphome/config.py", line 977, in read_config
    res = load_config(command_line_substitutions)
  File "/esphome/esphome/config.py", line 831, in load_config
    return _load_config(command_line_substitutions)
  File "/esphome/esphome/config.py", line 819, in _load_config
    result = validate_config(config, command_line_substitutions)
  File "/esphome/esphome/config.py", line 747, in validate_config
    result.run_validation_steps()
  File "/esphome/esphome/config.py", line 123, in run_validation_steps
    task.step.run(self)
  File "/esphome/esphome/config.py", line 489, in run
    validated = schema(input_conf)
  File "/esphome/esphome/voluptuous_schema.py", line 34, in __call__
    res = super().__call__(data)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/esphome/esphome/voluptuous_schema.py", line 34, in __call__
    res = super().__call__(data)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/esphome/esphome/voluptuous_schema.py", line 148, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/esphome/esphome/components/adc/sensor.py", line 120, in validate_adc_pin
    raise NotImplementedError
NotImplementedError
```

### Which version of ESPHome has the issue?

2022.11.0b6

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.11.2

### What platform are you using?

RP2040

### Board

Pico W

### Component causing the issue

adc

### Example YAML snippet

```yaml
esphome:
  name: pico-w-home
  compile_process_limit: 1
  on_boot:
    then:
      - output.turn_on: LED

rp2040:
  board: rpipicow
  framework:
    # Required until https://github.com/platformio/platform-raspberrypi/pull/36 is merged
    platform_version: https://github.com/maxgerhardt/platform-raspberrypi.git

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "PASSWORD123"

ota:
  password: "PASSWORD123"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot in case wifi connection fails
  ap:
    ssid: "Pico-W-Home Fallback Hotspot"
    password: "PASSWORD123"

sensor:
  - platform: uptime
    name: Uptime Sensor
    update_interval: 30s
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 30s
  - platform: adc
    pin: A4
    name: "Temperature"
    update_interval: 60s

output:
  # Built-in LED
  - platform: gpio
    id: LED
    pin:
      number: 32  # 25 for Pico (non-W)
      mode: output
```

**Comment by jesserockz** [comment]
Thanks @si458. I have added a [PR](https://github.com/esphome/esphome/pull/4040) and will release in 2022.11.1
