### ISSUE TITLE
H801 not working in ha core 2022.11.4

### ISSUE THREAD

**Issue by bjornmorsman** [esphome/issues#3851]
### The problem

Hello,

i have a h801 with a ledstrip connecten, when i upgrade ha cor from 2022.10.5 to 2022.11.4 the entity doesnt work anymore.

when i turn on or off the ledstrip i get an error, cant call service turn on.

https://community.home-assistant.io/t/h801-connection-failure-with-esphome/491730/7

### Which version of ESPHome has the issue?

2022.11.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2022.11.4

### What platform are you using?

ESP8266

### Board

H801

### Example YAML snippet

```yaml
https://esphome.io/cookbook/h801.html

I use the yaml from the esphome site.
```

### Anything in the logs that might be useful for us?

```txt
There are no errors in the esphome log, only errors at home assistant because the entity is not functioning correct
```

**Comment by Peixeiro** [comment]
I have the same problem. 
It works on first seconds when restart module, then stop working from HA.  However, via the EspHome webpage the module is fully functional, in the EspHome manager it always appears as available.

LOG: 
`Logger: homeassistant.components.websocket_api.http.connection
Source: components/esphome/light.py:252
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 07:57:45 (15 occurrences)
Last logged: 10:21:21

    [2644261880] Connection not done for h801-sala-estar @ 192.168.1.44!
    [2644027928] Connection not done for h801-sala-estar @ 192.168.1.44!
    [2644934368] Connection not done for h801-sala-estar @ 192.168.1.44!

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 208, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/light/__init__.py", line 570, in async_handle_light_on_service
    await light.async_turn_on(**filter_turn_on_params(light, params))
  File "/usr/src/homeassistant/homeassistant/components/esphome/light.py", line 252, in async_turn_on
    await self._client.light_command(**data)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 820, in light_command
    self._check_authenticated()
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 276, in _check_authenticated
    self._check_connected()
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 273, in _check_connected
    raise APIConnectionError(f"Connection not done for {self._log_name}!")
aioesphomeapi.core.APIConnectionError: Connection not done for h801-sala-estar @ 192.168.1.44!`
