### ISSUE TITLE
bluetooth proxy compile fatal errors

### ISSUE THREAD

**Issue by glbailey** [esphome/issues#4061]
### The problem

Created bluetooth proxy from https://esphome.github.io/bluetooth-proxies/ on a separate (from Home assistant) Linux Mint machine just fine. Device reports it was created with version 2022.9.4. Then adopted device with Home Assistant on a Linux Mint machine in a Virtual Box VM. When trying to install update to the bluetooth proxy device, a compile error is reported and compile is aborted. 
- ESPHome addon v 2022.12.3
- Home Assistant (OVA) running in Virtual Box on Linux Mint on Desktop PC.
    Home Assistant 2023.1.2
    Supervisor 2022.12.1
    Operating System 9.4
    Frontend 20230104.0 - latest 
- Virtual Box v 6.1.38_Ubuntu
- Linux Mint 20.3 Cinnamon
    Kernel 5.4.0-137

VM has 2 processors (out of 8) assigned and 4GB memory assigned. Peak processor use observed (happens during other ESPHome compiles) is 69% and peak mem usage is 35%. Disk space assigned 32GB and 58% usage reported by HA.
HA has been running for over 10 months (not a new install)

The 18th line of the log attached shows the fatal error. This is fully repeatable.

Log file excerpt of fatal error (full error log attached below):

-   Downloading pyparsing-2.3.1-py2.py3-none-any.whl (61 kB)
-   XXX lineno: 998, opcode: 172
-   ERROR: Exception:
-   Traceback (most recent call last):
-   File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 171, in _merge_into_criterion
-   crit = self.state.criteria[name]
-   KeyError: 'pyparsing'

### Which version of ESPHome has the issue?

2022.12.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.1.2

### What platform are you using?

ESP32-IDF

### Board

ESP32 DEVKIT V1

### Component causing the issue

compiler

### Example YAML snippet

```yaml
substitutions:
  name: esp32-bluetooth-proxy-a2f6e0
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32:
  board: esp32dev
  framework:
    type: esp-idf

api:
logger:
ota:
improv_serial:

# captive_portal:

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

button:
- platform: safe_mode
  name: Safe Mode Boot
  entity_category: diagnostic
```

### Anything in the logs that might be useful for us?

```txt
INFO Reading configuration /config/esphome/esp32-bluetooth-proxy-a2f6e0.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esp32-bluetooth-proxy-a2f6e0 (board: esp32dev; framework: espidf; platform: platformio/espressif32 @ 5.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40402.0 (4.4.2) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch3
Installing ESP-IDF's Python dependencies
Collecting future>=0.15.2
  Downloading future-0.18.3.tar.gz (840 kB)
Collecting pyparsing<2.4.0,>=2.0.3
  Downloading pyparsing-2.3.1-py2.py3-none-any.whl (61 kB)
XXX lineno: 998, opcode: 172
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'pyparsing'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 346, in run
    requirement_set = resolver.resolve(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/resolver.py", line 122, in resolve
    self._result = resolver.resolve(
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 453, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 318, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/resolvers.py", line 82, in from_requirement
    if not cands:
  File "/usr/share/python-wheels/resolvelib-0.5.4-py2.py3-none-any.whl/resolvelib/structs.py", line 124, in __bool__
    return bool(self._sequence)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 99, in __bool__
    return any(self)
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 239, in iter_index_candidates
    candidate = self._make_candidate_from_link(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/factory.py", line 167, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 296, in __init__
    super(LinkCandidate, self).__init__(
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 144, in __init__
    self.dist = self._prepare()
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 222, in _prepare
    dist = self._prepare_distribution()
  File "/usr/lib/python3/dist-packages/pip/_internal/resolution/resolvelib/candidates.py", line 307, in _prepare_distribution
    return self._factory.preparer.prepare_linked_requirement(
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 480, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 523, in _prepare_linked_requirement
    dist = _get_prepared_distribution(
  File "/usr/lib/python3/dist-packages/pip/_internal/operations/prepare.py", line 89, in _get_prepared_distribution
    return abstract_dist.get_pkg_resources_distribution()
  File "/usr/lib/python3/dist-packages/pip/_internal/distributions/wheel.py", line 31, in get_pkg_resources_distribution
    return pkg_resources_distribution_for_wheel(
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/wheel.py", line 64, in pkg_resources_distribution_for_wheel
    info_dir, _ = parse_wheel(wheel_zip, name)
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/wheel.py", line 104, in parse_wheel
    metadata = wheel_metadata(wheel_zip, info_dir)
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/wheel.py", line 173, in wheel_metadata
    wheel_contents = read_wheel_metadata_file(source, path)
  File "/usr/lib/python3/dist-packages/pip/_internal/utils/wheel.py", line 157, in read_wheel_metadata_file
    return source.read(path)
  File "/usr/lib/python3.9/zipfile.py", line 1464, in read
    return fp.read()
  File "/usr/lib/python3.9/zipfile.py", line 908, in read
    buf += self._read1(self.MAX_N)
  File "/usr/lib/python3.9/zipfile.py", line 998, in _read1
    data = self._decompressor.decompress(data, n)
SystemError: unknown opcode
*** Error 2
Reading CMake configuration...
-- Building ESP-IDF components for target esp32
-- Configuring incomplete, errors occurred!
See also "/data/esp32-bluetooth-proxy-a2f6e0/.pioenvs/esp32-bluetooth-proxy-a2f6e0/CMakeFiles/CMakeOutput.log".

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/build.cmake:454 (message):
  /usr/bin/python3: Error while finding module specification for
  'idf_component_manager.prepare_components' (ModuleNotFoundError: No module
  named 'idf_component_manager')

Call Stack (most recent call first):
  /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:384 (idf_build_process)
  CMakeLists.txt:3 (project)
```

### Additional information

My suspicion was that it had something to do with python as the documentation (for manual installs) states "Your distribution probably already has Python installed. Confirm that it is at least version 3.9"
This is a problem since Linux Mint (and Ubuntu) reportedly considers 3.8 to be the latest and updates to that are apparently discouraged but I do not know if this is correct or not. At any rate, both my HA system and my other linux mint laptop report python3 at 3.8.10. I don't know how to reconcile that with the manual install page info.

**Comment by glbailey** [comment]
UPDATE: after updating to ESPHOME 2022.12.5 and Home assistant 2023.1.7 the issue has now been eliminated. Compiles complete correctly.

**Comment by Stooovie** [comment]
Not here. ESPHome 2023.3.1 on HA 2023.3.6, unable to update BTproxy to anything beyond 2022.12.6

**Comment by ssieb** [comment]
@Stooovie, please stop commenting in random unrelated issues.
