### ISSUE TITLE
BEDJET: MQTT AUtodiscovery payload for `climate` entity raises exception

### ISSUE THREAD

**Issue by kquinsland** [esphome/issues#4173]
### The problem

I recently upgraded to the new 2023.02 release and flashed the ESP32 that i've been using to control my BedJet.

After the device rebooted, I noticed that I no longer had a `climate` entity in Home Assistant. 

I looked at the logs and saw this error being thrown:

> Exception in async_discover when dispatching 'mqtt_discovery_new_climate_mqtt': ({'current_temperature_topic': 'bedjet-controller/climate/bedjet_climate/current_temperature/state', 'mode_command_topic': 'bedjet-controller/climate/bedjet_climate/mode/command', 'mode_state_topic': 'bedjet-controller/climate/bedjet_climate/mode/state', 'modes': ['off', 'heat', 'fan_only', 'dry'], 'temperature_command_topic': 'bedjet-controller/climate/bedjet_climate/target_temperature/command', 'temperature_state_topic': 'bedjet-controller/climate/bedjet_climate/target_temperature/state', 'min_temp': 19, 'max_temp': 43, 'temp_step': 1, 'temperature_unit': 'C', 'preset_mode_command_topic': 'bedjet-controller/climate/bedjet_climate/preset/command', 'preset_mode_state_topic': 'bedjet-controller/climate/bedjet_climate/preset/state', 'presets': ['boost', 'EXT HT', 'M1', 'M2', 'M3'], 'action_topic': 'bedjet-controller/climate/bedjet_climate/action/state', 'fan_mode_command_topic': 'bedjet-controller/climate/bedjet_climate/fan_mode/command', 'fan_mode_state_topic': 'bedjet-controller/climate/bedjet_climate/fan_mode/state', 'fan_modes': ['10%', '100%', '15%', '20%', '25%', '30%', '35%', '40%', '45%', '5%', '50%', '55%', '60%', '65%', '70%', '75%', '80%', '85%', '90%', '95%'], 'name': 'BedJet Climate', 'icon': 'mdi:car-turbocharger', 'availability_topic': 'bedjet-controller/status', 'unique_id': 'ESPclimatebedjet_climate', 'device': {'identifiers': '0123deadbeef', 'name': 'bedjet-controller', 'sw_version': 'esphome v2023.2.0 Feb 15 2023, 08:20:24', 'model': 'mhetesp32minikit', 'manufacturer': 'espressif'}, 'platform': 'mqtt'},) Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/components/mqtt/mixins.py", line 334, in async_discover config: DiscoveryInfoType = discovery_schema(discovery_payload) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 232, in __call__ return self._exec((Schema(val) for val in self.validators), v) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec raise e if self.msg is None else AllInvalid(self.msg, path=path) File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 351, in _exec v = func(v) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable return schema(data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__ return self._compiled([], data) File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 592, in validate_dict raise er.MultipleInvalid(errors) voluptuous.error.MultipleInvalid: some but not all values in the same group of inclusion 'preset_modes' @ data[<preset_modes>] 

### Which version of ESPHome has the issue?

2023.02

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

Home Assistant 2023.2.1

### What platform are you using?

ESP32

### Component causing the issue

bedjet

### Anything in the logs that might be useful for us?

Here is the MQTT payload from the error above:

```json

{'current_temperature_topic': 'bedjet-controller/climate/bedjet_climate/current_temperature/state', 'mode_command_topic': 'bedjet-controller/climate/bedjet_climate/mode/command', 'mode_state_topic': 'bedjet-controller/climate/bedjet_climate/mode/state', 'modes': ['off', 'heat', 'fan_only', 'dry'], 'temperature_command_topic': 'bedjet-controller/climate/bedjet_climate/target_temperature/command', 'temperature_state_topic': 'bedjet-controller/climate/bedjet_climate/target_temperature/state', 'min_temp': 19, 'max_temp': 43, 'temp_step': 1, 'temperature_unit': 'C', 'preset_mode_command_topic': 'bedjet-controller/climate/bedjet_climate/preset/command', 'preset_mode_state_topic': 'bedjet-controller/climate/bedjet_climate/preset/state', 'presets': ['boost', 'EXT HT', 'M1', 'M2', 'M3'], 'action_topic': 'bedjet-controller/climate/bedjet_climate/action/state', 'fan_mode_command_topic': 'bedjet-controller/climate/bedjet_climate/fan_mode/command', 'fan_mode_state_topic': 'bedjet-controller/climate/bedjet_climate/fan_mode/state', 'fan_modes': ['10%', '100%', '15%', '20%', '25%', '30%', '35%', '40%', '45%', '5%', '50%', '55%', '60%', '65%', '70%', '75%', '80%', '85%', '90%', '95%'], 'name': 'BedJet Climate', 'icon': 'mdi:car-turbocharger', 'availability_topic': 'bedjet-controller/status', 'unique_id': 'ESPclimatebedjet_climate', 'device': {'identifiers': '0123deadbeef', 'name': 'bedjet-controller', 'sw_version': 'esphome v2023.2.0 Feb 15 2023, 08:20:24', 'model': 'mhetesp32minikit', 'manufacturer': 'espressif'}
```

And here's the MQTT payload from the `2022.12.8` release that does work:

```json
{"curr_temp_t":"bedjet-controller/climate/bedjet_climate/current_temperature/state","mode_cmd_t":"bedjet-controller/climate/bedjet_climate/mode/command","mode_stat_t":"bedjet-controller/climate/bedjet_climate/mode/state","modes":["off","heat","fan_only","dry"],"temp_cmd_t":"bedjet-controller/climate/bedjet_climate/target_temperature/command","temp_stat_t":"bedjet-controller/climate/bedjet_climate/target_temperature/state","min_temp":19,"max_temp":43,"temp_step":1,"temp_unit":"C","act_t":"bedjet-controller/climate/bedjet_climate/action/state","fan_mode_cmd_t":"bedjet-controller/climate/bedjet_climate/fan_mode/command","fan_mode_stat_t":"bedjet-controller/climate/bedjet_climate/fan_mode/state","fan_modes":["10%","100%","15%","20%","25%","30%","35%","40%","45%","5%","50%","55%","60%","65%","70%","75%","80%","85%","90%","95%"],"name":"BedJet Climate","ic":"mdi:car-turbocharger","avty_t":"bedjet-controller/status","uniq_id":"ESPclimatebedjet_climate","dev":{"ids":"0123deadbeef","name":"bedjet-controller","sw":"esphome v2022.12.8 Feb 15 2023, 09:04:04","mdl":"mhetesp32minikit","mf":"espressif"}}
```

Looking here: https://github.com/home-assistant/core/blob/dev/homeassistant/components/mqtt/climate.py#L332

It's not immediately clear to me what the issue is other than `preset_modes` != `presets`.

**Comment by kquinsland** [comment]
This appears to be fixed, now. https://github.com/esphome/esphome/pull/4451
