### ISSUE TITLE
[Dashboard] PipeIOStream  is not Supported on Windows

### ISSUE THREAD

**Issue by mfbehrens** [esphome/issues#4280]
### The problem

When running the dashboard on Windows and editing a file an error message gets thrown (see below).

### Which version of ESPHome has the issue?

2023.2.4

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP8266

### Board

d1_mini_lite

### Component causing the issue

dashboard

### Example YAML snippet

```
2023-03-06 12:43:24,860 ERROR Uncaught exception GET /ace (127.0.0.1)
HTTPServerRequest(protocol='http', host='localhost:6052', method='GET', uri='/ace', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "C:\Users\mfbeh\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\websocket.py", line 635, in _run_callback
    result = callback(*args, **kwargs)
  File "C:\Users\mfbeh\AppData\Local\Programs\Python\Python310\lib\site-packages\esphome\dashboard\dashboard.py", line 138, in decorator
    return func(self, *args, **kwargs)
  File "C:\Users\mfbeh\AppData\Local\Programs\Python\Python310\lib\site-packages\esphome\dashboard\dashboard.py", line 212, in on_message
    handlers[type_](self, json_message)
  File "C:\Users\mfbeh\AppData\Local\Programs\Python\Python310\lib\site-packages\esphome\dashboard\dashboard.py", line 221, in handle_spawn
    self._proc = tornado.process.Subprocess(
  File "C:\Users\mfbeh\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\process.py", line 226, in __init__
    self.stdin = PipeIOStream(in_w)
  File "C:\Users\mfbeh\AppData\Local\Programs\Python\Python310\lib\site-packages\tornado\iostream.py", line 1640, in __init__
    raise AssertionError("PipeIOStream is not supported on Windows")
AssertionError: PipeIOStream is not supported on Windows
```

### Additional information

I am not sure if the dashboard is meant to be used to be used on Windows, however an error message when starting the dashboard "esphome dashboard is not compatible with windows" would be nice.

Thanks for developing and maintaining esphome!

**Comment by ssieb** [comment]
This is known and kind of documented. https://esphome.io/guides/getting_started_command_line.html#bonus-esphome-dashboard

**Comment by Henri-J-Norden** [comment]
I ran into the same issue - while it may be "documented", it's not at all obvious that the error message `PipeIOStream is not supported on Windows` actually means "ESPHome Dashboard does not support Windows". This issue is the first result when googling the error, because the error message is not even mentioned in the documentation.

**Comment by stefan-sherwood** [comment]
For what it's worth, ESPHome dashboard works perfectly -- including "Update All" -- in Windows in WSL.

**Comment by NODeeJay** [comment]
> Windows in WSL.

Do you mind roughly sharing your steps? You install python and pip and the esphome venv etc. all in WSL or is anything "installed" under Windows?

**Comment by stefan-sherwood** [comment]
Python is installed by default in most Linux distributions. Since WSL supports many flavors of Linux, you have to Google how to install or upgrade Python in then one you're using.

```
pip install esphome
python -m esphome dashboard config/
```
(note: config is the directory where I store my configuration files. It may be different for you)
