### ISSUE TITLE
Wizard crashes if OTA password contains char > ascii 128

### ISSUE THREAD

**Issue by nicop4** [esphome/issues#431]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

pip command line, MacOS, python 2.7.13

**ESP (ESP32/ESP8266, Board/Sonoff):**

Was for ESP8266, but might affect any

**Affected component:**

Wizard

**Description of problem:**
Wizard asked for OTA password, I gave the value `lo5ù§RyeF3`. I think the character `ù` caused the crash but `§` might also.

**Problem-relevant YAML-configuration entries:**
no yaml yet

**Traceback (if applicable):**

```
============= STEP 4 =============
       ____ _______
      / __ \__   __|/\\
     | |  | | | |  /  \\
     | |  | | | | / /\ \\
     | |__| | | |/ ____ \\
      \____/  |_/_/    \_\\

===================================
Almost there! ESPHome can automatically upload custom firmwares over WiFi (over the air) and integrates into Home Assistant with a native API.
This can be insecure if you do not trust the WiFi network. Do you want to set a password for connecting to this ESP?

Press ENTER for no password
(password): lo5ù§RyeF3
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/esphome/__main__.py", line 483, in main
    return run_esphome(sys.argv)
  File "/usr/local/lib/python2.7/site-packages/esphome/__main__.py", line 459, in run_esphome
    return PRE_CONFIG_ACTIONS[args.command](args)
  File "/usr/local/lib/python2.7/site-packages/esphome/__main__.py", line 253, in command_wizard
    return wizard.wizard(args.configuration)
  File "/usr/local/lib/python2.7/site-packages/esphome/wizard.py", line 268, in wizard
    ssid=ssid, psk=psk, password=password)
  File "/usr/local/lib/python2.7/site-packages/esphome/wizard.py", line 91, in wizard_write
    f_handle.write(wizard_file(**kwargs))
  File "/usr/local/lib/python2.7/site-packages/esphome/wizard.py", line 71, in wizard_file
    config += u'  password: "{0}"\n\nota:\n  password: "{0}"\n'.format(kwargs['password'])
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3: ordinal not in range(128)
```

**Additional information and things you've tried:**

**Comment by OttoWinter** [comment]
Fixed in dev
