### ISSUE TITLE
Documentation for using HEX codes to define colors in Display component is wrong

### ISSUE THREAD

**Issue by mcsquared88** [esphome/issues#4354]
### The problem

The example code at https://esphome.io/components/display/index.html is as follows:
```
color:
  - id: my_light_red
    hex: FF3340
```

I couldn't get that to work.

The Github discussion at https://github.com/esphome/esphome/pull/4493 gives the following as example code:
```
color:
  - id: test
    hex: '112233'
```

That did work. 

So it seems the hex value must be enclosed in parentheses, and the documentation needs to be updated to reflect that.

I've attached the error I got at compile when not using parentheses. It wasn't that helpful.

### Which version of ESPHome has the issue?

2023.3.1

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

N/A

### What platform are you using?

ESP32

### Anything in the logs that might be useful for us?

```txt
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
  File "/esphome/esphome/__main__.py", line 963, in main
    return run_esphome(sys.argv)
  File "/esphome/esphome/__main__.py", line 941, in run_esphome
    config = read_config(dict(args.substitution) if args.substitution else {})
  File "/esphome/esphome/config.py", line 986, in read_config
    res = load_config(command_line_substitutions)
  File "/esphome/esphome/config.py", line 840, in load_config
    return _load_config(command_line_substitutions)
  File "/esphome/esphome/config.py", line 828, in _load_config
    result = validate_config(config, command_line_substitutions)
  File "/esphome/esphome/config.py", line 756, in validate_config
    result.run_validation_steps()
  File "/esphome/esphome/config.py", line 125, in run_validation_steps
    task.step.run(self)
  File "/esphome/esphome/config.py", line 507, in run
    validated = schema(self.conf)
  File "/esphome/esphome/voluptuous_schema.py", line 34, in __call__
    res = super().__call__(data)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/validators.py", line 274, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/esphome/esphome/voluptuous_schema.py", line 34, in __call__
    res = super().__call__(data)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/esphome/esphome/voluptuous_schema.py", line 148, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.9/dist-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
  File "/esphome/esphome/components/color/__init__.py", line 17, in hex_color
    if len(value) != 6:
TypeError: object of type 'EInt' has no len()
```

**Comment by pkejval** [comment]
Exactly! I was solving this right now. Documentation says:
```color:
  - id: my_light_red
    hex: FF3340
```
It indeed works. However when you want to use multiple values you have to enclose hex values into quote marks or it won't compile with error @mcsquared88 posted above.

This is right syntax:
```
color:
  - id: color_light_green
    hex: '00FF00'
  
  - id: color_green
    hex: '007500'
```

Another issue in documentation is that they use color without id() parenthes so code in documentation is invalid:
`it.graph(10, 20, id(multi_temperature_graph), my_yellow);`
should be `it.graph(10, 20, id(multi_temperature_graph), id(my_yellow));`
