### ISSUE TITLE
Connection error occurred: Invalid protobuf message

### ISSUE THREAD

**Issue by viotemp1** [esphome/issues#4461]
### The problem

I see a lot of error like this and disconnections from HA lately (not sure when it started).

`Apr 26 15:33:53 a0d7b954-ssh hass: 2023-04-26 15:33:53.144 WARNING (MainThread) [aioesphomeapi.connection] my_esp32_utils @ 10.0.0.250: Connection error occurred: Invalid protobuf message: type=12 data=b'\n\x15my_esp32_utils_status\x15d\x8c\x1e]\x1a\x15my_esp32_utils_Status"0my_esp32_utilsbinary_sensormy_esp32_utils_status*\x0cconn\x01c\xff\x0f\xff\x0fty0\x01H\x02': 'utf-8' codec can't decode byte 0xff in position 6: 'utf-8' codec can't decode byte 0xff in position 6: invalid start byte in field: ListEntitiesBinarySensorResponse.device_class
`

### Which version of ESPHome has the issue?

2023.4.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.6

### What platform are you using?

esp32/arduino

### Board

m5stack-core2

### Component causing the issue

aioesphomeapi.connection

### Anything in the logs that might be useful for us?

```txt
Apr 26 15:33:53 a0d7b954-ssh hass: 2023-04-26 15:33:53.144 WARNING (MainThread) [aioesphomeapi.connection] my_esp32_utils @ 10.0.0.250: Connection error occurred: Invalid protobuf message: type=12 data=b'\n\x15my_esp32_utils_status\x15d\x8c\x1e]\x1a\x15my_esp32_utils_Status"0my_esp32_utilsbinary_sensormy_esp32_utils_status*\x0cconn\x01c\xff\x0f\xff\x0fty0\x01H\x02': 'utf-8' codec can't decode byte 0xff in position 6: 'utf-8' codec can't decode byte 0xff in position 6: invalid start byte in field: ListEntitiesBinarySensorResponse.device_class
Apr 26 15:33:53 a0d7b954-ssh hass: Traceback (most recent call last):
Apr 26 15:33:53 a0d7b954-ssh hass:  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 876, in _read_ready__data_received
Apr 26 15:33:53 a0d7b954-ssh hass:    self._protocol.data_received(data)
Apr 26 15:33:53 a0d7b954-ssh hass:  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/_frame_helper.py", line 194, in data_received
Apr 26 15:33:53 a0d7b954-ssh hass:    self._callback_packet(msg_type_int, bytes(packet_data))
Apr 26 15:33:53 a0d7b954-ssh hass:  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/_frame_helper.py", line 109, in _callback_packet
Apr 26 15:33:53 a0d7b954-ssh hass:    self._on_pkt(Packet(type_, data))
Apr 26 15:33:53 a0d7b954-ssh hass:  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 661, in _process_packet
Apr 26 15:33:53 a0d7b954-ssh hass:    msg.MergeFromString(pkt.data)
Apr 26 15:33:53 a0d7b954-ssh hass:  File "/usr/local/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 1128, in MergeFromString
Apr 26 15:33:53 a0d7b954-ssh hass:    if self._InternalParse(serialized, 0, length) != length:
Apr 26 15:33:53 a0d7b954-ssh hass:  File "/usr/local/lib/python3.10/site-packages/google/protobuf/internal/python_message.py", line 1195, in InternalParse
Apr 26 15:33:53 a0d7b954-ssh hass:    pos = field_decoder(buffer, new_pos, end, self, field_dict)
Apr 26 15:33:53 a0d7b954-ssh hass:  File "/usr/local/lib/python3.10/site-packages/google/protobuf/internal/decoder.py", line 591, in DecodeField
Apr 26 15:33:53 a0d7b954-ssh hass:    field_dict[key] = _ConvertToUnicode(buffer[pos:new_pos])
Apr 26 15:33:53 a0d7b954-ssh hass:  File "/usr/local/lib/python3.10/site-packages/google/protobuf/internal/decoder.py", line 553, in _ConvertToUnicode
Apr 26 15:33:53 a0d7b954-ssh hass:    value = str(byte_str, 'utf-8')
Apr 26 15:33:53 a0d7b954-ssh hass: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 6: 'utf-8' codec can't decode byte 0xff in position 6: invalid start byte in field: ListEntitiesBinarySensorResponse.device_class
```

**Comment by buzurk26** [comment]
Im getting this too with my sonoff rf bridge, i have rf buttons to trigger things and get api errors and Connection error occurred: Invalid protobuf message in HA logs
