### ISSUE TITLE
Issue upgrading esphome addon - home assistant 

### ISSUE THREAD

**Issue by jjgit1234** [esphome/issues#4467]
### The problem

Getting below error upgrading esphome on home assistant raspberry pi 2
Please fix url

Can't install ghcr.io/esphome/esphome-hassio:2023.4.2: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.4.2/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.4.2")

### Which version of ESPHome has the issue?

2023.4.2

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.4.6

### What platform are you using?

ESP8266

### Board

Nodemcu

### Component causing the issue

Can't install ghcr.io/esphome/esphome-hassio:2023.4.2: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.4.2/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.4.2")

**Comment by rafawallaa** [comment]
Same problem with me, same exact error

**Comment by desperadoNL** [comment]
Same issue here, exact same error.

**Comment by bhyatyab** [comment]
Issue still not resolved 8n esphome 2023.4.3

**Comment by bhyatyab** [comment]
Can't install ghcr.io/esphome/esphome-hassio:2023.4.3: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.4.3/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.4.3")

**Comment by bhyatyab** [comment]
Any update? The last version installed with no error is 2023.4.0

**Comment by willie-breedt** [comment]
I've been having the same issue for a few versions. Uninstalling, and Reinstalling ESPHome sorts out the issue - but it would be preferred to simply use the update feature:

Logger: homeassistant.components.hassio
Source: components/hassio/websocket_api.py:125
Integration: Home Assistant Supervisor ([documentation](https://www.home-assistant.io/integrations/hassio), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+hassio%22))
First occurred: May 17, 2023 at 9:54:34 AM (3 occurrences)
Last logged: 7:53:33 AM

Failed to to call /store/addons/5c53de3b_esphome/update - Can't install ghcr.io/esphome/esphome-hassio:2023.5.0: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.5.0/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.5.0")
Failed to to call /store/addons/5c53de3b_esphome/update - Can't install ghcr.io/esphome/esphome-hassio:2023.5.1: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.5.1/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.5.1")

**Comment by willie-breedt** [comment]
This is still happening when attempting to upgrade to newer versions of ESPHome. The workaround is to uninstall, reinstall and then upgrade devices - but this isn't ideal.

Full error from Errog Log:
Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/update.py:169
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: September 27, 2023 at 9:28:03 AM (2 occurrences)
Last logged: 8:50:08 AM

[1465008424] Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.9.0: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.9.0/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.9.0")
[1488439016] Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.9.1: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.9.1/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.9.1")
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 167, in async_install
    await async_update_addon(self.hass, slug=self._addon_slug, backup=backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/handler.py", line 53, in _wrapper
    raise HassioAPIError(data["message"])
homeassistant.components.hassio.handler.HassioAPIError: Can't install ghcr.io/esphome/esphome-hassio:2023.9.0: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.9.0/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.9.0")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 227, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1969, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2006, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 235, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 870, in entity_service_call
    response_data = await _handle_entity_call(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 942, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 157, in async_install
    await entity.async_install_with_progress(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/update/__init__.py", line 428, in async_install_with_progress
    await self.async_install(version, backup)
  File "/usr/src/homeassistant/homeassistant/components/hassio/update.py", line 169, in async_install
    raise HomeAssistantError(f"Error updating {self.title}: {err}") from err
homeassistant.exceptions.HomeAssistantError: Error updating ESPHome: Can't install ghcr.io/esphome/esphome-hassio:2023.9.0: 404 Client Error for http+docker://localhost/v1.42/images/ghcr.io/esphome/esphome-hassio:2023.9.0/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.9.0")

**Comment by ssummer** [comment]
This has been happening for me for every update for the last 6 months or so. It seems to be unable to pull the image and is getting a 404 when it tries. However a workaround is to SSH into HA and issue the docker pull command an d once that has completed it is possible to install the update.
My HA runs on a raspberry pi.
If the error is with another component can anyone suggest where to report this as this is a long running issue affecting a lot of people. I have seen it reported elsewhere also with no resolution. I looked through the release notes and changes around the time it stopped working but couldn't see anything.

It is strange that it works if the image has already been pulled, perhaps it checks if image is already present before pulling? In which case does it mean the pull URL is being formed incorrectly?

**Comment by ssummer** [comment]
I am using HAOS on a dedicated raspberry pi and I ssh directly into the OS which provides access to the root OS and provides docker cli. Other ssh methods may only ssh into a particular container. However some add-ins apparently do also allow you to ssh into the host os too.
But I ssh in directly from another machine, SSH setup details are here:

https://developers.home-assistant.io/docs/operating-system/debugging#ssh-access-to-the-host

"SSH access through port 22222"

Regards,

Stephen

**Comment by TorAllex** [comment]
same error
Can't install ghcr.io/esphome/esphome-hassio:2023.10.1: 404 Client Error for http+docker://localhost/v1.43/images/ghcr.io/esphome/esphome-hassio:2023.10.1/json: Not Found ("No such image: ghcr.io/esphome/esphome-hassio:2023.10.1")

**Comment by eerootsus** [comment]
@ssummer 

Thanks for this! It worked. Not the easiest of workarounds, but definitely better than uninstalling and reinstalling the add-on.

So once I could SSH into the host I issued the following command:
`docker pull ghcr.io/esphome/esphome-hassio:2023.10.1`

**Comment by ssummer** [comment]
Looks like this is now (finally) fixed, I just tried upgrading to ESPHome 2023.12.6 and it worked!
