### ISSUE TITLE
updating to latest esphome throws error

### ISSUE THREAD

**Issue by ljmerza** [esphome/issues#4538]
### The problem

updating to latest esphome throws error

### Which version of ESPHome has the issue?

2023.5.3

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

esp32

### Anything in the logs that might be useful for us?

```txt
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
CMake Error at /config/.esphome/platformio/packages/framework-espidf/tools/cmake/component.cmake:237 (message):
  Traceback (most recent call last):

    File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/local/lib/python3.9/dist-packages/idf_component_manager/prepare_components/__main__.py", line 4, in <module>
      from .prepare import main
    File "/usr/local/lib/python3.9/dist-packages/idf_component_manager/prepare_components/prepare.py", line 18, in <module>
      from ..core import ComponentManager
    File "/usr/local/lib/python3.9/dist-packages/idf_component_manager/core.py", line 28, in <module>
      from idf_component_tools.manifest import (
    File "/usr/local/lib/python3.9/dist-packages/idf_component_tools/manifest/__init__.py", line 9, in <module>
      from .solved_component import SolvedComponent
    File "/usr/local/lib/python3.9/dist-packages/idf_component_tools/manifest/solved_component.py", line 9, in <module>
      from ..sources.base import BaseSource
    File "/usr/local/lib/python3.9/dist-packages/idf_component_tools/sources/__init__.py", line 8, in <module>
      from .web_service import WebServiceSource
    File "/usr/local/lib/python3.9/dist-packages/idf_component_tools/sources/web_service.py", line 14, in <module>
      import idf_component_tools.api_client as api_client
    File "/usr/local/lib/python3.9/dist-packages/idf_component_tools/api_client.py", line 16, in <module>
      from requests_toolbelt import MultipartEncoder, MultipartEncoderMonitor
    File "/usr/local/lib/python3.9/dist-packages/requests_toolbelt/__init__.py", line 18, in <module>
      from .streaming_iterator import StreamingIterator

  ModuleNotFoundError: No module named 'requests_toolbelt.streaming_iterator'

Call Stack (most recent call first):
  /config/.esphome/platformio/packages/framework-espidf/tools/cmake/build.cmake:486 (__component_get_requirements)
  /config/.esphome/platformio/packages/framework-espidf/tools/cmake/project.cmake:384 (idf_build_process)
  CMakeLists.txt:3 (project)
```
```


### Additional information

_No response_

**Comment by ssieb** [comment]
Try rebuilding your container.
