### ISSUE TITLE
TSL2591 calculated_lux "inf" instead of 0

### ISSUE THREAD

**Issue by wtv1211** [esphome/issues#4544]
### The problem

I've got a TSL2591 on a nodemcuv2 board  reading solar iradiation. At night, calculated_lux is either 0 or "inf". When "inf" is present, home assistant v 2023.5.x closes connection to the entire node.

### Which version of ESPHome has the issue?

2023.5.3

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.x

### What platform are you using?

ESP8266

### Board

nodemcuv2

### Component causing the issue

TSL2591 calculated_lux

### Example YAML snippet

```yaml
sensor:
   - platform: tsl2591
     name: "Luminita_TSL2591"
     id: "my_tls2591"
     address: 0x29
     gain: 1x
     update_interval: 0.5s #0.025
     power_save_mode: true
     device_factor: 53
     glass_attenuation_factor: 19.9
     integration_time: 100ms
    
     calculated_lux:
              id: i_lux
              name: "Luminita Lux"
              unit_of_measurement: "lx"
              accuracy_decimals: 0
              filters:
                   - or:
                      - throttle: 30s
                      - delta: 1000
```

### Anything in the logs that might be useful for us?

```txt
Logger: homeassistant
Source: components/sensor/__init__.py:583
First occurred: 28 mai 2023 la 21:15:57 (249 occurrences)
Last logged: 28 mai 2023 la 21:23:13

Error doing job: Fatal error: protocol.data_received() call failed.
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 579, in state
    numerical_value = int(value)
ValueError: invalid literal for int() with base 10: 'inf'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/selector_events.py", line 876, in _read_ready__data_received
    self._protocol.data_received(data)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/_frame_helper.py", line 182, in data_received
    self._callback_packet(msg_type_int, bytes(packet_data))
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/_frame_helper.py", line 102, in _callback_packet
    self._on_pkt(type_, data)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/connection.py", line 690, in _process_packet
    handler(msg)
  File "/usr/local/lib/python3.10/site-packages/aioesphomeapi/client.py", line 395, in on_msg
    on_state(cls.from_pb(msg))
  File "/usr/src/homeassistant/homeassistant/components/esphome/entry_data.py", line 270, in async_update_state
    self.state_subscriptions[subscription_key]()
  File "/usr/src/homeassistant/homeassistant/components/esphome/__init__.py", line 807, in _on_state_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 585, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 649, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 591, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 583, in state
    raise ValueError(
ValueError: Sensor sensor.luminita_lux has device class illuminance, state class measurement unit lx and suggested precision None thus indicating it has a numeric value; however, it has the non-numeric value: inf (<class 'str'>)
```

**Comment by samuelolteanu** [comment]
Issue still present. Happens with gain: 1 in not really complete dark.
