### ISSUE TITLE
Ignored Exception after upload (on one device only)

### ISSUE THREAD

**Issue by colmbuckley** [esphome/issues#5255]
### The problem

On one device (only; out of a few dozen), `esphome upload` is throwing an exception *after* a successful upload. It doesn't seem to affect anything - the device receives the new configuration okay, but `esphome` does complain.

I don't think there's anything unusual in this device's configuration; it uses similar components and configuration to every other device on my network; in particular I have several other identical controllers which don't exhibit this issue.

### Which version of ESPHome has the issue?

2023.12.0

### What type of installation are you using?

pip

### Which version of Home Assistant has the issue?

2023.12.3

### What platform are you using?

ESP32

### Board

esp32dev [Rocket Controller Astra BT4A4AL)

### Component causing the issue

N/A

### Anything in the logs that might be useful for us?

```txt
% esphome upload lightswitch-office.yaml 
INFO ESPHome 2023.12.0
INFO Reading configuration lightswitch-office.yaml...
INFO Resolving IP address of lightswitch-office.local
INFO  -> 192.168.107.226
INFO Uploading .esphome/build/lightswitch-office/.pioenvs/lightswitch-office/firmware.bin (774768 bytes)
Uploading: [============================================================] 100% Done...

INFO Upload took 2.72 seconds, waiting for result...
INFO OTA successful
INFO Successfully uploaded program.
Exception ignored in: <function BaseEventLoop.__del__ at 0x152d40d99440>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/base_events.py", line 694, in __del__
    self.close()
  File "/usr/lib/python3.11/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 91, in close
    self._close_self_pipe()
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 98, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
  File "/usr/lib/python3.11/asyncio/selector_events.py", line 281, in _remove_reader
    key = self._selector.get_key(fd)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/selectors.py", line 190, in get_key
    return mapping[fileobj]
           ~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.11/selectors.py", line 71, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/selectors.py", line 225, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
```
```


### Additional information

_No response_

**Comment by token47** [comment]
I'm seeing the same issue in one of my devoces. Upload is fine but I see that message at the end.

Not sure if this is related, but this specific device has "baund_rate=0" on the logger component (so it won't try to use the UART since GPIO pins are being used for something else). No other device I have with that setting, so they might be related.

As you can see, this error message appears AFTER it concludes that it should not start the logs.

```
INFO Successfully uploaded program.
INFO UART logging is disabled (baud_rate=0). Not starting UART logs.
Exception ignored in: <function BaseEventLoop.__del__ at 0x7f1e348abe20>
Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/base_events.py", line 690, in __del__
    self.close()
  File "/usr/lib/python3.10/asyncio/unix_events.py", line 68, in close
    super().close()
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 87, in close
    self._close_self_pipe()
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 94, in _close_self_pipe
    self._remove_reader(self._ssock.fileno())
  File "/usr/lib/python3.10/asyncio/selector_events.py", line 272, in _remove_reader
    key = self._selector.get_key(fd)
  File "/usr/lib/python3.10/selectors.py", line 191, in get_key
    return mapping[fileobj]
  File "/usr/lib/python3.10/selectors.py", line 72, in __getitem__
    fd = self._selector._fileobj_lookup(fileobj)
  File "/usr/lib/python3.10/selectors.py", line 226, in _fileobj_lookup
    return _fileobj_to_fd(fileobj)
  File "/usr/lib/python3.10/selectors.py", line 42, in _fileobj_to_fd
    raise ValueError("Invalid file descriptor: {}".format(fd))
ValueError: Invalid file descriptor: -1
```
