### ISSUE TITLE
ESPHome container can't run properly after docker pull

### ISSUE THREAD

**Issue by zivarzi** [esphome/issues#5424]
### The problem

When installing the docker container, I receive the following message from the docker container logs and the esphome dashboard is not showing.

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

Docker

### Which version of Home Assistant has the issue?

2024.1.3

### What platform are you using?

ESP32

### Board

lolin D32

### Anything in the logs that might be useful for us?

```txt
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 33, in <module>
    sys.exit(load_entry_point('esphome', 'console_scripts', 'esphome')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/esphome", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/esphome/esphome/__main__.py", line 4, in <module>
    import logging
  File "/usr/lib/python3.11/logging/__init__.py", line 58, in <module>
    _startTime = time.time()
                 ^^^^^^^^^^^
PermissionError: [Errno 1] Operation not permitted
```

**Comment by ssieb** [comment]
This is a docker problem.
https://stackoverflow.com/questions/70195968/dockerfile-raspberry-pi-python-pip-install-permissionerror-errno-1-operation
