### ISSUE TITLE
Unable to wirelessly access to log

### ISSUE THREAD

**Issue by dudu7731** [esphome/issues#5457]
### The problem

When i try to access logs wirelesly i have following issue 
```
INFO Successfully connected to detecteur-bureau @ 10.0.50.11 in 0.046s
ERROR Exception in callback APINoiseFrameHelper.connection_made(<_SelectorSoc...e, bufsize=0>>)
handle: <Handle APINoiseFrameHelper.connection_made(<_SelectorSoc...e, bufsize=0>>)>
Traceback (most recent call last):
  File "/usr/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "aioesphomeapi/_frame_helper/noise.py", line 134, in aioesphomeapi._frame_helper.noise.APINoiseFrameHelper.connection_made
  File "aioesphomeapi/_frame_helper/noise.py", line 175, in aioesphomeapi._frame_helper.noise.APINoiseFrameHelper._send_hello_handshake
  File "/opt/esphome/lib/python3.11/site-packages/noise/connection.py", line 110, in write_message
    result = self.noise_protocol.handshake_state.write_message(payload, buffer)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/esphome/lib/python3.11/site-packages/noise/state.py", line 339, in write_message
    self.symmetric_state.mix_key_and_hash(self.noise_protocol.psks.pop(0))
  File "/opt/esphome/lib/python3.11/site-packages/noise/state.py", line 159, in mix_key_and_hash
    self.cipher_state.initialize_key(temp_k)
  File "/opt/esphome/lib/python3.11/site-packages/noise/state.py", line 29, in initialize_key
    self.cipher.initialize(key)
  File "/opt/esphome/lib/python3.11/site-packages/noise/functions/cipher.py", line 27, in initialize
    self.cipher = self.klass(key)
                  ^^^^^^^^^^^^^^^
  File "src/chacha20poly1305_reuseable/__init__.py", line 82, in chacha20poly1305_reuseable.ChaCha20Poly1305Reusable.__init__
  File "/opt/esphome/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 572, in aead_cipher_supported
    return aead._aead_cipher_supported(self, cipher)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/esphome/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/aead.py", line 22, in _aead_cipher_supported
    cipher_name = _evp_cipher_cipher_name(cipher)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/esphome/lib/python3.11/site-packages/cryptography/hazmat/backends/openssl/aead.py", line 66, in _evp_cipher_cipher_name
    assert isinstance(cipher, AESGCM)
AssertionError
```

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

pip

### What platform are you using?

ESP32

### Board

any

### Component causing the issue

any

### Anything in the logs that might be useful for us?

```txt
on the device : 	
[api.connection:092]	
: Socket operation failed: CONNECTION_CLOSED errno=128
```

### Additional information

My installation : 
```
(esphome) root@esphome:~# pip install -U esphome
Requirement already satisfied: esphome in /opt/esphome/lib/python3.11/site-packages (2023.12.9)
Requirement already satisfied: voluptuous==0.14.1 in /opt/esphome/lib/python3.11/site-packages (from esphome) (0.14.1)
Requirement already satisfied: PyYAML==6.0.1 in /opt/esphome/lib/python3.11/site-packages (from esphome) (6.0.1)
Requirement already satisfied: paho-mqtt==1.6.1 in /opt/esphome/lib/python3.11/site-packages (from esphome) (1.6.1)
Requirement already satisfied: colorama==0.4.6 in /opt/esphome/lib/python3.11/site-packages (from esphome) (0.4.6)
Requirement already satisfied: tornado==6.4 in /opt/esphome/lib/python3.11/site-packages (from esphome) (6.4)
Requirement already satisfied: tzlocal==5.2 in /opt/esphome/lib/python3.11/site-packages (from esphome) (5.2)
Requirement already satisfied: tzdata>=2021.1 in /opt/esphome/lib/python3.11/site-packages (from esphome) (2023.4)
Requirement already satisfied: pyserial==3.5 in /opt/esphome/lib/python3.11/site-packages (from esphome) (3.5)
Requirement already satisfied: platformio==6.1.11 in /opt/esphome/lib/python3.11/site-packages (from esphome) (6.1.11)
Requirement already satisfied: esptool==4.6.2 in /opt/esphome/lib/python3.11/site-packages (from esphome) (4.6.2)
Requirement already satisfied: click==8.1.7 in /opt/esphome/lib/python3.11/site-packages (from esphome) (8.1.7)
Requirement already satisfied: esphome-dashboard==20231107.0 in /opt/esphome/lib/python3.11/site-packages (from esphome) (20231107.0)
Requirement already satisfied: aioesphomeapi==21.0.1 in /opt/esphome/lib/python3.11/site-packages (from esphome) (21.0.1)
Requirement already satisfied: zeroconf==0.130.0 in /opt/esphome/lib/python3.11/site-packages (from esphome) (0.130.0)
Requirement already satisfied: python-magic==0.4.27 in /opt/esphome/lib/python3.11/site-packages (from esphome) (0.4.27)
Requirement already satisfied: kconfiglib==13.7.1 in /opt/esphome/lib/python3.11/site-packages (from esphome) (13.7.1)
Requirement already satisfied: pyparsing>=3.0 in /opt/esphome/lib/python3.11/site-packages (from esphome) (3.1.1)
Requirement already satisfied: argcomplete>=2.0.0 in /opt/esphome/lib/python3.11/site-packages (from esphome) (3.2.2)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /opt/esphome/lib/python3.11/site-packages (from aioesphomeapi==21.0.1->esphome) (2.3.2)
Requirement already satisfied: protobuf>=3.19.0 in /opt/esphome/lib/python3.11/site-packages (from aioesphomeapi==21.0.1->esphome) (4.25.2)
Requirement already satisfied: chacha20poly1305-reuseable>=0.12.0 in /opt/esphome/lib/python3.11/site-packages (from aioesphomeapi==21.0.1->esphome) (0.12.0)
Requirement already satisfied: noiseprotocol<1.0,>=0.3.1 in /opt/esphome/lib/python3.11/site-packages (from aioesphomeapi==21.0.1->esphome) (0.3.1)
Requirement already satisfied: bitstring>=3.1.6 in /opt/esphome/lib/python3.11/site-packages (from esptool==4.6.2->esphome) (4.1.4)
Requirement already satisfied: cryptography>=2.1.4 in /opt/esphome/lib/python3.11/site-packages (from esptool==4.6.2->esphome) (42.0.0)
Requirement already satisfied: ecdsa>=0.16.0 in /opt/esphome/lib/python3.11/site-packages (from esptool==4.6.2->esphome) (0.18.0)
Requirement already satisfied: reedsolo<1.8,>=1.5.3 in /opt/esphome/lib/python3.11/site-packages (from esptool==4.6.2->esphome) (1.7.0)
Requirement already satisfied: bottle==0.12.* in /opt/esphome/lib/python3.11/site-packages (from platformio==6.1.11->esphome) (0.12.25)
Requirement already satisfied: marshmallow==3.* in /opt/esphome/lib/python3.11/site-packages (from platformio==6.1.11->esphome) (3.20.2)
Requirement already satisfied: pyelftools==0.29 in /opt/esphome/lib/python3.11/site-packages (from platformio==6.1.11->esphome) (0.29)
Requirement already satisfied: requests==2.* in /opt/esphome/lib/python3.11/site-packages (from platformio==6.1.11->esphome) (2.31.0)
Requirement already satisfied: semantic-version==2.10.* in /opt/esphome/lib/python3.11/site-packages (from platformio==6.1.11->esphome) (2.10.0)
Requirement already satisfied: tabulate==0.* in /opt/esphome/lib/python3.11/site-packages (from platformio==6.1.11->esphome) (0.9.0)
Requirement already satisfied: ajsonrpc==1.2.* in /opt/esphome/lib/python3.11/site-packages (from platformio==6.1.11->esphome) (1.2.0)
Requirement already satisfied: starlette<0.32,>=0.19 in /opt/esphome/lib/python3.11/site-packages (from platformio==6.1.11->esphome) (0.31.1)
Requirement already satisfied: uvicorn<0.24,>=0.16 in /opt/esphome/lib/python3.11/site-packages (from platformio==6.1.11->esphome) (0.23.2)
Requirement already satisfied: wsproto==1.* in /opt/esphome/lib/python3.11/site-packages (from platformio==6.1.11->esphome) (1.2.0)
Requirement already satisfied: ifaddr>=0.1.7 in /opt/esphome/lib/python3.11/site-packages (from zeroconf==0.130.0->esphome) (0.2.0)
Requirement already satisfied: packaging>=17.0 in /opt/esphome/lib/python3.11/site-packages (from marshmallow==3.*->platformio==6.1.11->esphome) (23.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/esphome/lib/python3.11/site-packages (from requests==2.*->platformio==6.1.11->esphome) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/esphome/lib/python3.11/site-packages (from requests==2.*->platformio==6.1.11->esphome) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/esphome/lib/python3.11/site-packages (from requests==2.*->platformio==6.1.11->esphome) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/esphome/lib/python3.11/site-packages (from requests==2.*->platformio==6.1.11->esphome) (2023.11.17)
Requirement already satisfied: h11<1,>=0.9.0 in /opt/esphome/lib/python3.11/site-packages (from wsproto==1.*->platformio==6.1.11->esphome) (0.14.0)
Requirement already satisfied: bitarray<3.0.0,>=2.8.0 in /opt/esphome/lib/python3.11/site-packages (from bitstring>=3.1.6->esptool==4.6.2->esphome) (2.9.2)
Requirement already satisfied: cffi>=1.12 in /opt/esphome/lib/python3.11/site-packages (from cryptography>=2.1.4->esptool==4.6.2->esphome) (1.16.0)
Requirement already satisfied: six>=1.9.0 in /opt/esphome/lib/python3.11/site-packages (from ecdsa>=0.16.0->esptool==4.6.2->esphome) (1.16.0)
Requirement already satisfied: anyio<5,>=3.4.0 in /opt/esphome/lib/python3.11/site-packages (from starlette<0.32,>=0.19->platformio==6.1.11->esphome) (4.2.0)
Requirement already satisfied: sniffio>=1.1 in /opt/esphome/lib/python3.11/site-packages (from anyio<5,>=3.4.0->starlette<0.32,>=0.19->platformio==6.1.11->esphome) (1.3.0)
Requirement already satisfied: pycparser in /opt/esphome/lib/python3.11/site-packages (from cffi>=1.12->cryptography>=2.1.4->esptool==4.6.2->esphome) (2.21)

```

**Comment by johannesc** [comment]
I had the same issue. I solved it by resinstalling esphome in a fresh virtual env:
```
python -m venv .venv
. .venv/bin/activate
pip install esphome
esphome logs XXX.yaml
```

**Comment by spraot** [comment]
@johannesc that didn't solve it for me

**Comment by johannesc** [comment]
Hi,
I pinned it down to chacha20poly1305-reuseable. Upgrading from 0.12.0 to 0.12.1 was the thing that solved the problem for me. The root cause is probably https://github.com/bdraco/chacha20poly1305-reuseable/issues/34.

Make sure that you are running the correct version of that:
```
$ pip freeze | grep chacha20poly1305
chacha20poly1305-reuseable==0.12.1
```

**Comment by spraot** [comment]
@johannesc Thanks, that was it!
