### ISSUE TITLE
Error when Wifi connection lost

### ISSUE THREAD

**Issue by mjcumming** [esphome/issues#57]
The configuration below causes this error when the wifi connection is lost.

`esphomeyaml:
  name: subaruoutback
  platform: ESP8266
  board: d1_mini_pro

wifi:
  ssid: 'xxT'
  password: 'xxx
  hostname: 'OutbackPresence'
  reboot_timeout: 0s

  ap: 
    ssid: 'outback'
    

mqtt:
  broker: '192.168.8.1'
  discovery: True
  #reboot_timeout: 0s

# Enable logging
logger:
  level: VERBOSE
  logs:
    mqtt.component: DEBUG
    mqtt.client: ERROR

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    update_interval: 5s
    filters: []

  - platform: uptime
    name: Uptime Sensor    
    update_interval: 5s
    filters: []

`

`[20:16:39][V][sensor.sensor:020]: 'Uptime Sensor': Received new state 38.057999
[20:16:43][V][sensor.sensor:020]: 'WiFi Signal Sensor': Received new state -58.000000
[20:16:44][V][sensor.sensor:020]: 'Uptime Sensor': Received new state 43.050999
[20:16:48][V][sensor.sensor:020]: 'WiFi Signal Sensor': Received new state -51.000000
[20:16:49][V][sensor.sensor:020]: 'Uptime Sensor': Received new state 48.051998
[20:16:53][V][sensor.sensor:020]: 'WiFi Signal Sensor': Received new state -51.000000
[20:16:53]bcn_timout,ap_probe_send_start
[20:16:54][V][sensor.sensor:020]: 'Uptime Sensor': Received new state 53.044998
[20:16:56]ap_probe_send over, rest wifi status to disassoc
[20:16:56]state: 5 -> 0 (1)
[20:16:56]rm 0
[20:16:56]pm close 7
[20:16:56][W][wifi:727]: Event: Disconnected ssid='4254_EXT' bssid=80:3F:5D:67:87:58 reason='Beacon Timeout'
[20:16:58]
[20:16:58]Panic C:\users\mike\.platformio\packages\framework-arduinoespressif8266\cores\esp8266\core_esp8266_main.cpp:103 __yield
[20:16:58]
[20:16:58]ctx: sys
[20:16:58]sp: 3fffeb90 end: 3fffffb0 offset: 01b0
[20:16:58]
[20:16:58]>>>stack>>>
[33mWARNING Found stack trace! Trying to decode it[0m
[20:16:58]3fffed40:  00f8d2cb 00000000 00000028 0000006d
[20:16:58]3fffed50:  00000000 00000000 3fff38d4 0000006d
[20:16:58]3fffed60:  00000000 00000000 3fff38d4 4021168c
[32mINFO Need to fetch platformio IDE-data, please stand by[0m
[32mINFO Running:  platformio run -d subaruoutback -t idedata[0m
Traceback (most recent call last):
  File "c:\users\mike\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mike\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mike\AppData\Local\Programs\Python\Python37\Scripts\esphomeyaml.exe\__main__.py", line 9, in <module>
  File "c:\users\mike\appdata\local\programs\python\python37\lib\site-packages\esphomeyaml\__main__.py", line 505, in main
    return run_esphomeyaml(sys.argv)
  File "c:\users\mike\appdata\local\programs\python\python37\lib\site-packages\esphomeyaml\__main__.py", line 495, in run_esphomeyaml
    return POST_CONFIG_ACTIONS[args.command](args, config)
  File "c:\users\mike\appdata\local\programs\python\python37\lib\site-packages\esphomeyaml\__main__.py", line 318, in command_run
    return show_logs(config, args, port)
  File "c:\users\mike\appdata\local\programs\python\python37\lib\site-packages\esphomeyaml\__main__.py", line 217, in show_logs
    run_miniterm(config, port)
  File "c:\users\mike\appdata\local\programs\python\python37\lib\site-packages\esphomeyaml\__main__.py", line 124, in run_miniterm
    config, line, backtrace_state=backtrace_state)
  File "c:\users\mike\appdata\local\programs\python\python37\lib\site-packages\esphomeyaml\platformio_api.py", line 180, in process_stacktrace
    _decode_pc(config, addr.group())
  File "c:\users\mike\appdata\local\programs\python\python37\lib\site-packages\esphomeyaml\platformio_api.py", line 107, in _decode_pc
    idedata = get_idedata(config)
  File "c:\users\mike\appdata\local\programs\python\python37\lib\site-packages\esphomeyaml\platformio_api.py", line 60, in get_idedata
    IDE_DATA = run_idedata(config)
  File "c:\users\mike\appdata\local\programs\python\python37\lib\site-packages\esphomeyaml\platformio_api.py", line 43, in run_idedata
    match = re.search(r'{.*}', stdout)
  File "c:\users\mike\appdata\local\programs\python\python37\lib\re.py", line 183, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object`

**Comment by OttoWinter** [comment]
This has been fixed
