### ISSUE TITLE
Web interface/dashboard do not show device configs

### ISSUE THREAD

**Issue by Saentist** [esphome/issues#5802]
### The problem

After update to latest DEV version no more device configs show in web ui.

![image](https://github.com/esphome/issues/assets/16975883/fbef14d5-4f9f-4227-a0e8-62804eac8188)

 all config files are in place 
 even new device add disappear immediately. 

### Which version of ESPHome has the issue?

 2024.6.0-dev

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.5.3

### What platform are you using?

ESP8266

**Comment by Saentist** [comment]
2024.6.0-dev20240518
Same situation

**Comment by ThomasFTL** [comment]
All actual updates are running.
ESPhome 2024.5.0 Home Assistant AddOn
Home Assistant 2024.5.4

The Web Ui show no content. Only the headers of the tables for the data and logs and the footer to change sheme are shown. I see no data and no logs.
But Home Assistant gets all data and logs.

**Comment by Saentist** [comment]
@ThomasFTL  this is Issue is for managment webUI
For device WebUI check if your browser don't block web content
```
https://esphome.io/_static/webserver-v1.min.css
https://esphome.io/_static/webserver-v1.min.js
```
https://esphome.io/components/web_server.html

**Comment by ThomasFTL** [comment]
@Saentist  thats work.
I test with Mozilla, Chrome and Edge.
The code of the css file and the js file are displayed as text.
But, when I call the ESP's IP, I get the two empty tables.
If I display the ESP logs in HA under ESP home, this display works.

**Comment by Saentist** [comment]
@ThomasFTL create NEW issue and post YAML config file of device

**Comment by ThomasFTL** [comment]
@Saentist 
I have around 10 ESP home devices that have been working flawlessly for over 2 years.
Since the last update to ESP home, the websites of all ESPs no longer work.
I see only the frame.

**Comment by Saentist** [comment]
@ThomasFTL 
I have same problem with devices 
`/events`
do not return data

**Comment by Saentist** [comment]
```yaml
devices-list.ts:253 Uncaught (in promise) TypeError: i.toLocaleLowerCase is not a function
    at devices-list.ts:253:4
    at Array.sort (<anonymous>)
    at devices-list.ts:249:8
    at r (polling-collection.ts:40:29)
```
this is a repeating message with browser is not happy with it.

**Comment by ThomasFTL** [comment]
Update from 2024.5.0 to 2024.5.1: The same problem. No improvement.

**Comment by olonsoft** [comment]
Just compiled and updated a device and I have the same error as @ThomasFTL shows in his screenshot.
Chrome shows this error in console:
```
www.js:3 Uncaught (in promise) Error: invalid template strings array
    at Ct (www.js:3:335)
    at Mt (www.js:3:1057)
    at new H (www.js:3:1221)
    at T._$AC (www.js:3:4731)
    at T.g (www.js:3:4433)
    at T._$AI (www.js:3:4089)
    at qt (www.js:3:7409)
    at yt.update (www.js:3:7811)
    at yt.performUpdate (www.js:1:6064)
    at yt.scheduleUpdate (www.js:1:5716)
```

**Comment by ThomasFTL** [comment]
I have one ESP 32 Cam-Projekt. Thats work. But all ESP 8266 have the Problem with the Web-Interface.

**Comment by ThomasFTL** [comment]
Why are ESP32, IDF, Libretiny and Pico W components also compiled with an esp12e?
Are they also integrated by the linker?

**Comment by randybb** [comment]
guys, this issue is about the dashboard, for the web_server problem is opened another issue

**Comment by vvrein** [comment]
Another fix is here https://github.com/esphome/issues/issues/5793#issuecomment-2120983660

**Comment by Saentist** [comment]
If disabled caching on devices, web interface is show without problem.
but strange message appear.
`Could not allocate memory for JSON document! Requested 512 bytes, largest free heap block: 512 bytes`

**Comment by ssieb** [comment]
Fixed with https://github.com/esphome/esphome/pull/6797

**Comment by Saentist** [comment]
@ssieb cannot confirm, still blank dashboard devices list.
```
Uncaught (in promise) TypeError: i.toLocaleLowerCase is not a function
    at devices-list.ts:253:4
    at Array.sort (<anonymous>)
    at devices-list.ts:249:8
    at r (polling-collection.ts:40:29)
```
```
The resource http://10.244.21.87:8123/api/hassio_ingress/-J94cKKnPBFYq23v4xZUvlsJ9eTbwTncftyvBEf4MAs/static/fonts/material-icons/MaterialIcons-Regular.woff2?hash=570eb838 
was preloaded using link preload but not used within a few seconds from the window's load event. 
Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

**Comment by ssieb** [comment]
Sorry, this got overrun with people from the other issue and I missed that.

**Comment by Saentist** [comment]
2024.6.0-dev20240528
still not devices

**Comment by Saentist** [comment]
2024.6.0-dev20240529
nothing

**Comment by ssieb** [comment]
There's no need to keep posting like that unless you think there was something submitted that might change it.
This is something very specific to your install since no one else is seeing this.
Maybe try re-installing the add-on.

**Comment by Saentist** [comment]
@ssieb any steps for debugging?
I use HAOS so nothing specific can be different from others with same setup.

**Comment by ssieb** [comment]
It looks like what happens when a proxy doesn't pass websockets.  Check the browser network log and see if there are any errors.

**Comment by Saentist** [comment]
> It looks like what happens when a proxy doesn't pass websockets. Check the browser network log and see if there are any errors.

I try different browsers same situation, no devices show, even if create new it disappear after wizard finish.

**Comment by ssieb** [comment]
I don't see any issues in the HAR file.  All the devices are there and things seem to be working.  I don't know why only you would be getting that error.

**Comment by ssieb** [comment]
I don't see any issues in the HAR file.  All the devices are there and things seem to be working.

**Comment by Saentist** [comment]
@ssieb  Dashboard do not show devices, page generator have something wrong I guess. 

![image](https://github.com/esphome/issues/assets/16975883/be756de8-7744-43fc-bfc2-afaac865eb22)
![image](https://github.com/esphome/issues/assets/16975883/80306269-12e0-450e-a218-2929d4deb26a)
![image](https://github.com/esphome/issues/assets/16975883/ce819cfa-9ba9-4a49-81c3-4f48a7b07844)

**Comment by sql-aus-hh** [comment]
I am having the same issue. Two different computers, 
It seems to work if reload the integration, but just for one refresh (F5), then ESPhome-screen keeps empty

![image](https://github.com/esphome/issues/assets/20439825/7625022b-81fe-4bcb-a5d3-c3b32f756225)

**Comment by sql-aus-hh** [comment]
If you open the "issue" tab in Chrome you will receive the following hint... but I don't know if this is the reason:

![image](https://github.com/esphome/issues/assets/20439825/3e130c1e-9912-4ff7-b207-07e2cc3777e6)

**Comment by Saentist** [comment]
@sql-aus-hh 
can you share what addons are also installed, maby is some conflicting one

**Comment by Saentist** [comment]
Is any one else have this problem?
Any debugging suggestions are welcome.

**Comment by Saentist** [comment]
Update
Installed ESP home on another virtual pc and ESPHome dashboard again stop to show device.

**Comment by JovanVuceljic** [comment]
Saw comment in [this issue](https://github.com/esphome/issues/issues/5873) that bad yaml can cause the issue. 
Did ssh into `root/homeassistant/esphome` and removed the latest edited one by one until the UI  showed up.
HA addon for ssh can be used for this. I did Terminal & SSH.

**Comment by Saentist** [comment]
> Saw comment in [this issue](https://github.com/esphome/issues/issues/5873) that bad yaml can cause the issue. Did ssh into `root/homeassistant/esphome` and removed the latest edited one by one until the UI showed up. HA addon for ssh can be used for this. I did Terminal & SSH.

it import it from devices
very bad situation better to see from where error come not to guess.

**Comment by igorbaikov** [comment]
I think it's a bug of how names are parsed. Numbers are not parsed as a string, so it messes with esphome's dashboard. Rename devices to have letters together with numbers, i.e. 8266.yaml -> esp8266.yaml.

You can see it when you are in editing mode in esphome: the name of the device can't be just a number, it shows an error.

**Comment by Saentist** [comment]
> I think it's a bug of how names are parsed. Numbers are not parsed as a string, so it messes with esphome's dashboard. Rename devices to have letters together with numbers, i.e. 8266.yaml -> esp8266.yaml.
> 
> You can see it when you are in editing mode in esphome: the name of the device can't be just a number, it shows an error.

10x @igorbaikov 
This is so unlogical bug but definitely this is a problem.
more interesting, this was not a bug before,
and if only one device there also no problem.
Parser need to be fixed!

**Comment by Saentist** [comment]
After try to update outdated firmware of one of esp devices all they disappear again
/no number starting devices/
