### ISSUE TITLE
ESP32-C3 (LaskaKit ESP32-C3-LPKit) not able to load the FW

### ISSUE THREAD

**Issue by stranskj** [esphome/issues#5805]
### The problem

I am not able to load the compiled FW to the board using the USB cable, with the Error 71. When I run it from the command line, a bit more thorough tracback, see bellow.

I think the esptool.py fails instantly, without even trying the board. I tried different boards, different cables, not sure how relevant is that...

### Which version of ESPHome has the issue?

2024.5.0

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### Board

LaskaKit ESP32-C3-LPKit

### Component causing the issue

esptool.py?

### Example YAML snippet

```yaml
esphome:
  name: esp32c3-test
  friendly_name: esp32c3-test
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_flash: 40000000L
    board_build.flash_size: 4MB
    board_build.mcu: esp32c3

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf # tried Arduino too, no difference
```

### Anything in the logs that might be useful for us?

```txt
esptool.py --before default_reset --after hard_reset --baud 115200 --port /dev/ttyACM0 --chip esp32c3 write_flash -z --flash_size detect 0x10000 /config/.esphome/build/esp-toilet-clima/.pioenvs/esp-toilet-clima/firmware.bin 0x0 /config/.esphome/build/esp-toilet-clima/.pioenvs/esp-toilet-clima/bootloader.bin 0x8000 /config/.esphome/build/esp-toilet-clima/.pioenvs/esp-toilet-clima/partitions.bin 0x9000 /config/.esphome/build/esp-toilet-clima/.pioenvs/esp-toilet-clima/ota_data_initial.bin
esptool.py v4.7.0
Serial port /dev/ttyACM0
Connecting...
Traceback (most recent call last):
  File "/usr/local/bin/esptool.py", line 37, in <module>
    esptool._main()
  File "/usr/local/lib/python3.11/dist-packages/esptool/__init__.py", line 1139, in _main
    main()
  File "/usr/local/lib/python3.11/dist-packages/esptool/__init__.py", line 712, in main
    esp = esp or get_default_connected_device(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/esptool/__init__.py", line 1024, in get_default_connected_device
    _esp.connect(before, connect_attempts)
  File "/usr/local/lib/python3.11/dist-packages/esptool/loader.py", line 678, in connect
    last_error = self._connect_attempt(reset_strategy, mode)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/esptool/loader.py", line 563, in _connect_attempt
    reset_strategy()  # Reset the chip to bootloader (download mode)
    ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/esptool/reset.py", line 100, in __call__
    self._setRTS(False)
  File "/usr/local/lib/python3.11/dist-packages/esptool/reset.py", line 40, in _setRTS
    self.port.setRTS(state)
  File "/usr/local/lib/python3.11/dist-packages/serial/serialutil.py", line 600, in setRTS
    self.rts = value
    ^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/serial/serialutil.py", line 463, in rts
    self._update_rts_state()
  File "/usr/local/lib/python3.11/dist-packages/serial/serialposix.py", line 708, in _update_rts_state
    fcntl.ioctl(self.fd, TIOCMBIC, TIOCM_RTS_str)
OSError: [Errno 71] Protocol error
```

### Additional information

Link to the board GitHub: https://github.com/LaskaKit/ESP32-C3-LPKit
I have v3.

**Comment by ssieb** [comment]
This isn't an esphome issue.  It's either a problem with docker or you need to manually put the device in download mode first.
https://docs.espressif.com/projects/esptool/en/latest/esp32s2/troubleshooting.html#issues-when-using-usb-serial-jtag-or-usb-otg
If you need more help, come ask on discord or one of the forums.
