### ISSUE TITLE
ValueError after succesful upload over network

### ISSUE THREAD

**Issue by wilmardo** [esphome/issues#596]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESP8266, pip installed esphome. Tested with latest release and current master.

**Affected component:**

Python uploader of Esphome

**Description of problem:**
My config renders and ValueError when trying to upload the firmware.

**Problem-relevant YAML-configuration entries:**
```yaml
---
# Enable wifi with static ip
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.1.55
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Enable MQTT
mqtt:
  broker: !secret mqtt_broker
  port: !secret mqtt_port
  username: !secret mqtt_username
  password: !secret mqtt_password

# Enable logging
logger:
  level: INFO
  esp8266_store_log_strings_in_flash: False

# Enable status led on onboard led
status_led:
  pin:
    number: GPIO2
    inverted: True

# Enable esphome
esphome:
  name: watermeter
  platform: ESP8266
  board: d1

sensor:
  - platform: pulse_counter
    pin: D7
    name: Water Meter
    unit_of_measurement: m3
    update_interval: 10s
    # internal_filter: 10us
    # filters:
    #   - multiply: 0.006  # 10000/min = 1m3
    accuracy_decimals: 3
    on_value:
      then:
        - switch.turn_on: led
        - delay: 100ms
        - switch.turn_off: led

switch:
  - platform: gpio
    pin: D5
    id: led
```

**Logs (if applicable):**

```
Compiling .pioenvs/watermeter/FrameworkArduino/spiffs_hal.cpp.o
Compiling .pioenvs/watermeter/FrameworkArduino/time.c.o
Compiling .pioenvs/watermeter/FrameworkArduino/uart.c.o
Compiling .pioenvs/watermeter/FrameworkArduino/umm_malloc/umm_malloc.c.o
Archiving .pioenvs/watermeter/libFrameworkArduino.a
Indexing .pioenvs/watermeter/libFrameworkArduino.a
Linking .pioenvs/watermeter/firmware.elf
Retrieving maximum program size .pioenvs/watermeter/firmware.elf
Checking size .pioenvs/watermeter/firmware.elf
Building .pioenvs/watermeter/firmware.bin
Memory Usage -> http://bit.ly/pio-memory-usage
DATA:    [====      ]  41.1% (used 33656 bytes from 81920 bytes)
PROGRAM: [===       ]  31.5% (used 329344 bytes from 1044464 bytes)
============================================= [SUCCESS] Took 23.80 seconds =============================================
INFO Successfully compiled program.
Traceback (most recent call last):
  File "/c/Users/wilmaro/Development/Prive/esphome-configs/venv/bin/esphome", line 11, in <module>
    load_entry_point('esphome==1.14.0.dev0', 'console_scripts', 'esphome')()
  File "/c/Users/wilmaro/Development/Prive/esphome-configs/venv/lib/python3.6/site-packages/esphome/__main__.py", line 537, in main
    return run_esphome(sys.argv)
  File "/c/Users/wilmaro/Development/Prive/esphome-configs/venv/lib/python3.6/site-packages/esphome/__main__.py", line 524, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
  File "/c/Users/wilmaro/Development/Prive/esphome-configs/venv/lib/python3.6/site-packages/esphome/__main__.py", line 310, in command_run
    show_ota=True, show_mqtt=False, show_api=True)
  File "/c/Users/wilmaro/Development/Prive/esphome-configs/venv/lib/python3.6/site-packages/esphome/__main__.py", line 78, in choose_upload_log_host
    return choose_prompt(options)
  File "/c/Users/wilmaro/Development/Prive/esphome-configs/venv/lib/python3.6/site-packages/esphome/__main__.py", line 38, in choose_prompt
    raise ValueError
ValueError
```

**Additional information and things you've tried:**
Seems to be the same as #8 

If more logs are needed please let me know :)

**Comment by OttoWinter** [comment]
You have OTA disabled and no USB device is connected to the computer - so there's nowhere esphome can upload the binary to
