### ISSUE TITLE
Issue after updating - sensor.max31865 platform not found

### ISSUE THREAD

**Issue by roscsa77** [esphome/issues#6195]
### The problem

I recently upgraded an older version of ESPHome to 2024.7.3 and today I hopefully upgraded to 2024.8.0, but my problem is not solved, that I cannot compile the yaml file that contains the platform max31865. So far it has worked without errors. Now it says that it cannot find the platform sensor.max31865. If I change it to max31855 or max31856 then the error disappears. 

### Which version of ESPHome has the issue?

2024.8.0

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.7.3

### What platform are you using?

ESP32

### Board

Own developed

### Component causing the issue

max31865

### Example YAML snippet

```yaml
esphome:
  name: floor_heater_control
  platform: ESP32
  board: esp32dev

...

spi:
  miso_pin: 32
  mosi_pin: 33
  clk_pin: 25

sensor:
  - platform: max31865
    name: "Corridor floor temperature"
    cs_pin: 26
    reference_resistance: 430 Ω
    rtd_nominal_resistance: 100 Ω
    update_interval: 10s
    mains_filter: 50Hz
    rtd_wires: 3
    filters:
    - sliding_window_moving_average:
        window_size: 12
        send_every: 6
 - platform: max31865
    name: "Living room floor temperature"
    cs_pin: 27
    reference_resistance: 430 Ω
    rtd_nominal_resistance: 100 Ω
    update_interval: 10s
    mains_filter: 50Hz
    rtd_wires: 3
    filters:
    - sliding_window_moving_average:
        window_size: 12
        send_every: 6
  - platform: max31865
    name: "Kitchen floor temperature"
    cs_pin: 14
    reference_resistance: 430 Ω
    rtd_nominal_resistance: 100 Ω
    update_interval: 10s
    mains_filter: 50Hz
    rtd_wires: 3
    filters:
    - sliding_window_moving_average:
        window_size: 12
        send_every: 6

binary_sensor:
  - platform: gpio
    name: "DI0"
    pin:
      number: 35
      inverted: True
#      mode: INPUT_PULLUP
    filters:
    - delayed_off: 20ms
  - platform: gpio
    name: "GPIO0"
    pin:
      number: 0
      inverted: True
      mode: INPUT_PULLUP
    filters:
    - delayed_off: 20ms

switch:
  - platform: gpio
    name: "Living room floor valve"
    pin: 21
  - platform: gpio
    name: "Kitchen floor valve"
    pin: 19
  - platform: gpio
    name: "Bathroom floor valve"
    pin: 18
  - platform: gpio
    name: "Corridor floor valve"
    pin: 17
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.8.0
INFO Reading configuration /config/esphome/floor_heater_control.yaml...
ERROR Unable to load component max31865.sensor:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 177, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/esphome/custom_components/max31865/sensor.py", line 17, in <module>
    CONFIG_SCHEMA = sensor.sensor_schema(UNIT_CELSIUS, ICON_THERMOMETER, 1).extend({
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sensor_schema() takes from 0 to 1 positional arguments but 3 were given
ERROR Unable to load component max31865.sensor:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 177, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/esphome/custom_components/max31865/sensor.py", line 17, in <module>
    CONFIG_SCHEMA = sensor.sensor_schema(UNIT_CELSIUS, ICON_THERMOMETER, 1).extend({
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sensor_schema() takes from 0 to 1 positional arguments but 3 were given
ERROR Unable to load component max31865.sensor:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 177, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/esphome/custom_components/max31865/sensor.py", line 17, in <module>
    CONFIG_SCHEMA = sensor.sensor_schema(UNIT_CELSIUS, ICON_THERMOMETER, 1).extend({
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sensor_schema() takes from 0 to 1 positional arguments but 3 were given
Failed config

sensor.max31865: [source /config/esphome/floor_heater_control.yaml:36]
  
  Platform not found: 'sensor.max31865'.
  platform: max31865
  name: Corridor floor temperature
  cs_pin: 26
  reference_resistance: 430 Ω
  rtd_nominal_resistance: 100 Ω
  update_interval: 10s
  mains_filter: 50Hz
  rtd_wires: 3
  filters: 
    - sliding_window_moving_average: 
        window_size: 12
        send_every: 6
sensor.max31865: [source /config/esphome/floor_heater_control.yaml:48]
  
  Platform not found: 'sensor.max31865'.
  platform: max31865
  name: Living room floor temperature
  cs_pin: 27
  reference_resistance: 430 Ω
  rtd_nominal_resistance: 100 Ω
  update_interval: 10s
  mains_filter: 50Hz
  rtd_wires: 3
  filters: 
    - sliding_window_moving_average: 
        window_size: 12
        send_every: 6
sensor.max31865: [source /config/esphome/floor_heater_control.yaml:60]
  
  Platform not found: 'sensor.max31865'.
  platform: max31865
  name: Kitchen floor temperature
  cs_pin: 14
  reference_resistance: 430 Ω
  rtd_nominal_resistance: 100 Ω
  update_interval: 10s
  mains_filter: 50Hz
  rtd_wires: 3
  filters: 
    - sliding_window_moving_average: 
        window_size: 12
        send_every: 6
```

### Additional information

![image](https://github.com/user-attachments/assets/84dbcdc1-7c1f-4ddd-97ae-2a55ddb4f83d)

**Comment by ssieb** [comment]
You have a `custom_components` directory with that component in it.  You need to remove that directory.
