### ISSUE TITLE
 Update error esphome-xiaomi_bslamp2

### ISSUE THREAD

**Issue by ADMiNZ** [esphome/issues#6290]
### The problem

Hello. Starting from version 2024.8.3, the firmware for xiaomi_bslamp2 is no longer built. Before this version, everything was assembled without testing. The device itself works on the old firmware, but it always says that it needs to be updated but is not updated.

### Which version of ESPHome has the issue?

2024.8.3-2024.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.9.3

### What platform are you using?

ESP32

### Board

xiaomi_bslamp2

### Component causing the issue

https://github.com/mmakaay/esphome-xiaomi_bslamp2

### Example YAML snippet

```yaml
# --------------------------------------------------------------------------
# Substitutions
#
# These are substitutions as used by the configuration packages from below.
# You can uncomment and update the ones that you want to modify.
# --------------------------------------------------------------------------

substitutions:
  name: bedside-lamp
  friendly_name: Bedside Lamp
  #light_name: ${friendly_name} RGBWW Light
  #light_mode_text_sensor_name: ${friendly_name} Light Mode
  #default_transition_length: 800ms

# --------------------------------------------------------------------------
# Load configuration packages
#
# These provide a convenient way to compose your device configuration from
# some functional building blocks. Pick and mix the blocks that you need.
#
# For customization you can override options in your config or you can
# copy the contents of these packages directly in your config file as
# an example for your own customizations.
#
# Available packages are:
# - core.yaml                : core components & hardware setup
# - behavior_default.yaml    : default device behavior
# - ota_feedback.yaml        : enable visual feedback during OTA updates
# - activate_preset_svc.yaml : 'activate_preset' service for Home Assistant
# --------------------------------------------------------------------------

packages:
  bslamp2:
    url: https://github.com/mmakaay/esphome-xiaomi_bslamp2
    ref: dev
    files:
      - packages/core.yaml
      - packages/behavior_default.yaml
      - packages/ota_feedback.yaml
      - packages/activate_preset_svc.yaml
    refresh: 0s

# --------------------------------------------------------------------------
# Use your own preferences for these components.
# --------------------------------------------------------------------------

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret api_key

ota:
  platform: esphome
  password: !secret ota_password
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.9.1
INFO Reading configuration /config/esphome/bedside-lamp.yaml...
INFO Updating https://github.com/mmakaay/esphome-xiaomi_bslamp2@dev
INFO Generating C++ source...
INFO Compiling app...
Processing bedside-lamp (board: esp32doit-devkit-v1; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40407.0 (4.4.7) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
-- Building ESP-IDF components for target esp32
-- Project sdkconfig file /data/build/bedside-lamp/sdkconfig.bedside-lamp
-- Configuring incomplete, errors occurred!
See also "/data/build/bedside-lamp/.pioenvs/bedside-lamp/CMakeFiles/CMakeOutput.log".

fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Traceback (most recent call last):
  File "/data/cache/platformio/packages/framework-espidf/tools/kconfig_new/confgen.py", line 644, in <module>
    main()
  File "/data/cache/platformio/packages/framework-espidf/tools/kconfig_new/confgen.py", line 264, in main
    config = kconfiglib.Kconfig(args.kconfig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.platformio/penv/.espidf-4.4.7/lib/python3.11/site-packages/kconfiglib.py", line 947, in __init__
    self._init(filename, warn, warn_to_stderr, encoding)
  File "/root/.platformio/penv/.espidf-4.4.7/lib/python3.11/site-packages/kconfiglib.py", line 1085, in _init
    self._parse_block(None, self.top_node, self.top_node).next = None
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.platformio/penv/.espidf-4.4.7/lib/python3.11/site-packages/kconfiglib.py", line 2982, in _parse_block
    prev = self._parse_block(None, parent, prev)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.platformio/penv/.espidf-4.4.7/lib/python3.11/site-packages/kconfiglib.py", line 2982, in _parse_block
    prev = self._parse_block(None, parent, prev)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.platformio/penv/.espidf-4.4.7/lib/python3.11/site-packages/kconfiglib.py", line 2907, in _parse_block
    while self._next_line():
          ^^^^^^^^^^^^^^^^^
  File "/root/.platformio/penv/.espidf-4.4.7/lib/python3.11/site-packages/kconfiglib.py", line 2224, in _next_line
    line = self._readline()
           ^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error
CMake Error at /data/cache/platformio/packages/framework-espidf/tools/cmake/kconfig.cmake:266 (message):
  Failed to run confgen.py
  (/root/.platformio/penv/.espidf-4.4.7/bin/python;/data/cache/platformio/packages/framework-espidf/tools/kconfig_new/confgen.py;--kconfig;/data/cache/platformio/packages/framework-espidf/Kconfig;--sdkconfig-rename;/data/cache/platformio/packages/framework-espidf/sdkconfig.rename;--config;/data/build/bedside-lamp/sdkconfig.bedside-lamp;--env-file;/data/build/bedside-lamp/.pioenvs/bedside-lamp/config.env).
  Error 1
Call Stack (most recent call first):
  /data/cache/platformio/packages/framework-espidf/tools/cmake/build.cmake:534 (__kconfig_generate_config)
  /data/cache/platformio/packages/framework-espidf/tools/cmake/project.cmake:476 (idf_build_process)
  CMakeLists.txt:3 (project)



========================== [FAILED] Took 5.98 seconds ==========================
```

**Comment by kcajjones** [comment]
I'm getting similar errors compiling updates for my Raspberry Pi Pico W.
I've not found a solution/cause yet.

**Comment by mmakaay** [comment]
I'm the author of the bslamp2 component, and I just did a fresh build (fully fresh build cache + paltformio cache) of the firmware. This build was successful using ESPHome 2024.9.2. So this does not seem to be a general issue.

Some output from my build:
```
INFO ESPHome 2024.9.2
------8<------
Processing bedside-lamp-office (board: esp32dev; framework: espidf; platform: platformio/espressif32@5.4.0)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40407.240606 (4.4.7) 
 - tool-cmake @ 3.16.4 
 - tool-ninja @ 1.7.1 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
```

The only difference with my output is `framework-espidf @ 3.40407.240606` which is `framework-espidf @ 3.40407.0 (4.4.7)` in the log of the failed build. So that might be a pointer at the source of the build issue?

@kcajjones : Do you see the same pattern in the output of your build?

@kcajjones / @ADMiNZ : What platform are you building the code on? I am building on an ADM64 myself. Any chance that your using something like ARM on a raspberry Pi or so?

**Comment by ADMiNZ** [comment]
Hello @mmakaay.

I am using x86 processor (AMD64)

**Comment by randybb** [comment]
Yea, no issue (at least not with the stable one. dev is a bit different story, but it is related only to singlecore esp32).

Try to clean your build files and if this will not help remove/add the esphome addon (all files will be preserved)/

**Comment by ADMiNZ** [comment]
Thank you very much @randybb, @mmakaay Removing and installing esphome helped! :)
