### ISSUE TITLE
external_components not properly fetching (before yaml check) / sometimes not working at all

### ISSUE THREAD

**Issue by RubenKelevra** [esphome/issues#6299]
### The problem

The external_components function is a bit flaky for me, when overwriting an already existing component with an updated one for testing.

## Issues I've noticed
- Using just a branch, will lead to no updates being done, after pushing new commits to Github to the branch.
- Using tags will sometimes not work at all, without any notification about not using the external_component. This will lead to complains by the yaml checker if there were changes to the syntax as the only way to find out that something was going wrong. If there were no changes to the syntax, there's no way of knowing that this happened.
- After pushing a new tag, even when waiting two minutes, it will still complain that this path does not exist. A retry will immediately fetch the new tag and build (in most cases).

### Observations
- Sometimes it helps to wait just half an hour, sometimes it won't.
- Cleaning the build files don't help
- Pushing the same commit to a new tag will help sometimes.

### Which version of ESPHome has the issue?

2024.9.2 / 2024.9.1

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.10.0b3 / 2024.9.0

### What platform are you using?

ESP8266

### Board

Wemos D1 mini

### Component causing the issue

external_components

### Example YAML snippet

```yaml
external_components:
  - source: github://RubenKelevra/esphome_esphome@tcs34725_spec_based_irradiance_output_v0.23
    components: [ tcs34725 ]
```

### Anything in the logs that might be useful for us?

```txt
#### Not fetching the update at all:

INFO ESPHome 2024.9.2
INFO Reading configuration /config/esphome/ambient-light-sensor.yaml...
INFO Detected timezone 'Europe/Berlin'
Failed config

sensor.tcs34725: [source /config/esphome/ambient-light-sensor.yaml:88]
  platform: tcs34725
  i2c_id: bus_a
  
  [red_channel_irradiance] is an invalid option for [sensor.tcs34725]. Did you mean [red_channel]?
  red_channel_irradiance: 
    name: Ambient Light Sensor Red Channel Irradiance
    accuracy_decimals: 1
    filters: 
      - or: 
          - throttle: 300s
          - delta: 0.01
  
  [green_channel_irradiance] is an invalid option for [sensor.tcs34725]. Did you mean [green_channel]?
  green_channel_irradiance: 
    name: Ambient Light Sensor Green Channel Irradiance
    accuracy_decimals: 1
    filters: 
      - or: 
          - throttle: 300s
          - delta: 0.01
  
  [blue_channel_irradiance] is an invalid option for [sensor.tcs34725]. Did you mean [blue_channel]?
  blue_channel_irradiance: 
    name: Ambient Light Sensor Blue Channel Irradiance
    accuracy_decimals: 1
    filters: 
      - or: 
          - throttle: 300s
          - delta: 0.01
  
  [sensor_saturation] is an invalid option for [sensor.tcs34725]. Please check the indentation.
  sensor_saturation: 
    name: Ambient Light Sensor Sensor Saturation
    accuracy_decimals: 1


#### First try of fetching a newly published tag:

INFO ESPHome 2024.9.2
INFO Reading configuration /config/esphome/ambient-light-sensor.yaml...
Failed config

external_components: [source /config/esphome/ambient-light-sensor.yaml:2]
  - 
    Could not find components folder for source. Please check the source contains a 'components' or 'esphome/components' folder.
    source: |-
      github://RubenKelevra/esphome_esphome@tcs34725_spec_based_irradiance_output_v0.24
    components: 
      - tcs34725

### Hitting retry won't work:

INFO ESPHome 2024.9.2
INFO Reading configuration /config/esphome/ambient-light-sensor.yaml...
INFO Detected timezone 'Europe/Berlin'
Failed config

sensor.tcs34725: [source /config/esphome/ambient-light-sensor.yaml:88]
  platform: tcs34725
  i2c_id: bus_a
  
  [red_channel_irradiance] is an invalid option for [sensor.tcs34725]. Did you mean [red_channel]?
  red_channel_irradiance: 
    name: Ambient Light Sensor Red Channel Irradiance
    accuracy_decimals: 1
    filters: 
      - or: 
          - throttle: 300s
          - delta: 0.01
  
  [green_channel_irradiance] is an invalid option for [sensor.tcs34725]. Did you mean [green_channel]?
  green_channel_irradiance: 
    name: Ambient Light Sensor Green Channel Irradiance
    accuracy_decimals: 1
    filters: 
      - or: 
          - throttle: 300s
          - delta: 0.01
  
  [blue_channel_irradiance] is an invalid option for [sensor.tcs34725]. Did you mean [blue_channel]?
  blue_channel_irradiance: 
    name: Ambient Light Sensor Blue Channel Irradiance
    accuracy_decimals: 1
    filters: 
      - or: 
          - throttle: 300s
          - delta: 0.01
  
  [sensor_saturation] is an invalid option for [sensor.tcs34725]. Please check the indentation.
  sensor_saturation: 
    name: Ambient Light Sensor Sensor Saturation
    accuracy_decimals: 1

#### Changing to v0.23, which is the same commit, does work:

INFO ESPHome 2024.9.2
INFO Reading configuration /config/esphome/ambient-light-sensor.yaml...
INFO Detected timezone 'Europe/Berlin'
INFO Generating C++ source...
INFO Compiling app...
Processing ambient-light-sensor (board: d1_mini; framework: arduino; platform: platformio/espressif8266@4.2.1)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
Dependency Graph
|-- ESP8266WiFi @ 1.0
|-- ESP8266mDNS @ 1.2
|-- noise-c @ 0.1.6
|-- Wire @ 1.0
```

**Comment by nkinnan** [comment]
```yaml
external_components:
  - source:
    refresh: 1s  <------------------- add this
```

**Comment by nkinnan** [comment]
I couldn't say, I just run with the refresh specified and have had no issues.  

speculation: I suppose it doesn't *know* that the tag wasn't found because it didn't check because it wasn't refreshing from git in the first place since it's "timeout" to refresh wasn't hit.  And if you manually go into the filesystem and delete what it downloaded, and it's not hit the refresh "timeout" it again doesn't check git, and doesn't know you went and deleted it behind it's back.

**Comment by RubenKelevra** [comment]
Well, that sounds pretty broken ;D

If I got time I'll take a look

**Comment by nkinnan** [comment]
It's just a guess ;) But I'm sure any improvements would be welcomed by esphome.

**Comment by blacknell** [comment]
I was seeing this when specifying a PR number and after pushing new commits it just wasn't being download. I ended up using local files

**Comment by RubenKelevra** [comment]
@github-actions: get lost.

**Comment by RubenKelevra** [comment]
still not stale 🙄

**Comment by chilipepperpizza** [comment]
~~It looks like the bot is still suggesting this method that no longer works. If the issue can't be fixed, could the bot be updated to show instructions on how to use the external component locally?~~

~~Hmm, nevermind I think.. I see it pulls the PR. Perhaps there's a separate issue with this particular PR that ends up in a "platform not found" error..~~

Well I've leaned a lot this morning :) I've added the dev version of ESPHome to home assistant and was able to successfully use this new component with the bot's provided yaml suggestion.

<img width="924" height="300" alt="Image" src="https://github.com/user-attachments/assets/7a61a828-40e8-4587-a647-eecbaabc21ee" />

```
INFO ESPHome 2025.7.5
INFO Reading configuration /config/esphome/test-air-quality.yaml...
INFO Updating https://github.com/esphome/esphome.git@pull/9254/head
ERROR Unable to import component sen5x.sensor:
Traceback (most recent call last):
  File "/esphome/esphome/loader.py", line 200, in _lookup_module
    module = importlib.import_module(f"esphome.components.{domain}")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/data/external_components/b35e7f11/esphome/components/sen5x/sensor.py", line 6, in <module>
    from esphome.const import (
ImportError: cannot import name 'CONF_ALTITUDE_COMPENSATION' from 'esphome.const' (/esphome/esphome/const.py)
Failed config

Platform not found: 'sensor.sen5x'
```
