### ISSUE TITLE
ssl.SSLError: [X509] PEM lib (_ssl.c:4123)

### ISSUE THREAD

**Issue by eximo84** [esphome/issues#6610]
### The problem

Trying to write a firmware but getting ssl.SSLError: [X509] PEM lib (_ssl.c:4123)... unsure why?

### Which version of ESPHome has the issue?

2024.12.2

### What type of installation are you using?

Docker

### What platform are you using?

ESP32

### YAML Config

```yaml
esphome:
  name: esp32-dev-03
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: "NAME"
  password: "PASS"

  manual_ip:
    static_ip: XXX.XXX.XXX.XXX
    gateway: XXX.XXX.XXX.XXX
    subnet: XXX.XXX.XXX.XXX
  

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esp32 Dev 03 Fallback Hotspot"
    password: "PASS"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  platform: esphome

i2c:
  sda: 21
  scl: 22
  scan: True
  id: bus_a

esp32_ble_tracker:

bluetooth_proxy:
  active: true

sensor:
  - platform: bh1750
    name: "esp_dev_03_BH1750 Illuminance"
    address: 0x23
    update_interval: 60s
  - platform: dht
    model: AM2302
    pin: 13
    temperature:
      name: "esp_dev_03_AM2302 Temperature"
    humidity:
      name: "esp_dev_03_AM2302 Humidity"
    update_interval: 60s
```

### Anything in the logs that might be useful for us?

```txt
INFO ESPHome 2024.12.2
INFO Reading configuration /config/esp32_dev_03.yaml...
INFO Generating C++ source...
INFO Compiling app...
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/esphome/esphome/__main__.py", line 1036, in main
    return run_esphome(sys.argv)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 1023, in run_esphome
    rc = POST_CONFIG_ACTIONS[args.command](args, config)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 506, in command_run
    exit_code = compile_program(args, config)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/__main__.py", line 239, in compile_program
    rc = platformio_api.run_compile(config, CORE.verbose)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/platformio_api.py", line 108, in run_compile
    return run_platformio_cli_run(config, verbose, *args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/platformio_api.py", line 101, in run_platformio_cli_run
    return run_platformio_cli(*command, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/esphome/esphome/platformio_api.py", line 90, in run_platformio_cli
    import platformio.__main__
  File "/usr/local/lib/python3.11/dist-packages/platformio/__main__.py", line 21, in <module>
    from platformio import __version__, exception, maintenance
  File "/usr/local/lib/python3.11/dist-packages/platformio/maintenance.py", line 22, in <module>
    from platformio import __version__, app, exception, fs, telemetry
  File "/usr/local/lib/python3.11/dist-packages/platformio/telemetry.py", line 25, in <module>
    import requests
  File "/usr/local/lib/python3.11/dist-packages/requests/__init__.py", line 164, in <module>
    from .api import delete, get, head, options, patch, post, put, request
  File "/usr/local/lib/python3.11/dist-packages/requests/api.py", line 11, in <module>
    from . import sessions
  File "/usr/local/lib/python3.11/dist-packages/requests/sessions.py", line 15, in <module>
    from .adapters import HTTPAdapter
  File "/usr/local/lib/python3.11/dist-packages/requests/adapters.py", line 81, in <module>
    _preloaded_ssl_context.load_verify_locations(
ssl.SSLError: [X509] PEM lib (_ssl.c:4123)
```

**Comment by eximo84** [comment]
ok, sorry. Can ignore.  I have completely blown away my entire docker setup and redownloaded everything and it now appears to be working
