### ISSUE TITLE
Error for MDNS

### ISSUE THREAD

**Issue by moskovskiy82** [esphome/issues#6618]
### The problem

All the devices started to appear offline.
Running inside the docker container.
Network is set to host.

Tried to execute inside docker container aioesphomeapi-discover and got the following error

```
root@hass:/config# aioesphomeapi-discover
Traceback (most recent call last):
  File "/usr/local/bin/aioesphomeapi-discover", line 8, in <module>
    sys.exit(cli_entry_point())
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aioesphomeapi/discover.py", line 73, in cli_entry_point
    asyncio.run(main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/aioesphomeapi/discover.py", line 56, in main
    aiozc = AsyncZeroconf()
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/zeroconf/asyncio.py", line 166, in __init__
    self.zeroconf = zc or Zeroconf(
                          ^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/zeroconf/_core.py", line 180, in __init__
    listen_socket, respond_sockets = create_sockets(interfaces, unicast, ip_version, apple_p2p=apple_p2p)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/zeroconf/_utils/net.py", line 373, in create_sockets
    if add_multicast_member(cast(socket.socket, listen_socket), i):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/zeroconf/_utils/net.py", line 288, in add_multicast_member
    listen_socket.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, _value)
OSError: [Errno 105] No buffer space available

```

### Which version of ESPHome has the issue?

2024.12

### What type of installation are you using?

Docker

### What platform are you using?

ESP8266

**Comment by ssieb** [comment]
That's a docker or host issue.  A google search of the error message should find you some answers.
