### ISSUE TITLE
No RMT support for Neopixelbus Light

### ISSUE THREAD

**Issue by icefire555** [esphome/issues#846]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):** 

Docker/Unraid
**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 NODEMCU
**Affected component:**

https://esphome.io/components/light/neopixelbus.html

**Description of problem:**
I am unable to use the RMT method on an ESP32.

**Problem-relevant YAML-configuration entries:**
```yaml
light:
 - platform: neopixelbus
   type: BRG
   name: "GameRoom Lights"
   id: ledstrip
   method: ESP32_RMT_0
   num_leds: 295
   pin: GPIO2
   effects:
    - random:
    - strobe:
    - flicker:
    - addressable_rainbow:
    - addressable_color_wipe:
    - addressable_scan:
    - addressable_twinkle:
    - addressable_random_twinkle:
    - addressable_fireworks:
    - addressable_flicker:

```

**Logs (if applicable):**

```
INFO Reading configuration /config/gameroomlights.yaml...
ERROR Unexpected exception while reading configuration:
Traceback (most recent call last):
  File "/usr/local/bin/esphome", line 11, in <module>
    load_entry_point('esphome', 'console_scripts', 'esphome')()
  File "/usr/src/app/esphome/__main__.py", line 551, in main
    return run_esphome(sys.argv)
  File "/usr/src/app/esphome/__main__.py", line 529, in run_esphome
    config = read_config()
  File "/usr/src/app/esphome/config.py", line 808, in read_config
    res = load_config()
  File "/usr/src/app/esphome/config.py", line 668, in load_config
    return _load_config()
  File "/usr/src/app/esphome/config.py", line 656, in _load_config
    result = validate_config(config)
  File "/usr/src/app/esphome/config.py", line 561, in validate_config
    validated = comp.config_schema(input_conf)
  File "/usr/local/lib/python3.6/dist-packages/voluptuous/validators.py", line 208, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
  File "/usr/local/lib/python3.6/dist-packages/voluptuous/validators.py", line 283, in _exec
    v = func(v)
  File "/usr/local/lib/python3.6/dist-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.6/dist-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/app/esphome/components/neopixelbus/light.py", line 77, in validate_method_pin
    pins_ = method_pins[method]
KeyError: 'ESP32_RMT_0'

```

**Additional information and things you've tried:**
This is related to this problem. 
[https://github.com/esphome/issues/issues/839](url)
But it was closed before I could update it.

**Comment by OttoWinter** [comment]
See https://github.com/esphome/issues/issues/839 - already fixed
